name: test

channels:
  - bccp

dependencies:
  # Below are for building MP-Gadget
  # Pin to latest version compatible with mpich 3.3.2: https://github.com/AnacondaRecipes/mpich-feedstock/issues/5
  - mpich
  - gxx_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - boost
  # For the tests
  - python
  - numpy
  - matplotlib
  - mpi4py
  - nbodykit
  - configobj
