name: test

channels:
  - bccp

dependencies:
  # Below are for building MP-Gadget
  - gxx_linux-64
  - gcc_linux-64
  - mpich
  # For the tests
  - python
  - numpy
  - matplotlib
  - mpi4py
  - nbodykit
  - configobj
