name: test

channels:
  - bccp

dependencies:
  - python
  - mpi4py
  - nbodykit
  - matplotlib
  - numpy
  - configobj
  # Below are for building MP-Gadget
  - openmpi
  - gxx_linux-64
  - gcc_linux-64
