MP-Gadget: auxiliary_functions.c File Reference
auxiliary_functions.c File Reference
Macros
#define AUXILIARY_FUNCTIONS_C
#define inline
#define h All.HubbleParam
#define cm (h/All.UnitLength_in_cm)
#define g (h/All.UnitMass_in_g)
#define s (h/All.UnitTime_in_s)
#define erg (g*cm*cm/(s*s))
#define keV (1.602e-9*erg)
#define deg 1.0
#define m_p (PROTONMASS * g)
#define m_e (ELECTRONMASS * g)
#define k_B (BOLTZMANN * erg / deg)
#define LightSpeed (2.9979e10*cm/s)
#define HBAR (1.05457e-27 * cm * cm * g / s)
#define e2 (HBAR * LightSpeed / 137.04)
#define statcoul sqrt(erg * cm)
#define mpc2 (m_p * LightSpeed * LightSpeed)
#define mec2 (m_e * LightSpeed * LightSpeed)
#define c2 (LightSpeed * LightSpeed)
Functions
static double square (double A)
static double cube (double A)
static double IonizationGrade (SphParticle *Particle)
static double Comoving_ElectronDensity (SphParticle *Particle)
static double Physical_ElectronDensity (SphParticle *Particle)
static double ElectronDensity (SphParticle *Particle)
static double Comoving_NumberDensity (SphParticle *Particle)
static double Physical_NumberDensity (SphParticle *Particle)
static double PhysicalNumberDensity (SphParticle *Particle)
static double Comoving_Density (SphParticle *Particle)
static double Physical_Density (SphParticle *Particle)
static double Physical_InternalEnergy (SphParticle *Particle)
Macro Definition Documentation
AUXILIARY_FUNCTIONS_C
#define AUXILIARY_FUNCTIONS_C
Definition at line 2 of file auxiliary_functions.c.
c2
#define c2 (LightSpeed * LightSpeed)
Definition at line 33 of file auxiliary_functions.c.
Referenced by clockcmp(), cmp_seed_task(), fof_radix_origin(), and MakeCoolingTable().
cm
#define cm (h/All.UnitLength_in_cm)
Definition at line 12 of file auxiliary_functions.c.
Referenced by fof_finish_group_properties().
deg
#define deg 1.0
Definition at line 19 of file auxiliary_functions.c.
e2
#define e2 (HBAR * LightSpeed / 137.04)
Definition at line 27 of file auxiliary_functions.c.
Referenced by create_gadget_parameter_set().
erg
#define erg (g*cm*cm/(s*s))
Definition at line 15 of file auxiliary_functions.c.
g
#define g (h/All.UnitMass_in_g)
Definition at line 13 of file auxiliary_functions.c.
Referenced by cmp_seed_task(), hci_update_query_timer(), and slots_fork().
h
#define h All.HubbleParam
Definition at line 10 of file auxiliary_functions.c.
Referenced by density_ngbiter(), drift_integ(), force_treeev_shortrange(), force_treeevaluate_shortrange(), grav_short_pair_ngbiter(), gravkick_integ(), and hydrokick_integ().
HBAR
#define HBAR (1.05457e-27 * cm * cm * g / s)
Definition at line 25 of file auxiliary_functions.c.
inline
#define inline
Definition at line 5 of file auxiliary_functions.c.
k_B
#define k_B (BOLTZMANN * erg / deg)
Definition at line 22 of file auxiliary_functions.c.
keV
#define keV (1.602e-9*erg)
Definition at line 18 of file auxiliary_functions.c.
LightSpeed
#define LightSpeed (2.9979e10*cm/s)
Definition at line 23 of file auxiliary_functions.c.
m_e
#define m_e (ELECTRONMASS * g)
Definition at line 21 of file auxiliary_functions.c.
m_p
#define m_p (PROTONMASS * g)
Definition at line 20 of file auxiliary_functions.c.
Referenced by Comoving_ElectronDensity(), and Comoving_NumberDensity().
mec2
#define mec2 (m_e * LightSpeed * LightSpeed)
Definition at line 32 of file auxiliary_functions.c.
mpc2
#define mpc2 (m_p * LightSpeed * LightSpeed)
Definition at line 31 of file auxiliary_functions.c.
s
#define s (h/All.UnitTime_in_s)
Definition at line 14 of file auxiliary_functions.c.
Referenced by force_exchange_pseudodata(), and force_treeupdate_pseudos().
statcoul
#define statcoul sqrt(erg * cm)
Definition at line 29 of file auxiliary_functions.c.
Function Documentation
Comoving_Density()
static double Comoving_Density (SphParticle * Particle) inline static
Definition at line 114 of file auxiliary_functions.c.
 {
   return Particle->d.Density;
 }
Comoving_ElectronDensity()
static double Comoving_ElectronDensity (SphParticle * Particle) inline static
Definition at line 61 of file auxiliary_functions.c.
References HYDROGEN_MASSFRAC, IonizationGrade(), and m_p.
Referenced by Physical_ElectronDensity().
 {
   return (Particle->d.Density * HYDROGEN_MASSFRAC * IonizationGrade(Particle) / m_p);
 }
Comoving_NumberDensity()
static double Comoving_NumberDensity (SphParticle * Particle) inline static
Definition at line 89 of file auxiliary_functions.c.
References HYDROGEN_MASSFRAC, and m_p.
Referenced by Physical_NumberDensity().
 {
   return (Particle->d.Density * (3.0 * HYDROGEN_MASSFRAC + 1.0) / (4.0 * m_p));
 }
cube()
static double cube (double A) inline static
Definition at line 43 of file auxiliary_functions.c.
Referenced by Physical_Density(), Physical_ElectronDensity(), and Physical_NumberDensity().
 {
   return (A * A * A);
 }
ElectronDensity()
static double ElectronDensity (SphParticle * Particle) inline static
Definition at line 81 of file auxiliary_functions.c.
References Physical_ElectronDensity().
 {
   return Physical_ElectronDensity(Particle);
 }
IonizationGrade()
static double IonizationGrade (SphParticle * Particle) inline static
Definition at line 55 of file auxiliary_functions.c.
References HYDROGEN_MASSFRAC.
Referenced by Comoving_ElectronDensity().
 {
   return (1 + HYDROGEN_MASSFRAC) / (2 * HYDROGEN_MASSFRAC); /* always return full ionization */
 }
Physical_Density()
static double Physical_Density (SphParticle * Particle) inline static
Definition at line 120 of file auxiliary_functions.c.
References All, cube(), and global_data_all_processes::Time.
Referenced by Physical_InternalEnergy().
 {
   if(All.ComovingIntegrationOn)
     {
       return Particle->d.Density / cube(All.Time);
     }
   else
     {
       return Particle->d.Density;
     }
 }
Physical_ElectronDensity()
static double Physical_ElectronDensity (SphParticle * Particle) inline static
Definition at line 68 of file auxiliary_functions.c.
References All, Comoving_ElectronDensity(), cube(), and global_data_all_processes::Time.
Referenced by ElectronDensity().
 {
   if(All.ComovingIntegrationOn)
     {
       return Comoving_ElectronDensity(Particle) / cube(All.Time);
     }
   else
     {
       return Comoving_ElectronDensity(Particle);
     }
 }
Physical_InternalEnergy()
static double Physical_InternalEnergy (SphParticle * Particle) inline static
Definition at line 133 of file auxiliary_functions.c.
References GAMMA_MINUS1, and Physical_Density().
 {
   double rPhysicalDensity;
   rPhysicalDensity = Physical_Density(Particle);
   return Particle->Entropy * pow(rPhysicalDensity, GAMMA_MINUS1) / GAMMA_MINUS1;
 }
Physical_NumberDensity()
static double Physical_NumberDensity (SphParticle * Particle) inline static
Definition at line 95 of file auxiliary_functions.c.
References All, Comoving_NumberDensity(), cube(), and global_data_all_processes::Time.
Referenced by PhysicalNumberDensity().
 {
   if(All.ComovingIntegrationOn)
     {
       return Comoving_NumberDensity(Particle) / cube(All.Time);
     }
   else
     {
       return Comoving_NumberDensity(Particle);
     }
 }
PhysicalNumberDensity()
static double PhysicalNumberDensity (SphParticle * Particle) inline static
Definition at line 107 of file auxiliary_functions.c.
References Physical_NumberDensity().
 {
   return Physical_NumberDensity(Particle);
 }
square()
static double square (double A) inline static
Definition at line 37 of file auxiliary_functions.c.
 {
   return (A * A);
 }