MP-Gadget: libgadget/checkpoint.c File Reference
checkpoint.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "petaio.h"
#include "checkpoint.h"
#include "walltime.h"
#include "fof.h"
#include "utils.h"
Functions
void write_checkpoint (int snapnum, int WriteGroupID, int MetalReturnOn, double Time, const Cosmology *CP, const char *OutputDir, const int OutputDebugFields)
void dump_snapshot (const char *dump, const double Time, const Cosmology *CP, const char *OutputDir)
int find_last_snapnum (const char *OutputDir)
Function Documentation
dump_snapshot()
void dump_snapshot (const char * dump, const double Time, const Cosmology * CP, const char * OutputDir)
Definition at line 52 of file checkpoint.c.
 {
     struct IOTable IOTable = {0};
     register_io_blocks(&IOTable, 0, 1);
     register_debug_io_blocks(&IOTable);
     char * fname = fastpm_strdup_printf("%s/%s", OutputDir, dump);
     petaio_save_snapshot(fname, &IOTable, 1, Time, CP);
     destroy_io_blocks(&IOTable);
 }
References CP, destroy_io_blocks(), fastpm_strdup_printf(), petaio_save_snapshot(), register_debug_io_blocks(), and register_io_blocks().
Referenced by force_tree_build(), and run().
find_last_snapnum()
int find_last_snapnum (const char * OutputDir)
Definition at line 63 of file checkpoint.c.
 {
     /* FIXME: this is very fragile; should be fine */
     int snapnumber = -1;
     int ThisTask;
     MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
     if(ThisTask == 0) {
         char * buf = fastpm_strdup_printf("%s/Snapshots.txt", OutputDir);
         FILE * fd = fopen(buf, "r");
         if(fd == NULL) {
             snapnumber = -1;
         } else {
             double time;
             char ch;
             int line = 0;
             while (!feof(fd)) {
                 int n = fscanf(fd, "%d %lg%c", &snapnumber, &time, &ch);
 //                 message(1, "n = %d\n", n);
                 if (n == 3 && ch == '\n') {
                     line ++;
                     continue;
                 }
                 if (n == -1 && feof(fd)) {
                     continue;
                 }
                 endrun(1, "Failed to parse %s:%d for the last snap shot number.\n", buf, line);
             }
             fclose(fd);
         }
         myfree(buf);
     }
     MPI_Bcast(&snapnumber, 1, MPI_INT, 0, MPI_COMM_WORLD);
     return snapnumber;
 }
References endrun(), fastpm_strdup_printf(), myfree, and ThisTask.
Referenced by find_last_snapshot().
write_checkpoint()
void write_checkpoint (int snapnum, int WriteGroupID, int MetalReturnOn, double Time, const Cosmology * CP, const char * OutputDir, const int OutputDebugFields)
Definition at line 24 of file checkpoint.c.
 {
     walltime_measure("/Misc");
     /* write snapshot of particles */
     struct IOTable IOTable = {0};
     register_io_blocks(&IOTable, WriteGroupID, MetalReturnOn);
     if(OutputDebugFields)
         register_debug_io_blocks(&IOTable);
     char * fname = petaio_get_snapshot_fname(snapnum, OutputDir);
     petaio_save_snapshot(fname, &IOTable, 1, Time, CP);
     myfree(fname);
     destroy_io_blocks(&IOTable);
     walltime_measure("/Snapshot/Write");
     int ThisTask;
     MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
     if(ThisTask == 0) {
         char * buf = fastpm_strdup_printf("%s/Snapshots.txt", OutputDir);
         FILE * fd = fopen(buf, "a");
         fprintf(fd, "%03d %g\n", snapnum, Time);
         fclose(fd);
         myfree(buf);
     }
 }
References CP, destroy_io_blocks(), fastpm_strdup_printf(), myfree, petaio_get_snapshot_fname(), petaio_save_snapshot(), register_debug_io_blocks(), register_io_blocks(), ThisTask, and walltime_measure.
Referenced by run().