MP-Gadget: cooling.h File Reference
cooling.h File Reference
Classes
struct UVBG
Functions
void GetParticleUVBG (int i, struct UVBG *uvbg)
void GetGlobalUVBG (struct UVBG *uvbg)
double AbundanceRatios (double u, double rho, struct UVBG *uvbg, double *ne_guess, double *nH0_pointer, double *nHeII_pointer)
double GetCoolingTime (double u_old, double rho, struct UVBG *uvbg, double *ne_guess, double Z)
double DoCooling (double u_old, double rho, double dt, struct UVBG *uvbg, double *ne_guess, double Z)
double ConvertInternalEnergy2Temperature (double u, double ne)
void InitCool (void)
void IonizeParams (void)
void MakeCoolingTable (void)
void SetZeroIonization (void)
Function Documentation
AbundanceRatios()
double AbundanceRatios (double u, double rho, struct UVBG * uvbg, double * ne_guess, double * nH0_pointer, double * nHeII_pointer)
Definition at line 463 of file cooling.c.
References All, CoolingNoPrimordial, global_data_all_processes::CP, Cosmology::HubbleParam, abundance::ne, abundance::nH0, abundance::nHep, PROTONMASS, solve_equilibrium_temp(), global_data_all_processes::UnitDensity_in_cgs, global_data_all_processes::UnitPressure_in_cgs, and XH.
Referenced by GTNeutralHydrogenFraction().
 {
     if(CoolingNoPrimordial) return 0;
     double temp;
     struct abundance y;
     rho *= All.UnitDensity_in_cgs * All.CP.HubbleParam * All.CP.HubbleParam;    /* convert to physical cgs units */
     u *= All.UnitPressure_in_cgs / All.UnitDensity_in_cgs;
     double nHcgs = rho / PROTONMASS * XH;
     y.ne = *ne_guess;
     temp = solve_equilibrium_temp(u, nHcgs, uvbg, &y);
     *ne_guess = y.ne;
     *nH0_pointer = y.nH0;
     *nHeII_pointer = y.nHep;
     return temp;
 }
ConvertInternalEnergy2Temperature()
double ConvertInternalEnergy2Temperature (double u, double ne)
Definition at line 484 of file cooling.c.
References All, BOLTZMANN, CoolingNoPrimordial, fd, GAMMA_MINUS1, PROTONMASS, global_data_all_processes::UnitDensity_in_cgs, global_data_all_processes::UnitPressure_in_cgs, and yhelium.
Referenced by compute_global_quantities_of_system().
 {
     if(CoolingNoPrimordial) return 0;
     double mu;
     double temp;
     mu = (1 + 4 * yhelium) / (1 + yhelium + ne);
     u *= All.UnitPressure_in_cgs / All.UnitDensity_in_cgs;
     temp = GAMMA_MINUS1 / BOLTZMANN * u * PROTONMASS * mu;
     return temp;
 }
DoCooling()
double DoCooling (double u_old, double rho, double dt, struct UVBG * uvbg, double * ne_guess, double Z)
Definition at line 133 of file cooling.c.
References All, CoolingNoPrimordial, CoolingRateFromU(), global_data_all_processes::CP, endrun(), Cosmology::HubbleParam, MAXITER, message(), PROTONMASS, global_data_all_processes::UnitDensity_in_cgs, global_data_all_processes::UnitPressure_in_cgs, global_data_all_processes::UnitTime_in_s, and XH.
Referenced by cooling_direct().
 {
     if(CoolingNoPrimordial) return 0;
     double u, du;
     double u_lower, u_upper;
     double ratefact;
     double LambdaNet;
     int iter = 0;
     rho *= All.UnitDensity_in_cgs * All.CP.HubbleParam * All.CP.HubbleParam;    /* convert to physical cgs units */
     u_old *= All.UnitPressure_in_cgs / All.UnitDensity_in_cgs;
     dt *= All.UnitTime_in_s / All.CP.HubbleParam;
     double nHcgs = XH * rho / PROTONMASS;   /* hydrogen number dens in cgs units */
     ratefact = nHcgs * nHcgs / rho;
     u = u_old;
     u_lower = u;
     u_upper = u;
     LambdaNet = CoolingRateFromU(u, nHcgs, uvbg, ne_guess, Z);
     /* bracketing */
     if(u - u_old - ratefact * LambdaNet * dt < 0)   /* heating */
     {
         u_upper *= sqrt(1.1);
         u_lower /= sqrt(1.1);
             while(u_upper - u_old - ratefact * CoolingRateFromU(u_upper, nHcgs, uvbg, ne_guess, Z) * dt < 0)
             {
                 u_upper *= 1.1;
                 u_lower *= 1.1;
             }
     }
     if(u - u_old - ratefact * LambdaNet * dt > 0)
     {
         u_lower /= sqrt(1.1);
         u_upper *= sqrt(1.1);
             while(u_lower - u_old - ratefact * CoolingRateFromU(u_lower, nHcgs, uvbg, ne_guess, Z) * dt > 0)
             {
                 u_upper /= 1.1;
                 u_lower /= 1.1;
             }
     }
     do
     {
         u = 0.5 * (u_lower + u_upper);
         LambdaNet = CoolingRateFromU(u, nHcgs, uvbg, ne_guess, Z);
         if(u - u_old - ratefact * LambdaNet * dt > 0)
         {
             u_upper = u;
         }
         else
         {
             u_lower = u;
         }
         du = u_upper - u_lower;
         iter++;
         if(iter >= (MAXITER - 10))
             message(1, "u= %g\n", u);
     }
     while(fabs(du / u) > 1.0e-6 && iter < MAXITER);
     if(iter >= MAXITER)
     {
         endrun(10, "failed to converge in DoCooling()\n");
     }
     u *= All.UnitDensity_in_cgs / All.UnitPressure_in_cgs;  /* to internal units */
     return u;
 }
GetCoolingTime()
double GetCoolingTime (double u_old, double rho, struct UVBG * uvbg, double * ne_guess, double Z)
Definition at line 220 of file cooling.c.
References All, CoolingNoPrimordial, CoolingRateFromU(), global_data_all_processes::CP, Cosmology::HubbleParam, PROTONMASS, global_data_all_processes::UnitDensity_in_cgs, global_data_all_processes::UnitPressure_in_cgs, global_data_all_processes::UnitTime_in_s, and XH.
Referenced by cooling_direct().
 {
     if(CoolingNoPrimordial) return 0;
     double u;
     double ratefact;
     double LambdaNet, coolingtime;
     rho *= All.UnitDensity_in_cgs * All.CP.HubbleParam * All.CP.HubbleParam;    /* convert to physical cgs units */
     u_old *= All.UnitPressure_in_cgs / All.UnitDensity_in_cgs;
     double nHcgs = XH * rho / PROTONMASS;   /* hydrogen number dens in cgs units */
     ratefact = nHcgs * nHcgs / rho;
     u = u_old;
     LambdaNet = CoolingRateFromU(u, nHcgs, uvbg, ne_guess, Z);
     /* bracketing */
     if(LambdaNet >= 0)      /* ups, we have actually heating due to UV background */
         return 0;
     coolingtime = u_old / (-ratefact * LambdaNet);
     coolingtime *= All.CP.HubbleParam / All.UnitTime_in_s;
     return coolingtime;
 }
GetGlobalUVBG()
void GetGlobalUVBG (struct UVBG * uvbg)
Definition at line 1112 of file cooling.c.
Referenced by cooling_direct().
{
     memcpy(uvbg, &GlobalUVBG, sizeof(struct UVBG));
 }
GetParticleUVBG()
void GetParticleUVBG (int i, struct UVBG * uvbg)
Definition at line 1088 of file cooling.c.
References global_data_all_processes::a, All, global_data_all_processes::cf, interp_eval_periodic(), P, UVF, and global_data_all_processes::UVRedshiftThreshold.
Referenced by cooling_direct(), GTJUV(), and GTNeutralHydrogenFraction().
{
     double z = 1 / All.cf.a - 1;
     if(All.UVRedshiftThreshold >= 0.0 && z > All.UVRedshiftThreshold) {
         /* if a threshold is set, disable UV bg above that redshift */
         memset(uvbg, 0, sizeof(struct UVBG));
         return;
     }
     if(UVF.disabled) {
         /* directly use the TREECOOL table if UVF is disabled */
         memcpy(uvbg, &GlobalUVBG, sizeof(struct UVBG));
         return;
     }
     double pos[3];
     int k;
     for(k = 0; k < 3; k ++) {
         pos[k] = P[i].Pos[k];
     }
     double zreion = interp_eval_periodic(&UVF.interp, pos, UVF.Table);
     if(zreion < z) {
         memset(uvbg, 0, sizeof(struct UVBG));
     } else {
         memcpy(uvbg, &GlobalUVBG, sizeof(struct UVBG));
     }
 }
InitCool()
void InitCool (void)
Definition at line 922 of file cooling.c.
References All, CoolingNoMetal, CoolingNoPrimordial, global_data_all_processes::CoolingOn, InitCoolMemory(), InitMetalCooling(), InitUVF(), MakeCoolingTable(), message(), global_data_all_processes::MetalCoolFile, ReadIonizeParams(), and global_data_all_processes::TreeCoolFile.
Referenced by begrun().
 {
     /* The table will be initialized to z=0 */
     if(!All.CoolingOn) {
         CoolingNoPrimordial = 1;
         CoolingNoMetal = 1;
         return;
     }
     InitCoolMemory();
     MakeCoolingTable();
     if(strlen(All.TreeCoolFile) == 0) {
         CoolingNoPrimordial = 1;
         message(0, "No TreeCool file is provided. Cooling is broken. OK for DM only runs. \n");
     } else {
         CoolingNoPrimordial = 0;
         ReadIonizeParams(All.TreeCoolFile);
     }
     /* now initialize the metal cooling table from cloudy; we got this file
      * from vogelsberger's Arepo simulations; it is supposed to be
      * cloudy + UVB - H and He; look so.
      * the table contains only 1 Z_sun values. Need to be scaled to the
      * metallicity.
      *
      * */
             /* let's see if the Metal Cool File is magic NoMetal */
     if(strlen(All.MetalCoolFile) == 0) {
         CoolingNoMetal = 1;
     } else {
         CoolingNoMetal = 0;
         InitMetalCooling();
     }
     InitUVF();
 }
IonizeParams()
void IonizeParams (void)
Definition at line 869 of file cooling.c.
References CoolingNoPrimordial, and IonizeParamsTable().
Referenced by main(), and set_global_time().
 {
     if(CoolingNoPrimordial) return;
     IonizeParamsTable();
 }
MakeCoolingTable()
void MakeCoolingTable (void)
Definition at line 601 of file cooling.c.
References All, Alphad, AlphaHep, AlphaHepp, AlphaHp, Betaff, BetaH0, BetaHep, BOLTZMANN, c2, COOLTABT, deltaT, ethmin, eV_to_erg, eV_to_K, GAMMA_MINUS1, GammaeH0, GammaeHe0, GammaeHep, HYDROGEN_MASSFRAC, mhboltz, global_data_all_processes::MinGasTemp, NCOOLTAB, P, PROTONMASS, Tmax, Tmin, XH, and yhelium.
Referenced by InitCool(), and main().
 {
     int i;
     double T;
     double Tfact;
 #ifdef NEW_RATES
     double dE, P, A, X, K, U, T_eV;
     double b0, b1, b2, b3, b4, b5, c0, c1, c2, c3, c4, c5, y;   /* used in Scholz-Walter fit */
     double E1s_2, Gamma1s_2s, Gamma1s_2p;
 #endif
     XH = 0.76;
     yhelium = (1 - XH) / (4 * XH);
     mhboltz = PROTONMASS / BOLTZMANN;
     if(All.MinGasTemp > 0.0)
         Tmin = log10(0.1 * All.MinGasTemp);
     else
         Tmin = 1.0;
     deltaT = (Tmax - Tmin) / NCOOLTAB;
     ethmin = pow(10.0, Tmin) * (1. + yhelium) / ((1. + 4. * yhelium) * mhboltz * GAMMA_MINUS1);
     /* minimum internal energy for neutral gas */
     for(i = 0; i <= NCOOLTAB; i++)
     {
         BetaH0[i] =
             BetaHep[i] =
             Betaff[i] =
             AlphaHp[i] = AlphaHep[i] = AlphaHepp[i] = Alphad[i] = GammaeH0[i] = GammaeHe0[i] = GammaeHep[i] = 0;
         T = pow(10.0, Tmin + deltaT * i);
         Tfact = 1.0 / (1 + sqrt(T / 1.0e5));
         if(118348 / T < 70)
             BetaH0[i] = 7.5e-19 * exp(-118348 / T) * Tfact;
 #ifdef NEW_RATES
         /* Scholtz-Walters 91 fit */
         if(T >= 2.0e3 && T < 1e8)
         {
             if(T >= 2.0e3 && T < 6.0e4)
             {
                 b0 = -3.299613e1;
                 b1 = 1.858848e1;
                 b2 = -6.052265;
                 b3 = 8.603783e-1;
                 b4 = -5.717760e-2;
                 b5 = 1.451330e-3;
                 c0 = -1.630155e2;
                 c1 = 8.795711e1;
                 c2 = -2.057117e1;
                 c3 = 2.359573;
                 c4 = -1.339059e-1;
                 c5 = 3.021507e-3;
             }
             else
             {
                 if(T >= 6.0e4 && T < 6.0e6)
                 {
                     b0 = 2.869759e2;
                     b1 = -1.077956e2;
                     b2 = 1.524107e1;
                     b3 = -1.080538;
                     b4 = 3.836975e-2;
                     b5 = -5.467273e-4;
                     c0 = 5.279996e2;
                     c1 = -1.939399e2;
                     c2 = 2.718982e1;
                     c3 = -1.883399;
                     c4 = 6.462462e-2;
                     c5 = -8.811076e-4;
                 }
                 else
                 {
                     b0 = -2.7604708e3;
                     b1 = 7.9339351e2;
                     b2 = -9.1198462e1;
                     b3 = 5.1993362;
                     b4 = -1.4685343e-1;
                     b5 = 1.6404093e-3;
                     c0 = -2.8133632e3;
                     c1 = 8.1509685e2;
                     c2 = -9.4418414e1;
                     c3 = 5.4280565;
                     c4 = -1.5467120e-1;
                     c5 = 1.7439112e-3;
                 }
                 y = log(T);
                 E1s_2 = 10.2;   /* eV */
                 Gamma1s_2s =
                     exp(b0 + b1 * y + b2 * y * y + b3 * y * y * y + b4 * y * y * y * y + b5 * y * y * y * y * y);
                 Gamma1s_2p =
                     exp(c0 + c1 * y + c2 * y * y + c3 * y * y * y + c4 * y * y * y * y + c5 * y * y * y * y * y);
                 T_eV = T / eV_to_K;
                 BetaH0[i] = E1s_2 * eV_to_erg * (Gamma1s_2s + Gamma1s_2p) * exp(-E1s_2 / T_eV);
             }
         }
 #endif
         if(473638 / T < 70)
             BetaHep[i] = 5.54e-17 * pow(T, -0.397) * exp(-473638 / T) * Tfact;
         Betaff[i] = 1.43e-27 * sqrt(T) * (1.1 + 0.34 * exp(-(5.5 - log10(T)) * (5.5 - log10(T)) / 3));
 #ifdef NEW_RATES
         AlphaHp[i] = 6.28e-11 * pow(T / 1000, -0.2) / (1. + pow(T / 1.0e6, 0.7)) / sqrt(T);
 #else
         AlphaHp[i] = 8.4e-11 * pow(T / 1000, -0.2) / (1. + pow(T / 1.0e6, 0.7)) / sqrt(T);  /* old Cen92 fit */
 #endif
         AlphaHep[i] = 1.5e-10 * pow(T, -0.6353);
 #ifdef NEW_RATES
         AlphaHepp[i] = 3.36e-10 * pow(T / 1000, -0.2) / (1. + pow(T / 4.0e6, 0.7)) / sqrt(T);
 #else
         AlphaHepp[i] = 4. * AlphaHp[i]; /* old Cen92 fit */
 #endif
         if(470000 / T < 70)
             Alphad[i] = 1.9e-3 * pow(T, -1.5) * exp(-470000 / T) * (1. + 0.3 * exp(-94000 / T));
 #ifdef NEW_RATES
         T_eV = T / eV_to_K;
         /* Voronov 97 fit */
         /* hydrogen */
         dE = 13.6;
         P = 0.0;
         A = 0.291e-7;
         X = 0.232;
         K = 0.39;
         U = dE / T_eV;
         GammaeH0[i] = A * (1.0 + P * sqrt(U)) * pow(U, K) * exp(-U) / (X + U);
         /* Helium */
         dE = 24.6;
         P = 0.0;
         A = 0.175e-7;
         X = 0.18;
         K = 0.35;
         U = dE / T_eV;
         GammaeHe0[i] = A * (1.0 + P * sqrt(U)) * pow(U, K) * exp(-U) / (X + U);
         /* Hellium II */
         dE = 54.4;
         P = 1.0;
         A = 0.205e-8;
         X = 0.265;
         K = 0.25;
         U = dE / T_eV;
         GammaeHep[i] = A * (1.0 + P * sqrt(U)) * pow(U, K) * exp(-U) / (X + U);
 #else
         if(157809.1 / T < 70)
             GammaeH0[i] = 5.85e-11 * sqrt(T) * exp(-157809.1 / T) * Tfact;
         if(285335.4 / T < 70)
             GammaeHe0[i] = 2.38e-11 * sqrt(T) * exp(-285335.4 / T) * Tfact;
         if(631515.0 / T < 70)
             GammaeHep[i] = 5.68e-12 * sqrt(T) * exp(-631515.0 / T) * Tfact;
 #endif
     }
 }
SetZeroIonization()
void SetZeroIonization (void)
Definition at line 917 of file cooling.c.
References epsH0, epsHe0, epsHep, gJH0, gJHe0, gJHep, and J_UV.
Referenced by cooling_direct(), and main().
 {
     memset(&GlobalUVBG, 0, sizeof(GlobalUVBG));
 }