MP-Gadget: libgadget/cooling.c File Reference
cooling.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <bigfile.h>
#include "utils/endrun.h"
#include "utils/mymalloc.h"
#include "utils/interp.h"
#include "physconst.h"
#include "cooling.h"
#include "cooling_rates.h"
#include "cooling_qso_lightup.h"
#include "cosmology.h"
Macros
#define MAXITER 1000
Functions
void init_cooling (const char *TreeCoolFile, const char *MetalCoolFile, char *reion_hist_file, struct cooling_units cu, Cosmology *CP)
static double get_lambdanet (double rho, double u, double redshift, double Z, struct UVBG *uvbg, double *ne_guess, int isHeIIIionized)
double DoCooling (double redshift, double u_old, double rho, double dt, struct UVBG *uvbg, double *ne_guess, double Z, double MinEgySpec, int isHeIIIionized)
double GetCoolingTime (double redshift, double u_old, double rho, struct UVBG *uvbg, double *ne_guess, double Z)
double GetNeutralFraction (double u_old, double rho, const struct UVBG *uvbg, double ne_init)
double GetHeliumIonFraction (int ion, double u_old, double rho, const struct UVBG *uvbg, double ne_init)
Variables
static struct cooling_units coolunits
Macro Definition Documentation
MAXITER
#define MAXITER 1000
Definition at line 46 of file cooling.c.
Function Documentation
DoCooling()
double DoCooling (double redshift, double u_old, double rho, double dt, struct UVBG * uvbg, double * ne_guess, double Z, double MinEgySpec, int isHeIIIionized)
Definition at line 71 of file cooling.c.
 {
     if(!coolunits.CoolingOn) return 0;
     double u, du;
     double u_lower, u_upper;
     double LambdaNet;
     int iter = 0;
     rho *= coolunits.density_in_phys_cgs / PROTONMASS;  /* convert to (physical) protons/cm^3 */
     u_old *= coolunits.uu_in_cgs;
     MinEgySpec *= coolunits.uu_in_cgs;
     if(u_old < MinEgySpec)
         u_old = MinEgySpec;
     dt *= coolunits.tt_in_s;
     u = u_old;
     u_lower = u;
     u_upper = u;
     LambdaNet = get_lambdanet(rho, u, redshift, Z, uvbg, ne_guess, isHeIIIionized);
     /* bracketing */
     if(u - u_old - LambdaNet * dt < 0)  /* heating */
     {
         do
         {
             u_lower = u_upper;
             u_upper *= 1.1;
         } while(u_upper - u_old - get_lambdanet(rho, u_upper, redshift, Z, uvbg, ne_guess, isHeIIIionized) * dt < 0);
     }
     else
     {
         do {
             u_upper = u_lower;
             u_lower /= 1.1;
             /* This means that we don't need an initial bracket*/
             if(u_upper <= MinEgySpec) {
                 break;
             }
         } while(u_lower - u_old - get_lambdanet(rho, u_lower, redshift, Z, uvbg, ne_guess, isHeIIIionized) * dt > 0);
     }
     do
     {
         u = 0.5 * (u_lower + u_upper);
         /* If we know that the new energy
          * is below the minimum gas internal energy, we are done here.*/
         if(u_upper <= MinEgySpec) {
             u = MinEgySpec;
             break;
         }
         LambdaNet = get_lambdanet(rho, u, redshift, Z, uvbg, ne_guess, isHeIIIionized);
         if(u - u_old - LambdaNet * dt > 0)
         {
             u_upper = u;
         }
         else
         {
             u_lower = u;
         }
         du = u_upper - u_lower;
         iter++;
         if(iter >= (MAXITER - 10))
             message(1, "u= %g\n", u);
     }
     while(fabs(du / u) > 1.0e-6 && iter < MAXITER);
     if(iter >= MAXITER)
     {
         endrun(10, "failed to converge in DoCooling()\n");
     }
     u /= coolunits.uu_in_cgs;   /*convert back to internal units */
     return u;
 }
References cooling_units::CoolingOn, coolunits, cooling_units::density_in_phys_cgs, endrun(), get_lambdanet(), MAXITER, message(), PROTONMASS, cooling_units::tt_in_s, and cooling_units::uu_in_cgs.
Referenced by cooling_direct(), and test_DoCooling().
get_lambdanet()
static double get_lambdanet (double rho, double u, double redshift, double Z, struct UVBG * uvbg, double * ne_guess, int isHeIIIionized) static
Definition at line 57 of file cooling.c.
 {
     double LambdaNet = get_heatingcooling_rate(rho, u, 1 - HYDROGEN_MASSFRAC, redshift, Z, uvbg, ne_guess);
     if(!isHeIIIionized) {
         /* get_long_mean_free_path_heating returns the heating in units of erg/s/cm^3,
          * the factor of the mean density converts from erg/s/cm^3 to erg/s/g */
         LambdaNet += get_long_mean_free_path_heating(redshift) / (coolunits.rho_crit_baryon * pow(1 + redshift,3));
     }
     return LambdaNet;
 }
References coolunits, get_heatingcooling_rate(), get_long_mean_free_path_heating(), HYDROGEN_MASSFRAC, and cooling_units::rho_crit_baryon.
Referenced by DoCooling().
GetCoolingTime()
double GetCoolingTime (double redshift, double u_old, double rho, struct UVBG * uvbg, double * ne_guess, double Z)
Definition at line 157 of file cooling.c.
 {
     if(!coolunits.CoolingOn) return 0;
     /* convert to physical cgs units */
     rho *= coolunits.density_in_phys_cgs / PROTONMASS;
     u_old *= coolunits.uu_in_cgs;
     /* Note: this does not include the long mean free path heating from helium reionization*/
     double LambdaNet = get_heatingcooling_rate(rho, u_old, 1 - HYDROGEN_MASSFRAC, redshift, Z, uvbg, ne_guess);
     if(LambdaNet >= 0)      /* ups, we have actually heating due to UV background */
         return 0;
     double coolingtime = u_old / (- LambdaNet);
     /*Convert back to internal units*/
     coolingtime /= coolunits.tt_in_s;
     return coolingtime;
 }
References cooling_units::CoolingOn, coolunits, cooling_units::density_in_phys_cgs, get_heatingcooling_rate(), HYDROGEN_MASSFRAC, PROTONMASS, cooling_units::tt_in_s, and cooling_units::uu_in_cgs.
Referenced by cooling_relaxed(), get_egyeff(), init_cooling_and_star_formation(), and test_DoCooling().
GetHeliumIonFraction()
double GetHeliumIonFraction (int ion, double u_old, double rho, const struct UVBG * uvbg, double ne_init)
Definition at line 192 of file cooling.c.
 {
     /* convert to physical cgs units */
     rho *= coolunits.density_in_phys_cgs / PROTONMASS;
     u_old *= coolunits.uu_in_cgs;
     double helium_ion = get_helium_ion_phys_cgs(ion, rho, u_old, 1 - HYDROGEN_MASSFRAC, uvbg, ne_init);
     return helium_ion;
 }
References coolunits, cooling_units::density_in_phys_cgs, get_helium_ion_phys_cgs(), HYDROGEN_MASSFRAC, PROTONMASS, and cooling_units::uu_in_cgs.
Referenced by get_helium_neutral_fraction_sfreff().
GetNeutralFraction()
double GetNeutralFraction (double u_old, double rho, const struct UVBG * uvbg, double ne_init)
Definition at line 181 of file cooling.c.
 {
     /* convert to physical cgs units */
     rho *= coolunits.density_in_phys_cgs / PROTONMASS;
     u_old *= coolunits.uu_in_cgs;
     double nh0 = get_neutral_fraction_phys_cgs(rho, u_old, 1 - HYDROGEN_MASSFRAC, uvbg, &ne_init);
     return nh0;
 }
References coolunits, cooling_units::density_in_phys_cgs, get_neutral_fraction_phys_cgs(), HYDROGEN_MASSFRAC, PROTONMASS, and cooling_units::uu_in_cgs.
Referenced by get_neutral_fraction_sfreff().
init_cooling()
void init_cooling (const char * TreeCoolFile, const char * MetalCoolFile, char * reion_hist_file, struct cooling_units cu, Cosmology * CP)
Definition at line 36 of file cooling.c.
 {
     coolunits = cu;
     /*Initialize the cooling rates*/
     if(coolunits.CoolingOn)
         init_cooling_rates(TreeCoolFile, MetalCoolFile, CP);
     /* Initialize the helium reionization model*/
     init_qso_lightup(reion_hist_file);
 }
References cooling_units::CoolingOn, coolunits, CP, init_cooling_rates(), and init_qso_lightup().
Referenced by init_cooling_and_star_formation(), and test_DoCooling().
Variable Documentation
coolunits
struct cooling_units coolunits static
Definition at line 1 of file cooling.c.
Referenced by DoCooling(), get_lambdanet(), GetCoolingTime(), GetHeliumIonFraction(), GetNeutralFraction(), init_cooling(), init_cooling_and_star_formation(), test_DoCooling(), and test_heatingcooling_rate().