MP-Gadget: libgadget/cooling_qso_lightup.h File Reference
cooling_qso_lightup.h File Reference
#include "forcetree.h"
#include "fof.h"
#include "utils/paramset.h"
Functions
void set_qso_lightup_params (ParameterSet *ps)
void init_qso_lightup (char *reion_hist_file)
void do_heiii_reionization (double atime, FOFGroups *fof, DomainDecomp *ddecomp, Cosmology *CP, double uu_in_cgs, FILE *FdHelium)
double get_long_mean_free_path_heating (double redshift)
int during_helium_reionization (double redshift)
int qso_lightup_on (void)
int need_change_helium_ionization_fraction (double atime)
Function Documentation
do_heiii_reionization()
void do_heiii_reionization (double atime, FOFGroups * fof, DomainDecomp * ddecomp, Cosmology * CP, double uu_in_cgs, FILE * FdHelium)
Definition at line 640 of file cooling_qso_lightup.c.
 {
     if(!QSOLightupParams.QSOLightupOn)
         return;
     if(atime < 1/(1+QSOLightupParams.heIIIreion_start))
         return;
     /* Do nothing if we are past the end of the table.*/
     if(atime > He_zz[Nreionhist-1])
         return;
     walltime_measure("/Misc");
     //message(0, "HeII: Reionization initiated.\n");
     turn_on_quasars(atime, fof, ddecomp, CP, uu_in_cgs, FdHelium);
 }
References CP, QSOPriv::fof, He_zz, qso_lightup_params::heIIIreion_start, Nreionhist, qso_lightup_params::QSOLightupOn, QSOLightupParams, turn_on_quasars(), QSOPriv::uu_in_cgs, and walltime_measure.
Referenced by run().
during_helium_reionization()
int during_helium_reionization (double redshift)
Definition at line 667 of file cooling_qso_lightup.c.
 {
     if(!QSOLightupParams.QSOLightupOn)
         return 0;
     if(redshift > QSOLightupParams.heIIIreion_start)
         return 0;
     /* Past the end of the table, it has finished.*/
     if(redshift < 1./He_zz[Nreionhist-1] - 1)
         return 0;
     return 1;
 }
References He_zz, qso_lightup_params::heIIIreion_start, Nreionhist, qso_lightup_params::QSOLightupOn, and QSOLightupParams.
Referenced by run().
get_long_mean_free_path_heating()
double get_long_mean_free_path_heating (double redshift)
Definition at line 249 of file cooling_qso_lightup.c.
 {
     if(!QSOLightupParams.QSOLightupOn)
         return 0;
     if(redshift > QSOLightupParams.heIIIreion_start)
         return 0;
     if(redshift == last_zz)
         return last_long_mfp_heating;
     double atime = 1/(1+redshift);
     /* Guard against the end of the table*/
     if(atime > He_zz[Nreionhist-1])
         return 0;
     double long_mfp_heating = gsl_interp_eval(LMFP_intp, He_zz, LMFP, atime, NULL);
     last_zz = redshift;
     last_long_mfp_heating = long_mfp_heating;
     return long_mfp_heating;
 }
References He_zz, qso_lightup_params::heIIIreion_start, last_long_mfp_heating, last_zz, LMFP, LMFP_intp, Nreionhist, qso_lightup_params::QSOLightupOn, and QSOLightupParams.
Referenced by get_lambdanet().
init_qso_lightup()
void init_qso_lightup (char * reion_hist_file)
Definition at line 238 of file cooling_qso_lightup.c.
 {
     if(QSOLightupParams.QSOLightupOn)
         load_heii_reion_hist(reion_hist_file);
 }
References load_heii_reion_hist(), qso_lightup_params::QSOLightupOn, and QSOLightupParams.
Referenced by init_cooling().
need_change_helium_ionization_fraction()
int need_change_helium_ionization_fraction (double atime)
Definition at line 657 of file cooling_qso_lightup.c.
 {
     double desired_ion_frac = gsl_interp_eval(HeIII_intp, He_zz, XHeIII, atime, NULL);
     double curionfrac = gas_ionization_fraction();
     if(curionfrac < desired_ion_frac)
         return 1;
     return 0;
 }
References gas_ionization_fraction(), He_zz, HeIII_intp, and XHeIII.
Referenced by run().
qso_lightup_on()
int qso_lightup_on (void)
Definition at line 682 of file cooling_qso_lightup.c.
 {
     return QSOLightupParams.QSOLightupOn;
 }
References qso_lightup_params::QSOLightupOn, and QSOLightupParams.
Referenced by open_outputfiles().
set_qso_lightup_params()
void set_qso_lightup_params (ParameterSet * ps)
Definition at line 94 of file cooling_qso_lightup.c.
 {
     int ThisTask;
     MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
     if(ThisTask == 0) {
         QSOLightupParams.QSOLightupOn = param_get_int(ps, "QSOLightupOn");
         QSOLightupParams.qso_candidate_max_mass = param_get_double(ps, "QSOMaxMass");
         QSOLightupParams.qso_candidate_min_mass = param_get_double(ps, "QSOMinMass");
         QSOLightupParams.mean_bubble = param_get_double(ps, "QSOMeanBubble");
         QSOLightupParams.var_bubble = param_get_double(ps, "QSOVarBubble");
         QSOLightupParams.heIIIreion_finish_frac = param_get_double(ps, "QSOHeIIIReionFinishFrac");
     }
     MPI_Bcast(&QSOLightupParams, sizeof(struct qso_lightup_params), MPI_BYTE, 0, MPI_COMM_WORLD);
 }
References qso_lightup_params::heIIIreion_finish_frac, qso_lightup_params::mean_bubble, param_get_double(), param_get_int(), qso_lightup_params::qso_candidate_max_mass, qso_lightup_params::qso_candidate_min_mass, qso_lightup_params::QSOLightupOn, QSOLightupParams, ThisTask, and qso_lightup_params::var_bubble.
Referenced by read_parameter_file().