MP-Gadget: cosmology.h File Reference
cosmology.h File Reference
#include <stddef.h>
#include "kspace-neutrinos/omega_nu_single.h"
Classes
struct Cosmology
struct FunctionOfK
Functions
void function_of_k_normalize_sigma (FunctionOfK *fk, double R, double sigma)
double function_of_k_eval (FunctionOfK *fk, double k)
double function_of_k_tophat_sigma (FunctionOfK *fk, double R)
double hubble_function (double a)
double GrowthFactor (double astart, double aend)
double F_Omega (double a)
void init_cosmology (Cosmology *CP, double TimeBegin, double box)
Function Documentation
F_Omega()
double F_Omega (double a)
Definition at line 139 of file cosmology.c.
References growth().
 {
     double dD1da=0;
     double D1 = growth(a, &dD1da);
     return a / D1 * dD1da;
 }
function_of_k_eval()
double function_of_k_eval (FunctionOfK * fk, double k)
Definition at line 176 of file cosmology.c.
References FunctionOfK::k, FunctionOfK::P, FunctionOfK::size, and FunctionOfK::table.
Referenced by sigma2_int().
 {
     /* ignore the 0 mode */
     if(k == 0) return 1;
     int l = 0;
     int r = fk->size - 1;
     while(r - l > 1) {
         int m = (r + l) / 2;
         if(k < fk->table[m].k)
             r = m;
         else
             l = m;
     }
     double k2 = fk->table[r].k,
            k1 = fk->table[l].k;
     double p2 = fk->table[r].P,
            p1 = fk->table[l].P;
     if(l == r) {
         return fk->table[l].P;
     }
     if(p1 == 0 || p2 == 0 || k1 == 0 || k2 == 0) {
         /* if any of the p is zero, use linear interpolation */
         double p = (k - k1) * p2 + (k2 - k) * p1;
         p /= (k2 - k1);
         return p;
     } else {
         k = log(k);
         p1 = log(p1);
         p2 = log(p2);
         k1 = log(k1);
         k2 = log(k2);
         double p = (k - k1) * p2 + (k2 - k) * p1;
         p /= (k2 - k1);
         return exp(p);
     }
 }
function_of_k_normalize_sigma()
void function_of_k_normalize_sigma (FunctionOfK * fk, double R, double sigma)
Definition at line 234 of file cosmology.c.
References function_of_k_tophat_sigma(), FunctionOfK::P, FunctionOfK::size, and FunctionOfK::table.
{
     double old = function_of_k_tophat_sigma(fk, R);
     int i;
     for(i = 0; i < fk->size; i ++) {
         fk->table[i].P *= sigma / old;
     };
 }
function_of_k_tophat_sigma()
double function_of_k_tophat_sigma (FunctionOfK * fk, double R)
Definition at line 218 of file cosmology.c.
References sigma2_int().
Referenced by function_of_k_normalize_sigma().
 {
     gsl_integration_workspace * w = gsl_integration_workspace_alloc (1000);
     void * params[] = {fk, &R};
     double result,abserr;
     gsl_function F;
     F.function = &sigma2_int;
     F.params = params;
     /* note: 500/R is here chosen as integration boundary (infinity) */
     gsl_integration_qags (&F, 0, 500. / R, 0, 1e-4,1000,w,&result, &abserr);
     //   printf("gsl_integration_qng in TopHatSigma2. Result %g, error: %g, intervals: %lu\n",result, abserr,w->size);
     gsl_integration_workspace_free (w);
     return sqrt(result);
 }
GrowthFactor()
double GrowthFactor (double astart, double aend)
Definition at line 78 of file cosmology.c.
References growth().
Referenced by gravpm_force().
 {
     return growth(astart, NULL) / growth(aend, NULL);
 }
hubble_function()
double hubble_function (double a)
Definition at line 55 of file cosmology.c.
References growth(), Cosmology::Hubble, Cosmology::OmegaBaryon, Cosmology::OmegaCDM, OmegaFLD(), Cosmology::OmegaG, Cosmology::OmegaK, Cosmology::OmegaLambda, Cosmology::ONu, and Cosmology::RadiationOn.
Referenced by drift_integ(), gravkick_integ(), growth(), growth_ode(), hydrokick_integ(), init_cosmology(), kernel(), and set_global_time().
 {
     double hubble_a;
     /* first do the terms in SQRT */
     hubble_a = CP->OmegaLambda;
     hubble_a += OmegaFLD(a);
     hubble_a += CP->OmegaK / (a * a);
     hubble_a += (CP->OmegaCDM + CP->OmegaBaryon) / (a * a * a);
     if(CP->RadiationOn) {
         hubble_a += CP->OmegaG / (a * a * a * a);
         hubble_a += get_omega_nu(&CP->ONu, a);
     }
     /* Now finish it up. */
     hubble_a = CP->Hubble * sqrt(hubble_a);
     return (hubble_a);
 }
init_cosmology()
void init_cosmology (Cosmology * CP, double TimeBegin, double box)
Definition at line 15 of file cosmology.c.
References C, Cosmology::CMBTemperature, GRAVITY, Cosmology::Hubble, HUBBLE, hubble_function(), Cosmology::HubbleParam, message(), Cosmology::MNu, Cosmology::Omega0, Cosmology::OmegaBaryon, Cosmology::OmegaCDM, Cosmology::OmegaG, Cosmology::OmegaK, Cosmology::OmegaLambda, Cosmology::ONu, and STEFAN_BOLTZMANN.
Referenced by set_units().
 {
     CP = CP_in;
     /*With slightly relativistic massive neutrinos, for consistency we need to include radiation.
      * A note on normalisation (as of 08/02/2012):
      * CAMB appears to set Omega_Lambda + Omega_Matter+Omega_K = 1,
      * calculating Omega_K in the code and specifying Omega_Lambda and Omega_Matter in the paramfile.
      * This means that Omega_tot = 1+ Omega_r + Omega_g, effectively
      * making h0 (very) slightly larger than specified, and the Universe is no longer flat!
      */
     CP->OmegaCDM = CP->Omega0 - CP->OmegaBaryon;
     CP->OmegaK = 1.0 - CP->Omega0 - CP->OmegaLambda;
     /* Omega_g = 4 \sigma_B T_{CMB}^4 8 \pi G / (3 c^3 H^2) */
     CP->OmegaG = 4 * STEFAN_BOLTZMANN
                   * pow(CP->CMBTemperature, 4)
                   * (8 * M_PI * GRAVITY)
                   / (3*C*C*C*HUBBLE*HUBBLE)
                   / (CP->HubbleParam*CP->HubbleParam);
     init_omega_nu(&CP->ONu, CP->MNu, TimeBegin, CP->HubbleParam, CP->CMBTemperature);
     /* Neutrinos will be included in Omega0, if massive.
      * This ensures that OmegaCDM contains only non-relativistic species.*/
     if(CP->MNu[0] + CP->MNu[1] + CP->MNu[2] > 0) {
         CP->OmegaCDM -= get_omega_nu(&CP->ONu, 1);
         /* Warn if we have a large enough box that neutrinos are not free-streaming on the largest scales.
          * Free-streaming scale is ~500 Mpc at z=99 for M_nu = 0.3 eV.
          * FIXME: Implement scale dependent growth correction, by differentiating transfer functions.*/
         /*Neutrino thermal velocity in cm/s*/
         double v_th = BOLEVK*(TNUCMB*CP->CMBTemperature)/(CP->MNu[0] + CP->MNu[1] + CP->MNu[2])*3. / TimeBegin * C;
         /*Neutrino free-streaming length from Lesgourgues & Pastor in (comoving) cm/h*/
         double nufs = 2 * M_PI * sqrt(2/3.) * v_th / (hubble_function(TimeBegin)/CP->Hubble * HUBBLE)/TimeBegin;
         /*Box should be in comoving cm/h: we ask for 1/4 of the box because sample variance will matter on larger scales.*/
         if(nufs < box/4.)
             message(0,"WARNING: Neutrino free-streaming/box size =  %g. May be inaccurate as scale-dependent growth is not modelled.\n",nufs/box);
     }
 }