MP-Gadget: densitykernel.h File Reference
densitykernel.h File Reference
Classes
struct DensityKernel
Macros
#define NUMDIMS 3
#define NORM_COEFF 4.188790204786
Functions
double density_kernel_desnumngb (DensityKernel *kernel, double eta)
void density_kernel_init (DensityKernel *kernel, double H)
void density_kernel_init_with_type (DensityKernel *kernel, int type, double H)
double density_kernel_wk (DensityKernel *kernel, double u)
double density_kernel_dwk (DensityKernel *kernel, double u)
double density_kernel_volume (DensityKernel *kernel)
static double density_kernel_dW (DensityKernel *kernel, double u, double wk, double dwk)
static double dotproduct (double v1[3], double v2[3])
static void crossproduct (double v1[3], double v2[3], double out[3])
Macro Definition Documentation
NORM_COEFF
#define NORM_COEFF 4.188790204786
Coefficient for kernel normalization. Note: 4.0/3 * PI = 4.188790204786
Definition at line 3 of file densitykernel.h.
Referenced by density_kernel_desnumngb(), and density_kernel_volume().
NUMDIMS
#define NUMDIMS 3
For 3D-normalized kernel
Definition at line 2 of file densitykernel.h.
Referenced by density_check_neighbours(), density_kernel_desnumngb(), density_kernel_dW(), density_kernel_init_with_type(), density_kernel_volume(), and density_postprocess().
Function Documentation
crossproduct()
static void crossproduct (double v1[3], double v2[3], double out[3]) inline static
Definition at line 56 of file densitykernel.h.
Referenced by add_particle_to_group(), density_ngbiter(), and fof_finish_group_properties().
 {
     static int D2[3] = {1, 2, 0};
     static int D3[3] = {2, 0, 1};
     int d1, d2, d3;
     for(d1 = 0; d1 < 3; d1++)
     {
         d2 = D2[d1];
         d3 = D3[d1];
         out[d1] = (v1[d2] * v2[d3] -  v2[d2] * v1[d3]);
     }
 }
density_kernel_desnumngb()
double density_kernel_desnumngb (DensityKernel * kernel, double eta)
Definition at line 124 of file densitykernel.c.
References NORM_COEFF, NUMDIMS, DensityKernel::support, and support.
Referenced by read_parameter_file().
 {
     /* this returns the expected number of ngb in for given sph resolution
      * deseta */
     /* See Price: arxiv 1012.1885. eq 12 */
     double support = kernel->support;
     return NORM_COEFF * pow(support * eta, NUMDIMS);
 }
density_kernel_dW()
static double density_kernel_dW (DensityKernel * kernel, double u, double wk, double dwk) inline static
Definition at line 40 of file densitykernel.h.
References dwk, DensityKernel::Hinv, and NUMDIMS.
Referenced by density_ngbiter().
 {
     return - (NUMDIMS * kernel->Hinv * wk + u * dwk);
 }
density_kernel_dwk()
double density_kernel_dwk (DensityKernel * kernel, double u)
Definition at line 108 of file densitykernel.c.
References DensityKernel::dWknorm, KERNELS, support, and DensityKernel::type.
Referenced by density_ngbiter(), and hydro_ngbiter().
 {
     double support = KERNELS[kernel->type].support;
     return kernel->dWknorm *
         KERNELS[kernel->type].dwk(kernel, u * support);
 }
density_kernel_init()
void density_kernel_init (DensityKernel * kernel, double H)
Definition at line 140 of file densitykernel.c.
References All, DENSITY_KERNEL_CUBIC_SPLINE, density_kernel_init_with_type(), DENSITY_KERNEL_QUARTIC_SPLINE, DENSITY_KERNEL_QUINTIC_SPLINE, global_data_all_processes::DensityKernelType, and endrun().
Referenced by density_ngbiter(), hydro_ngbiter(), and read_parameter_file().
 {
     int t = -1;
     if(All.DensityKernelType == DENSITY_KERNEL_CUBIC_SPLINE) {
         t = 0;
     } else
     if(All.DensityKernelType == DENSITY_KERNEL_QUINTIC_SPLINE) {
         t = 1;
     } else
     if(All.DensityKernelType == DENSITY_KERNEL_QUARTIC_SPLINE) {
         t = 2;
     } else {
         endrun(1, "Density Kernel type is unknown\n");
     }
     density_kernel_init_with_type(kernel, t, H);
 }
density_kernel_init_with_type()
void density_kernel_init_with_type (DensityKernel * kernel, int type, double H)
Definition at line 158 of file densitykernel.c.
References DensityKernel::dWknorm, DensityKernel::H, DensityKernel::HH, DensityKernel::Hinv, KERNELS, DensityKernel::name, NUMDIMS, sigma, DensityKernel::support, DensityKernel::type, and DensityKernel::Wknorm.
Referenced by density_kernel_init().
 {
     kernel->H = H;
     kernel->HH = H * H;
     kernel->Hinv = 1. / H;
     kernel->type = type;
     kernel->name = KERNELS[kernel->type].name;
     kernel->support = KERNELS[kernel->type].support;
     double sigma = KERNELS[kernel->type].sigma[NUMDIMS - 1];
     double hinv = kernel->Hinv * kernel->support;
     kernel->Wknorm = sigma * pow(hinv, NUMDIMS);
     kernel->dWknorm = kernel->Wknorm * hinv;
 }
density_kernel_volume()
double density_kernel_volume (DensityKernel * kernel)
Definition at line 134 of file densitykernel.c.
References DensityKernel::H, NORM_COEFF, and NUMDIMS.
Referenced by density_ngbiter().
 {
     return NORM_COEFF * pow(kernel->H, NUMDIMS);
 }
density_kernel_wk()
double density_kernel_wk (DensityKernel * kernel, double u)
Definition at line 116 of file densitykernel.c.
References KERNELS, support, DensityKernel::type, and DensityKernel::Wknorm.
Referenced by density_ngbiter().
 {
     double support = KERNELS[kernel->type].support;
     return kernel->Wknorm *
         KERNELS[kernel->type].wk(kernel, u * support);
 }
dotproduct()
static double dotproduct (double v1[3], double v2[3]) inline static
Definition at line 46 of file densitykernel.h.
Referenced by density_ngbiter(), and hydro_ngbiter().
 {
     double r =0;
     int d;
     for(d = 0; d < 3; d ++) {
         r += v1[d] * v2[d];
     }
     return r;
 }