MP-Gadget: libgadget/densitykernel.c File Reference
densitykernel.c File Reference
#include <math.h>
#include "densitykernel.h"
#include "utils/endrun.h"
Functions
double wk_cs (DensityKernel *kernel, double q)
double dwk_cs (DensityKernel *kernel, double q)
static double wk_qus (DensityKernel *kernel, double q)
static double dwk_qus (DensityKernel *kernel, double q)
static double wk_qs (DensityKernel *kernel, double q)
static double dwk_qs (DensityKernel *kernel, double q)
double density_kernel_dwk (DensityKernel *kernel, double u)
double density_kernel_wk (DensityKernel *kernel, double u)
double density_kernel_desnumngb (DensityKernel *kernel, double eta)
double density_kernel_volume (DensityKernel *kernel)
static void density_kernel_init_with_type (DensityKernel *kernel, int type, double H)
void density_kernel_init (DensityKernel *kernel, double H, enum DensityKernelType type)
Variables
struct {
const char * name
double(* wk)(DensityKernel *kernel, double q)
double(* dwk)(DensityKernel *kernel, double q)
double support
double sigma [3]
} KERNELS []
Function Documentation
density_kernel_desnumngb()
double density_kernel_desnumngb (DensityKernel * kernel, double eta)
Definition at line 124 of file densitykernel.c.
 {
     /* this returns the expected number of ngb in for given sph resolution
      * deseta */
     /* See Price: arxiv 1012.1885. eq 12 */
     double support = kernel->support;
     return NORM_COEFF * pow(support * eta, NUMDIMS);
 }
References kernel(), NORM_COEFF, NUMDIMS, and support.
Referenced by GetDensityKernelType().
density_kernel_dwk()
double density_kernel_dwk (DensityKernel * kernel, double u)
Definition at line 108 of file densitykernel.c.
 {
     double support = KERNELS[kernel->type].support;
     return kernel->dWknorm *
         KERNELS[kernel->type].dwk(kernel, u * support);
 }
References kernel(), KERNELS, and support.
Referenced by density_ngbiter(), and hydro_ngbiter().
density_kernel_init()
void density_kernel_init (DensityKernel * kernel, double H, enum DensityKernelType type)
Definition at line 157 of file densitykernel.c.
 {
     int t = -1;
     if(type == DENSITY_KERNEL_CUBIC_SPLINE) {
         t = 0;
     } else
     if(type == DENSITY_KERNEL_QUINTIC_SPLINE) {
         t = 1;
     } else
     if(type == DENSITY_KERNEL_QUARTIC_SPLINE) {
         t = 2;
     } else {
         endrun(1, "Density Kernel type is unknown\n");
     }
     density_kernel_init_with_type(kernel, t, H);
 }
References DENSITY_KERNEL_CUBIC_SPLINE, density_kernel_init_with_type(), DENSITY_KERNEL_QUARTIC_SPLINE, DENSITY_KERNEL_QUINTIC_SPLINE, endrun(), and kernel().
Referenced by blackhole_accretion_ngbiter(), blackhole_dynfric_ngbiter(), blackhole_feedback_ngbiter(), density_ngbiter(), GetDensityKernelType(), hydro_ngbiter(), metal_return_ngbiter(), set_density_params(), and stellar_density_ngbiter().
density_kernel_init_with_type()
static void density_kernel_init_with_type (DensityKernel * kernel, int type, double H) static
Definition at line 140 of file densitykernel.c.
 {
     kernel->H = H;
     kernel->HH = H * H;
     kernel->Hinv = 1. / H;
     kernel->type = type;
     kernel->name = KERNELS[kernel->type].name;
     kernel->support = KERNELS[kernel->type].support;
     double sigma = KERNELS[kernel->type].sigma[NUMDIMS - 1];
     double hinv = kernel->Hinv * kernel->support;
     kernel->Wknorm = sigma * pow(hinv, NUMDIMS);
     kernel->dWknorm = kernel->Wknorm * hinv;
 }
References kernel(), KERNELS, NUMDIMS, and sigma.
Referenced by density_kernel_init().
density_kernel_volume()
double density_kernel_volume (DensityKernel * kernel)
Definition at line 134 of file densitykernel.c.
 {
     return NORM_COEFF * pow(kernel->H, NUMDIMS);
 }
References kernel(), NORM_COEFF, and NUMDIMS.
Referenced by density_ngbiter(), and stellar_density_ngbiter().
density_kernel_wk()
double density_kernel_wk (DensityKernel * kernel, double u)
Definition at line 116 of file densitykernel.c.
 {
     double support = KERNELS[kernel->type].support;
     return kernel->Wknorm *
         KERNELS[kernel->type].wk(kernel, u * support);
 }
References kernel(), KERNELS, and support.
Referenced by blackhole_accretion_ngbiter(), blackhole_dynfric_ngbiter(), blackhole_feedback_ngbiter(), density_ngbiter(), metal_return_ngbiter(), and stellar_density_ngbiter().
dwk_cs()
double dwk_cs (DensityKernel * kernel, double q)
Definition at line 33 of file densitykernel.c.
{
     if(q < 1.0) {
         return - 0.25 * 3 * pow(2 - q, 2) + 3 * pow(1 - q, 2);
     }
     if(q < 2.0) {
         return -0.25 * 3 * pow(2 - q, 2);
     }
     return 0.0;
 }
dwk_qs()
static double dwk_qs (DensityKernel * kernel, double q) static
Definition at line 78 of file densitykernel.c.
{
     if(q < 1.0) {
         return -5 * pow(3 - q, 4) + 30 * pow(2 - q, 4)
              - 75 * pow (1 - q, 4);
     }
     if(q < 2.0) {
         return -5 * pow(3 - q, 4) + 30 * pow(2 - q, 4);
     }
     if(q < 3.0) {
         return -5 * pow(3 - q, 4);
     }
     return 0.0;
 }
dwk_qus()
static double dwk_qus (DensityKernel * kernel, double q) static
Definition at line 54 of file densitykernel.c.
{
     if(q < 0.5) {
         return -4 * pow(2.5 - q, 3) + 20 * pow(1.5 - q, 3) - 40 * pow(0.5 - q, 3);
     }
     if(q < 1.5) {
         return -4 * pow(2.5 - q, 3) + 20 * pow(1.5 - q, 3);
     }
     if(q < 2.5) {
         return -4 * pow(2.5 - q, 3);
     }
     return 0.0;
 }
wk_cs()
double wk_cs (DensityKernel * kernel, double q)
We use Price 1012.1885 kernels sml in Gadget is the support big H in Price,
u = r / H q = r / h
luckily, wk = 1 / H ** 3 W_volker(u) = 1 / h ** 3 W_price(q) and dwk = 1 / H ** 4 dw_volker/du = 1 / h ** 4 dw_price/dq
wk_xx is Price eq 6 , 7, 8, without sigma
the function density_kernel_wk and _dwk takes u to maintain compatibility with volker's gadget.
Definition at line 24 of file densitykernel.c.
{
     if(q < 1.0) {
         return 0.25 * pow(2 - q, 3) - pow(1 - q, 3);
     }
     if(q < 2.0) {
         return 0.25 * pow(2 - q, 3);
     }
     return 0.0;
 }
wk_qs()
static double wk_qs (DensityKernel * kernel, double q) static
Definition at line 66 of file densitykernel.c.
{
     if(q < 1.0) {
         return pow(3 - q, 5) - 6 * pow(2 - q, 5) + 15 * pow(1 - q, 5);
     }
     if(q < 2.0) {
         return pow(3 - q, 5)- 6 * pow(2 - q, 5);
     }
     if(q < 3.0) {
         return pow(3 - q, 5);
     }
     return 0.0;
 }
wk_qus()
static double wk_qus (DensityKernel * kernel, double q) static
Definition at line 42 of file densitykernel.c.
{
     if(q < 0.5) {
         return pow(2.5 - q, 4) - 5 * pow(1.5 - q, 4) + 10 * pow(0.5 - q, 4);
     }
     if(q < 1.5) {
         return pow(2.5 - q, 4) - 5 * pow(1.5 - q, 4);
     }
     if(q < 2.5) {
         return pow(2.5 - q, 4);
     }
     return 0.0;
 }
Variable Documentation
dwk
double(* dwk) (DensityKernel *kernel, double q) (DensityKernel * kernel, double q)
Definition at line 95 of file densitykernel.c.
Referenced by density_kernel_dW(), and density_ngbiter().
struct { ... } KERNELS[]
Initial value:
= {
    { "CubicSpline", wk_cs, dwk_cs, 2.,
        {2 / 3., 10 / (7 * M_PI), 1 / M_PI} },
    { "QuinticSpline", wk_qs, dwk_qs, 3.,
        {1 / 120., 7 / (478 * M_PI), 1 / (120 * M_PI)} },
    { "QuarticSpline", wk_qus, dwk_qus, 2.5,
        {1 / 24., 96 / (1199 * M_PI), 1 / (20 * M_PI)} },
}
Referenced by density_kernel_dwk(), density_kernel_init_with_type(), and density_kernel_wk().
name
const char* name
Definition at line 93 of file densitykernel.c.
Referenced by _bigfile_utils_create_block_from_c_array(), _get_attr_double(), _get_attr_int(), allocator_alloc(), allocator_alloc_va(), allocator_init(), allocator_malloc_init(), BlackHoleFeedbackMethodAction(), io_register_io_block(), mpsort_increment_timer(), OutputListAction(), param_declare(), param_declare_double(), param_declare_enum(), param_declare_int(), param_declare_string(), param_emit(), param_format_value(), param_get_double(), param_get_enum(), param_get_int(), param_get_schema(), param_get_string(), param_get_string2(), param_is_nil(), param_set_action(), param_set_from_string(), saveblock(), StarformationCriterionAction(), walltime_add_full(), walltime_add_internal(), walltime_clock(), walltime_clock_insert(), walltime_get(), walltime_get_symbol(), walltime_get_time(), walltime_measure_full(), walltime_measure_internal(), and walltime_report().
sigma
double sigma[3]
Definition at line 97 of file densitykernel.c.
Referenced by density_kernel_init_with_type(), function_of_k_normalize_sigma(), gaussian_rng(), and init_cooling_and_star_formation().
support
double support
Definition at line 96 of file densitykernel.c.
Referenced by density_kernel_desnumngb(), density_kernel_dwk(), and density_kernel_wk().
wk
double(* wk) (DensityKernel *kernel, double q) (DensityKernel * kernel, double q)
Definition at line 94 of file densitykernel.c.
Referenced by blackhole_accretion_ngbiter(), blackhole_dynfric_ngbiter(), blackhole_feedback_ngbiter(), density_kernel_dW(), density_ngbiter(), metal_return_ngbiter(), sfr_wind_weight_ngbiter(), and stellar_density_ngbiter().