MP-Gadget: drift.h File Reference
drift.h File Reference
Functions
void drift_particle (int i, inttime_t ti1)
void lock_particle (int i)
void unlock_particle (int i)
void drift_active_particles (inttime_t ti1)
void drift_all_particles (inttime_t ti1)
Function Documentation
drift_active_particles()
void drift_active_particles (inttime_t ti1)
Definition at line 161 of file drift.c.
References ActiveParticle, NumActiveParticle, real_drift_particle(), and walltime_measure.
 {
     int i;
     walltime_measure("/Misc");
 #pragma omp parallel for
     for(i = 0; i < NumActiveParticle; i++)
         real_drift_particle(ActiveParticle[i], ti1);
     walltime_measure("/Drift/Active");
 }
drift_all_particles()
void drift_all_particles (inttime_t ti1)
Definition at line 173 of file drift.c.
References part_manager_type::NumPart, PartManager, real_drift_particle(), and walltime_measure.
Referenced by run().
 {
     int i;
     walltime_measure("/Misc");
 #pragma omp parallel for
     for(i = 0; i < PartManager->NumPart; i++)
         real_drift_particle(i, ti1);
     walltime_measure("/Drift/All");
 }
drift_particle()
void drift_particle (int i, inttime_t ti1)
Definition at line 24 of file drift.c.
References drift_particle_full().
Referenced by force_treeev_shortrange(), force_treeevaluate_shortrange(), and treewalk_visit_ngbiter().
{
     drift_particle_full(i, ti1, 1);
 }
lock_particle()
void lock_particle (int i)
Definition at line 18 of file drift.c.
References P.
Referenced by cooling_direct(), fof_primary_ngbiter(), and HEADl().
{
     pthread_spin_lock(&P[i].SpinLock);
 }
unlock_particle()
void unlock_particle (int i)
Definition at line 21 of file drift.c.
References P.
Referenced by cooling_direct(), fof_primary_ngbiter(), fofp_merge(), and HEADl().
{
     pthread_spin_unlock(&P[i].SpinLock);
 }