MP-Gadget: libgadget/utils/event.h File Reference
event.h File Reference
Classes
struct EIBase
struct EventHandler
struct EventSpec
Macros
#define MAXEH 8
Typedefs
typedef struct EventHandler EventHandler
typedef struct EventSpec EventSpec
typedef int(* eventfunc) (EIBase *event, void *userdata)
Functions
int event_listen (EventSpec *e, eventfunc func, void *userdata)
int event_unlisten (EventSpec *e, eventfunc func, void *userdata)
int event_emit (EventSpec *eh, EIBase *event)
Variables
EventSpec EventSlotsFork
EventSpec EventSlotsAfterGC
Macro Definition Documentation
MAXEH
#define MAXEH 8
Definition at line 20 of file event.h.
Typedef Documentation
eventfunc
typedef int(* eventfunc) (EIBase *event, void *userdata)
Definition at line 12 of file event.h.
EventHandler
typedef struct EventHandler EventHandler
Definition at line 1 of file event.h.
EventSpec
typedef struct EventSpec EventSpec
Definition at line 1 of file event.h.
Function Documentation
event_emit()
int event_emit (EventSpec * eh, EIBase * event)
Definition at line 44 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         eh->h[i].func(event, eh->h[i].userdata);
     }
     return 0;
 }
References EventHandler::func, EventSpec::h, EventSpec::used, and EventHandler::userdata.
Referenced by slots_split_particle().
event_listen()
int event_listen (EventSpec * e, eventfunc func, void * userdata)
Definition at line 6 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         if(eh->h[i].func == func && eh->h[i].userdata == userdata) {
             return 0;
         }
     }
     if(eh->used == MAXEH) {
         /* overflown */
         abort();
     }
     eh->h[eh->used].func = func;
     eh->h[eh->used].userdata = userdata;
     eh->used ++;
     return 0;
 }
References EventHandler::func, EventSpec::h, MAXEH, EventSpec::used, and EventHandler::userdata.
Referenced by force_tree_rebuild(), and rebuild_activelist().
event_unlisten()
int event_unlisten (EventSpec * e, eventfunc func, void * userdata)
Definition at line 26 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         if(eh->h[i].func == func && eh->h[i].userdata == userdata) {
             break;
         }
     }
     if(i == eh->used || eh->used == 0) {
         return 1;
     }
     memmove(&eh->h[i], &eh->h[i+1], sizeof(eh->h[0]) * (eh->used - i - 1));
     eh->used --;
     return 0;
 }
References EventHandler::func, EventSpec::h, EventSpec::used, and EventHandler::userdata.
Referenced by force_tree_free(), and free_activelist().
Variable Documentation
EventSlotsAfterGC
EventSpec EventSlotsAfterGC extern
Definition at line 55 of file event.c.
EventSlotsFork
EventSpec EventSlotsFork extern
Definition at line 54 of file event.c.
Referenced by force_tree_free(), force_tree_rebuild(), free_activelist(), rebuild_activelist(), and slots_split_particle().