MP-Gadget: libgadget/utils/event.c File Reference
event.c File Reference
#include "event.h"
#include <stdlib.h>
#include <string.h>
Functions
int event_listen (EventSpec *eh, eventfunc func, void *userdata)
int event_unlisten (EventSpec *eh, eventfunc func, void *userdata)
int event_emit (EventSpec *eh, EIBase *event)
Variables
EventSpec EventSlotsFork = {"SlotsFork", 0, {{0}}}
EventSpec EventSlotsAfterGC = {"SlotsAfterGC", 0, {{0}}}
Function Documentation
event_emit()
int event_emit (EventSpec * eh, EIBase * event)
Definition at line 44 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         eh->h[i].func(event, eh->h[i].userdata);
     }
     return 0;
 }
References EventHandler::func, EventSpec::h, EventSpec::used, and EventHandler::userdata.
Referenced by slots_split_particle().
event_listen()
int event_listen (EventSpec * eh, eventfunc func, void * userdata)
Definition at line 6 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         if(eh->h[i].func == func && eh->h[i].userdata == userdata) {
             return 0;
         }
     }
     if(eh->used == MAXEH) {
         /* overflown */
         abort();
     }
     eh->h[eh->used].func = func;
     eh->h[eh->used].userdata = userdata;
     eh->used ++;
     return 0;
 }
References EventHandler::func, EventSpec::h, MAXEH, EventSpec::used, and EventHandler::userdata.
Referenced by force_tree_rebuild(), and rebuild_activelist().
event_unlisten()
int event_unlisten (EventSpec * eh, eventfunc func, void * userdata)
Definition at line 26 of file event.c.
 {
     int i;
     for(i = 0; i < eh->used; i ++) {
         if(eh->h[i].func == func && eh->h[i].userdata == userdata) {
             break;
         }
     }
     if(i == eh->used || eh->used == 0) {
         return 1;
     }
     memmove(&eh->h[i], &eh->h[i+1], sizeof(eh->h[0]) * (eh->used - i - 1));
     eh->used --;
     return 0;
 }
References EventHandler::func, EventSpec::h, EventSpec::used, and EventHandler::userdata.
Referenced by force_tree_free(), and free_activelist().
Variable Documentation
EventSlotsAfterGC
EventSpec EventSlotsAfterGC = {"SlotsAfterGC", 0, {{0}}}
Definition at line 55 of file event.c.
EventSlotsFork
EventSpec EventSlotsFork = {"SlotsFork", 0, {{0}}}
Definition at line 54 of file event.c.
Referenced by force_tree_free(), force_tree_rebuild(), free_activelist(), rebuild_activelist(), and slots_split_particle().