MP-Gadget: libgadget/gravity.c File Reference
gravity.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "utils.h"
#include "gravity.h"
#include "shortrange-kernel.c"
Macros
#define NTAB (sizeof(shortrange_force_kernels) / sizeof(shortrange_force_kernels[0]))
Functions
void gravshort_fill_ntab (const enum ShortRangeForceWindowType ShortRangeForceWindowType, const double Asmth)
int grav_apply_short_range_window (double r, double *fac, double *pot, const double cellsize)
Variables
static float shortrange_table [NTAB]
static float shortrange_table_potential [NTAB]
static float shortrange_table_tidal [NTAB]
Macro Definition Documentation
NTAB
#define NTAB (sizeof(shortrange_force_kernels) / sizeof(shortrange_force_kernels[0]))
Definition at line 17 of file gravity.c.
Function Documentation
grav_apply_short_range_window()
int grav_apply_short_range_window (double r, double * fac, double * pot, const double cellsize)
Definition at line 55 of file gravity.c.
 {
     const double dx = shortrange_force_kernels[1][0];
     double i = (r / cellsize / dx);
     size_t tabindex = floor(i);
     if(tabindex >= NTAB - 1)
         return 1;
     /* use a linear interpolation; */
     *fac *= (tabindex + 1 - i) * shortrange_table[tabindex] + (i - tabindex) * shortrange_table[tabindex + 1];
     *pot *= (tabindex + 1 - i) * shortrange_table_potential[tabindex] + (i - tabindex) * shortrange_table_potential[tabindex];
     return 0;
 }
References NTAB, shortrange_force_kernels, shortrange_table, and shortrange_table_potential.
Referenced by apply_accn_to_output(), and grav_short_pair_ngbiter().
gravshort_fill_ntab()
void gravshort_fill_ntab (const enum ShortRangeForceWindowType ShortRangeForceWindowType ShortRangeForceWindowType , const double Asmth)
Definition at line 23 of file gravity.c.
 {
     if (ShortRangeForceWindowType == SHORTRANGE_FORCE_WINDOW_TYPE_EXACT) {
         if(Asmth != 1.5) {
             endrun(0, "The short range force window is calibrated for Asmth = 1.5, but running with %g\n", Asmth);
         }
     }
     size_t i;
     for(i = 0; i < NTAB; i++)
     {
         /* force_kernels is in units of mesh points; */
         double u = shortrange_force_kernels[i][0] * 0.5 / Asmth;
         switch (ShortRangeForceWindowType) {
             case SHORTRANGE_FORCE_WINDOW_TYPE_EXACT:
                 /* Notice that the table is only calibrated for smth of 1.25*/
                 shortrange_table[i] = shortrange_force_kernels[i][2]; /* ~ erfc(u) + 2.0 * u / sqrt(M_PI) * exp(-u * u); */
                 /* The potential of the calibrated kernel is a bit off, so we still use erfc here; we do not use potential anyways.*/
                 shortrange_table_potential[i] = shortrange_force_kernels[i][1];
             break;
             case SHORTRANGE_FORCE_WINDOW_TYPE_ERFC:
                 shortrange_table[i] = erfc(u) + 2.0 * u / sqrt(M_PI) * exp(-u * u);
                 shortrange_table_potential[i] = erfc(u);
             break;
         }
         /* we don't have a table for that and don't use it anyways. */
         shortrange_table_tidal[i] = 4.0 * u * u * u / sqrt(M_PI) * exp(-u * u);
     }
 }
References endrun(), NTAB, shortrange_force_kernels, SHORTRANGE_FORCE_WINDOW_TYPE_ERFC, SHORTRANGE_FORCE_WINDOW_TYPE_EXACT, shortrange_table, shortrange_table_potential, and shortrange_table_tidal.
Referenced by begrun(), and do_force_test().
Variable Documentation
shortrange_table
float shortrange_table[NTAB] static
variables for short-range lookup table
Definition at line 20 of file gravity.c.
Referenced by grav_apply_short_range_window(), and gravshort_fill_ntab().
shortrange_table_potential
float shortrange_table_potential[NTAB] static
Definition at line 20 of file gravity.c.
Referenced by grav_apply_short_range_window(), and gravshort_fill_ntab().
shortrange_table_tidal
float shortrange_table_tidal[NTAB] static
Definition at line 20 of file gravity.c.
Referenced by gravshort_fill_ntab().