MP-Gadget: gravshort.h File Reference
gravshort.h File Reference
#include "partmanager.h"
#include "treewalk.h"
Classes
struct TreeWalkNgbIterGravShort
struct TreeWalkQueryGravShort
struct TreeWalkResultGravShort
Functions
static int grav_short_haswork (int i, TreeWalk *tw)
static void grav_short_postprocess (int i, TreeWalk *tw)
static void grav_short_copy (int place, TreeWalkQueryGravShort *input, TreeWalk *tw)
static void grav_short_reduce (int place, TreeWalkResultGravShort *result, enum TreeWalkReduceMode mode, TreeWalk *tw)
int grav_apply_short_range_window (double r, double *fac, double *facpot)
Function Documentation
grav_apply_short_range_window()
int grav_apply_short_range_window (double r, double * fac, double * facpot)
Definition at line 47 of file longrange.c.
References All, global_data_all_processes::Asmth, global_data_all_processes::BoxSize, global_data_all_processes::Nmesh, NTAB, shortrange_table, and shortrange_table_potential.
Referenced by force_treeev_shortrange(), grav_short_pair_ngbiter(), and grav_short_reduce().
 {
     const double asmth = All.Asmth * All.BoxSize / All.Nmesh;
     const double asmthfac = 0.5 / asmth * (NTAB / 3.0);
     int tabindex = (int) (asmthfac * r);
     if(tabindex < NTAB)
     {
         *fac *= shortrange_table[tabindex];
         *pot *= shortrange_table_potential[tabindex];
         return 0;
     } else {
         return 1;
     }
 }
grav_short_copy()
static void grav_short_copy (int place, TreeWalkQueryGravShort * input, TreeWalk * tw) static
Definition at line 50 of file gravshort.h.
References All, FORCE_SOFTENING(), global_data_all_processes::G, TreeWalkQueryGravShort::OldAcc, P, TreeWalkQueryGravShort::Soft, and TreeWalkQueryGravShort::Type.
Referenced by grav_short_pair(), grav_short_tree(), and grav_short_tree_old().
 {
     input->Type = P[place].Type;
     input->Soft = FORCE_SOFTENING(place);
     /*Compute old acceleration before we over-write things*/
     double aold=0;
     int i;
     for(i = 0; i < 3; i++) {
        double ax = P[place].GravAccel[i] + P[place].GravPM[i];
        aold += ax*ax;
     }
     input->OldAcc = sqrt(aold)/All.G;
 }
grav_short_haswork()
static int grav_short_haswork (int i, TreeWalk * tw) static
Definition at line 28 of file gravshort.h.
Referenced by grav_short_pair(), grav_short_tree(), and grav_short_tree_old().
 {
     return 1; /* gravity applies to all particles. Including Tracer particles to enhance numerical stability. */
 }
grav_short_postprocess()
static void grav_short_postprocess (int i, TreeWalk * tw) static
Definition at line 34 of file gravshort.h.
References All, global_data_all_processes::CP, FORCE_SOFTENING(), global_data_all_processes::G, Cosmology::Hubble, Cosmology::Omega0, and P.
Referenced by grav_short_pair(), grav_short_tree(), and grav_short_tree_old().
 {
     P[i].GravAccel[0] *= All.G;
     P[i].GravAccel[1] *= All.G;
     P[i].GravAccel[2] *= All.G;
     /* calculate the potential */
     /* remove self-potential */
     P[i].Potential += P[i].Mass / (FORCE_SOFTENING(i) / 2.8);
     P[i].Potential -= 2.8372975 * pow(P[i].Mass, 2.0 / 3) *
         pow(All.CP.Omega0 * 3 * All.CP.Hubble * All.CP.Hubble / (8 * M_PI * All.G), 1.0 / 3);
     P[i].Potential *= All.G;
 }
grav_short_reduce()
static void grav_short_reduce (int place, TreeWalkResultGravShort * result, enum TreeWalkReduceMode mode, TreeWalk * tw) static
Definition at line 66 of file gravshort.h.
References TreeWalkResultGravShort::Acc, grav_apply_short_range_window(), TreeWalkResultGravShort::Ninteractions, P, TreeWalkResultGravShort::Potential, and TREEWALK_REDUCE.
Referenced by grav_short_pair(), grav_short_tree(), and grav_short_tree_old().
 {
     int k;
     for(k = 0; k < 3; k++)
         TREEWALK_REDUCE(P[place].GravAccel[k], result->Acc[k]);
     TREEWALK_REDUCE(P[place].GravCost, result->Ninteractions);
     TREEWALK_REDUCE(P[place].Potential, result->Potential);
 }