MP-Gadget: libgadget/hci.h File Reference
hci.h File Reference
Classes
struct HCIManager
struct HCIAction
Typedefs
typedef struct HCIManager HCIManager
typedef struct HCIAction HCIAction
Enumerations
enum HCIActionType {
HCI_NO_ACTION = 0 , HCI_STOP = 1 , HCI_TIMEOUT = 2 , HCI_AUTO_CHECKPOINT = 3 ,
HCI_CHECKPOINT = 4 , HCI_TERMINATE = 5 , HCI_IOCTL = 6
}
Functions
void hci_init (HCIManager *manager, char *prefix, double TimeLimitCPU, double AutoCheckPointTime, int FOFEnabled)
void hci_action_init (HCIAction *action)
int hci_query (HCIManager *manager, HCIAction *action)
void hci_override_now (HCIManager *manager, double now)
Typedef Documentation
HCIAction
typedef struct HCIAction HCIAction
HCIManager
typedef struct HCIManager HCIManager
Enumeration Type Documentation
HCIActionType
enum HCIActionType
Enumerator
HCI_NO_ACTION
HCI_STOP
HCI_TIMEOUT
HCI_AUTO_CHECKPOINT
HCI_CHECKPOINT
HCI_TERMINATE
HCI_IOCTL
Definition at line 20 of file hci.h.
                    {
     HCI_NO_ACTION = 0,
     HCI_STOP = 1,
     HCI_TIMEOUT = 2,
     HCI_AUTO_CHECKPOINT = 3,
     HCI_CHECKPOINT = 4,
     HCI_TERMINATE = 5,
     HCI_IOCTL = 6,
 };
Function Documentation
hci_action_init()
void hci_action_init (HCIAction * action)
Definition at line 38 of file hci.c.
 {
     action->type = HCI_NO_ACTION;
     action->write_snapshot = 0;
     action->write_fof = 0;
 }
References HCI_NO_ACTION, HCIAction::type, HCIAction::write_fof, and HCIAction::write_snapshot.
Referenced by hci_query(), and run().
hci_init()
void hci_init (HCIManager * manager, char * prefix, double TimeLimitCPU, double AutoCheckPointTime, int FOFEnabled)
Definition at line 25 of file hci.c.
 {
     manager->prefix = prefix;
     manager->timer_begin = hci_now(manager);
     manager->timer_query_begin = manager->timer_begin;
     manager->WallClockTimeLimit = WallClockTimeLimit;
     manager->AutoCheckPointTime = AutoCheckPointTime;
     manager->FOFEnabled = FOFEnabled;
     manager->LongestTimeBetweenQueries = 0;
 }
References HCIManager::AutoCheckPointTime, HCIManager::FOFEnabled, hci_now(), HCIManager::LongestTimeBetweenQueries, manager, HCIManager::prefix, prefix, HCIManager::timer_begin, HCIManager::timer_query_begin, and HCIManager::WallClockTimeLimit.
Referenced by run(), test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), and test_hci_timeout().
hci_override_now()
void hci_override_now (HCIManager * manager, double now)
Definition at line 48 of file hci.c.
 {
     manager->_now = now;
     manager->OVERRIDE_NOW = 1;
 }
References HCIManager::_now, manager, and HCIManager::OVERRIDE_NOW.
Referenced by test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), and test_hci_timeout().
hci_query()
int hci_query (HCIManager * manager, HCIAction * action)
Definition at line 152 of file hci.c.
 {
     hci_action_init(action);
     /* measure time since last query */
     hci_update_query_timer(manager);
     /* Check whether we need to interrupt the run */
     char * request;
     /* Will we run out of time by the query ? highest priority.
      */
     if(hci_query_timeout(manager, &request)) {
         message(0, "HCI: Stopping due to TimeLimitCPU, dumping a CheckPoint.\n");
         action->type = HCI_TIMEOUT;
         action->write_snapshot = 1;
         if(manager->FOFEnabled)
             action->write_fof = 1;
         return 1;
     }
     if(hci_query_filesystem(manager, "reconfigure", &request))
     {
         /* FIXME: This is not implemented
          * it shall reread the configuration file and update the parameters of
          * the module listed in the request.
          * see the comment about update_IO_params
          * */
         message(0, "HCI: updating io parameters, this is not supported yet.\n");
         myfree(request);
         return 0;
     }
     if(hci_query_filesystem(manager, "checkpoint", &request))
     {
         message(0, "HCI: human controlled stop with checkpoint at next PM.\n");
         action->type = HCI_CHECKPOINT;
         /* will write checkpoint in this PM timestep */
         action->write_snapshot = 1;
         /* Write fof as well*/
         if(manager->FOFEnabled)
             action->write_fof = 1;
         myfree(request);
         manager->TimeLastCheckPoint = hci_get_elapsed_time(manager);
         return 0;
     }
     /* Is the stop-file present? If yes, interrupt the run with a snapshot. */
     if(hci_query_filesystem(manager, "stop", &request))
     {
         /* will write checkpoint in this PM timestep, then stop */
         action->type = HCI_STOP;
         action->write_snapshot = 1;
         myfree(request);
         return 1;
     }
     /* Is the terminate-file present? If yes, interrupt the run immediately. */
     if(hci_query_filesystem(manager, "terminate", &request))
     {
         message(0, "HCI: human triggered termination.\n");
         /* the caller shall take care of immediate termination.
          * This action is better than KILL as it avoids corrupt/incomplete snapshot files.*/
         action->type = HCI_TERMINATE;
         action->write_snapshot = 0;
         myfree(request);
         return 1;
     }
     /* lower priority */
     if(hci_query_auto_checkpoint(manager, &request))
     {
         message(0, "HCI: Auto checkpoint due to AutoCheckPointTime.\n");
         action->type = HCI_AUTO_CHECKPOINT;
         /* Write when the PM timestep completes*/
         action->write_snapshot = 1;
         if(manager->FOFEnabled)
             action->write_fof = 1;
         manager->TimeLastCheckPoint = hci_get_elapsed_time(manager);
         return 0;
     }
     message(0, "HCI: Nothing happened. \n");
     return 0;
 }
References HCIManager::FOFEnabled, hci_action_init(), HCI_AUTO_CHECKPOINT, HCI_CHECKPOINT, hci_get_elapsed_time(), hci_query_auto_checkpoint(), hci_query_filesystem(), hci_query_timeout(), HCI_STOP, HCI_TERMINATE, HCI_TIMEOUT, hci_update_query_timer(), manager, message(), myfree, HCIManager::TimeLastCheckPoint, HCIAction::type, HCIAction::write_fof, and HCIAction::write_snapshot.
Referenced by run(), test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), and test_hci_timeout().