MP-Gadget: libgadget/lightcone.h File Reference
lightcone.h File Reference
Functions
void lightcone_init (Cosmology *CP, double timeBegin, const double UnitLength_in_cm, const char *OutputDir)
void lightcone_compute (double a, double BoxSize, Cosmology *CP, inttime_t ti_curr, inttime_t ti_next)
Function Documentation
lightcone_compute()
void lightcone_compute (double a, double BoxSize, Cosmology * CP, inttime_t ti_curr, inttime_t ti_next)
Definition at line 177 of file lightcone.c.
 {
     int i;
     lightcone_set_time(a, BoxSize);
     const double ddrift = get_exact_drift_factor(CP, ti_curr, ti_next);
     #pragma omp parallel for
     for(i = 0; i < PartManager->NumPart; i++)
     {
         lightcone_cross(i, ddrift);
     }
 }
References CP, get_exact_drift_factor(), lightcone_cross(), lightcone_set_time(), part_manager_type::NumPart, and PartManager.
Referenced by run().
lightcone_init()
void lightcone_init (Cosmology * CP, double timeBegin, const double UnitLength_in_cm, const char * OutputDir)
Definition at line 91 of file lightcone.c.
 {
     int i;
     dloga = (0.0 - log(timeBegin)) / (NENTRY - 1);
     for(i = 0; i < NENTRY; i ++) {
         lightcone_init_entry(CP, i, UnitLength_in_cm);
     };
     char buf[1024];
     int chunk = 100;
     int ThisTask;
     MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
     sprintf(buf, "%s/lightcone/", OutputDir);
     mkdir(buf, 02755);
     sprintf(buf, "%s/lightcone/%03d/", OutputDir, (int)(ThisTask / chunk));
     mkdir(buf, 02755);
     sprintf(buf, "%s/lightcone/%03d/lightcone-%05d.raw", OutputDir, (int)(ThisTask / chunk), ThisTask);
     fd_lightcone = fopen(buf, "a+");
     if(fd_lightcone == NULL) {
         endrun(1, "failed to open %s\n", buf);
     }
     HorizonDistanceRef = lightcone_get_horizon(1 / (1 + ReferenceRedshift));
     printf("lightcone reference redshift = %g distance = %g\n",
             ReferenceRedshift, HorizonDistanceRef);
 }
References CP, dloga, endrun(), fd_lightcone, HorizonDistanceRef, lightcone_get_horizon(), lightcone_init_entry(), NENTRY, ReferenceRedshift, ThisTask, and UnitLength_in_cm.
Referenced by begrun().