MP-Gadget: longrange.c File Reference
longrange.c File Reference
driver routines for computation of long-range gravitational PM force
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "allvars.h"
Macros
#define NTAB 1000
Functions
void gravpm_init_periodic ()
static void fill_ntab ()
void long_range_init (void)
int grav_apply_short_range_window (double r, double *fac, double *pot)
Variables
static float shortrange_table [NTAB]
static float shortrange_table_potential [NTAB]
static float shortrange_table_tidal [NTAB]
Detailed Description
driver routines for computation of long-range gravitational PM force
Definition in file longrange.c.
Macro Definition Documentation
NTAB
#define NTAB 1000
length of lock-up table for short-range force kernel in TreePM algorithm
Definition at line 28 of file longrange.c.
Referenced by fill_ntab(), and grav_apply_short_range_window().
Function Documentation
fill_ntab()
static void fill_ntab () static
Definition at line 33 of file longrange.c.
References NTAB, shortrange_table, shortrange_table_potential, and shortrange_table_tidal.
Referenced by long_range_init().
 {
     int i;
     for(i = 0; i < NTAB; i++)
     {
         double u = 3.0 / NTAB * (i + 0.5);
         shortrange_table[i] = erfc(u) + 2.0 * u / sqrt(M_PI) * exp(-u * u);
         shortrange_table_potential[i] = erfc(u);
         shortrange_table_tidal[i] = 4.0 * u * u * u / sqrt(M_PI) * exp(-u * u);
     }
 }
grav_apply_short_range_window()
int grav_apply_short_range_window (double r, double * fac, double * pot)
Definition at line 47 of file longrange.c.
References All, global_data_all_processes::Asmth, global_data_all_processes::BoxSize, global_data_all_processes::Nmesh, NTAB, shortrange_table, and shortrange_table_potential.
Referenced by force_treeev_shortrange(), grav_short_pair_ngbiter(), and grav_short_reduce().
 {
     const double asmth = All.Asmth * All.BoxSize / All.Nmesh;
     const double asmthfac = 0.5 / asmth * (NTAB / 3.0);
     int tabindex = (int) (asmthfac * r);
     if(tabindex < NTAB)
     {
         *fac *= shortrange_table[tabindex];
         *pot *= shortrange_table_potential[tabindex];
         return 0;
     } else {
         return 1;
     }
 }
gravpm_init_periodic()
void gravpm_init_periodic ()
Definition at line 55 of file gravpm.c.
References All, global_data_all_processes::BoxSize, compute_neutrino_power(), global_data_all_processes::CP, delta_tot_table, PetaPMGlobalFunctions::global_analysis, PetaPMGlobalFunctions::global_readout, global_data_all_processes::MassiveNuLinRespOn, measure_power_spectrum(), global_data_all_processes::Nmesh, global_data_all_processes::NumThreads, Cosmology::Omega0, Cosmology::ONu, petapm_init(), PowerSpectrum, powerspectrum_alloc(), ThisTask, global_data_all_processes::TimeIC, global_data_all_processes::TimeMax, and global_data_all_processes::UnitTime_in_s.
Referenced by long_range_init().
{
     petapm_init(All.BoxSize, All.Nmesh, All.NumThreads);
     powerspectrum_alloc(&PowerSpectrum, All.Nmesh, All.NumThreads);
     /*Initialise the kspace neutrino code if it is enabled.
      * Mpc units are used to match power spectrum code.*/
     if(All.MassiveNuLinRespOn) {
         /*Set the private copy of the task in delta_tot_table*/
         delta_tot_table.ThisTask = ThisTask;
         allocate_delta_tot_table(&delta_tot_table, All.Nmesh, All.TimeIC, All.TimeMax, All.CP.Omega0, &All.CP.ONu, All.UnitTime_in_s, 3.085678e24, 0);
         global_functions.global_readout = measure_power_spectrum;
         global_functions.global_analysis = compute_neutrino_power;
     }
 }
long_range_init()
void long_range_init (void)
Driver routine to call initializiation of periodic or/and non-periodic FFT routines.
Definition at line 21 of file longrange.c.
References fill_ntab(), and gravpm_init_periodic().
Referenced by begrun().
 {
     fill_ntab();
     gravpm_init_periodic();
 }
Variable Documentation
shortrange_table
float shortrange_table[NTAB] static
variables for short-range lookup table
Definition at line 30 of file longrange.c.
Referenced by fill_ntab(), and grav_apply_short_range_window().
shortrange_table_potential
float shortrange_table_potential[NTAB] static
Definition at line 30 of file longrange.c.
Referenced by fill_ntab(), and grav_apply_short_range_window().
shortrange_table_tidal
float shortrange_table_tidal[NTAB] static
Definition at line 30 of file longrange.c.
Referenced by fill_ntab().