# vim: set ft=make:
DESTDIR ?= .

TARGETS = MP-Gadget GENIC/MP-GenIC

CFLAGS = -I. -I$(DESTDIR) $(OPTIONS) $(GSL_INCL) $(HDF5_INCL) -I$(PWD)/depends/include -DH5_USE_16_API

BUNDLEDLIBS = -lmpsort-mpi -lradixsort -lbigfile-mpi -lbigfile -lpfft -lfftw3_mpi -lfftw3_omp -lfftw3
LIBS   = -lm $(HDF_LIBS) $(GSL_LIBS) -L$(PWD)/depends/lib $(BUNDLEDLIBS)

OPTIONS = $(OPTIMIZE) $(OPT)

OBJECTS  =  \
	 gdbtools.o \
	 fof.o fofpetaio.o petaio.o \
	 param.o \
	 domain.o allvars.o main.o \
	 blackhole.o \
	 run.o predict.o begrun.o endrun.o global.o \
	 timestep.o init.o io.o sfr_eff.o \
	 accel.o \
	 cooling.o ngb.o openmpsort.o \
	 system.o allocate.o density.o sizelimited_sendrecv.o  \
	 evaluator.o cosmology.o \
	 gravtree.o hydra.o  driftfac.o \
	 gravpm.o \
	 forcetree.o peano.o \
	 petapm.o longrange.o mymalloc.o \
	 densitykernel.o interp.o lightcone.o walltime.o \
	 cppexample.o

ICOBJECTS   = GENIC/main.o GENIC/power.o GENIC/allvars.o GENIC/read_param.o \
		 petapm.o \
		 openmpsort.o \
		 GENIC/zeldovich.o \
		GENIC/save2.o  \
		walltime.o

INCL   = allvars.h proto.h forcetree.h cooling.h domain.h evaluator.h \
	 fof.h cosmology.h \
	 petaio.h \
	 Makefile 

EXEC = $(TARGETS:%=$(DESTDIR)/%)
OBJS = $(OBJECTS:%=$(DESTDIR)/%)
ICOBJS = $(ICOBJECTS:%=$(DESTDIR)/%)

all: depends $(EXEC)

.PHONY: depends

depends:
	cd depends; make

$(DESTDIR)/GENIC:
	mkdir -p $@

$(DESTDIR)/MP-Gadget: $(OBJS)
	$(CC) $(OPTIMIZE) $(OBJS) $(LIBS) -o $@

$(DESTDIR)/GENIC/MP-GenIC: $(DESTDIR)/GENIC $(ICOBJS)
	$(CC) $(OPTIMIZE) $(ICOBJS) $(LIBS) -o $@

$(DESTDIR)/config.h: Makefile
	mkdir -p `dirname $@`
	echo 'const char * COMPILETIMESETTINGS = "" ' > $@
	echo "\"$(OPTIMIZE)\n\"" >> $@
	for i in $(OPT); do echo "\"$$i\n\""; done >> $@
	echo ';' >> $@


$(OBJS): $(INCL) $(DESTDIR)/config.h 
$(ICOBJS): $(INCL) $(DESTDIR)/config.h 

$(DESTDIR)/%.o: %.c $(INCL)
	@echo Compiling $<; $(CC) -c -o $@ $(CFLAGS) $<

$(DESTDIR)/%.o: %.cpp $(INCL)
	@echo Compiling $<; $(CXX) -c -o $@ $(CFLAGS) $<

clean:
	rm -f $(OBJS) $(EXEC) $(ICOBJS)
