##
# Run all the tests.
#
#  make test
#
# run a selected suite of tests
#
#  make test SUITE=tests/test_cosmology
#
# To debug a test
#
#  make tests/test_cosmology
#  gdb tests/test_cosmology
#
##
TESTED = \
	hci \
	slotsmanager \
	interp \
	powerspectrum \
	cosmology \
	forcetree \
	timefac \
	timebinmgr \
	memory \
	openmpsort \
	genic-power \
	exchange

MPI_TESTED = exchange

TESTBIN = $(TESTED:%=tests/test_%) $(MPI_TESTED:%=tests/test_%)
SUITE?= $(TESTED:%=tests/test_%)
MPISUITE = $(MPI_TESTED:%=tests/test_%)

.PHONY: test run-tests build-tests


build-tests: $(TESTBIN)

test : build-tests
	trap 'err=1' ERR; for tt in $(SUITE) ; do \
		if [[ "$(MPISUITE)" =~ .*$$tt.* ]]; then \
			mpirun -np 4 $$tt ;  \
		else \
			$$tt ; \
		fi ;  \
	done; exit $$err

clean-tests:
	rm -f $(TESTBIN)

# this empty rule is important for tab-completion
$(TESTBIN):

tests/test_%: tests/test_%.c tests/stub.c $(DESTDIR)/%.o $(DESTDIR)/libgadget-utils.a tests/cmocka.c
	$(MPICC) $(CFLAGS) -Itests/ $^ $(LIBS) -o $@

tests/test_genic-%: tests/test_genic-%.c tests/stub.c $(DESTDIR)/genic/%.o $(DESTDIR)/libgadget-utils.a tests/cmocka.c
	$(MPICC) $(CFLAGS) -Itests/ $^ $(LIBS) -o $@
