# vim: set ft=make:
#
AR ?= ar
MPICC ?= mpic++
LOW_PRECISION ?= double

OPTIMIZE ?= -O2 -g -fopenmp -Wall
GSL_INCL ?= $(shell pkg-config --cflags gsl)
GSL_LIBS ?= $(shell pkg-config --libs gsl)
#BOOST_INCL ?= $(shell pkg-config --cflags boost)
#BOOST_LIBS ?= $(shell pkg-config --libs boost)

ifneq ($(findstring -DUSE_CFITSIO, $(OPT)),)
    # If found, set FITSIO_INCL with the cfitsio flags
    FITSIO_INCL ?= $(shell pkg-config --cflags cfitsio)
    FITSIO_LIBS ?= $(shell pkg-config --libs cfitsio)
endif

ifneq ($(findstring -DUSE_CUDA, $(OPT)),)
    CUDA_INCL ?= 
    CUDA_LIBS ?= -lcudart
    CUFFTMP_INCL ?= 
    CUFFTMP_LIBS ?= -lcufftMp
    NVSHMEM_INCL ?= 
    NVSHMEM_LIBS ?= -lnvshmem_host
    NVCC ?= nvcc
    NVOPTIMIZE ?= -O3
endif

OPTIONS = $(OPTIMIZE) $(OPT)
GADGET_TESTDATA_ROOT = $(CURDIR)/../

CFLAGS = $(OPTIONS) $(GSL_INCL) $(BOOST_INCL) $(FITSIO_INCL) $(CUDA_INCL) $(CUFFTMP_INCL) $(NVSHMEM_INCL)
CFLAGS += -I../depends/include
CFLAGS += -I../
CFLAGS += "-DLOW_PRECISION=$(LOW_PRECISION)"
#For tests
TCFLAGS = $(CFLAGS) -DGADGET_TESTDATA_ROOT=\"$(GADGET_TESTDATA_ROOT)\"

BUNDLEDLIBS = -lbigfile-mpi -lbigfile
LIBS  = -lm  $(BOOST_LIBS) $(GSL_LIBS) $(FITSIO_LIBS) $(CUDA_LIBS) $(CUFFTMP_LIBS) $(NVSHMEM_LIBS)
LIBS += -L../depends/lib $(BUNDLEDLIBS)
V ?= 0

.objs/%.o: %.c Makefile $(CONFIG)
	@cmd="$(MPICC) -MMD -c -o $@ $(CFLAGS) $<"; \
	if test "x$(V)" = "x1" ; then echo $$cmd; fi; \
	mkdir -p `dirname $@`; \
	echo Compiling $<; $$cmd

# Rule to compile .cu files (using nvcc)
.objs/%.o: %.cu
	$(NVCC) $(NVOPTIMIZE) -c $< -o $@
