#######################################################################
#  Look at end of file for a brief guide to the compile-time options. #
#######################################################################
SYSTYPE=Local
VPATH=./

#--------------------------------------- Basic operation mode of code
OPT += -DDENSITY_INDEPENDENT_SPH
OPT	+=  -DPERIODIC
#OPT += -DLIGHTCONE                       # write a lightcone on the fly; in development
OPT += -DPETAPM  # new peta scale PFFT based PM
OPT += -DPETAPM_ORDER=1  # order of finite differentiation kernel 1 is same as gadget

#--------------------------------------- TreePM Options
#OPT	+=  -DGRIDBOOST=2
#OPT	+=  -DASMTH=1.25
#OPT	+=  -DRCUT=4.5

#OPT += VALGRIND  # allow debugging with valgrind, disable the GADGET memory allocator.

# flags shall that always be there they need to be cleaned up
OPT += -DOPENMP_USE_SPINLOCK
OPT	+=  -DUNEQUALSOFTENINGS
OPT	+=  -DMOREPARAMS
OPT	+=  -DALLOWEXTRAPARAMS
OPT	+=  -DNOSTOP_WHEN_BELOW_MINTIMESTEP
OPT += -DSPH_GRAD_RHO  # calculate grad of rho in SPH, required for Krumholtz & Gnedin H2 SFR
OPT	+=  -DBH_REPOSITION_ON_POTMIN    # repositions hole on potential minimum (required )

#--------------------------------------- Multi-Domain and Top-Level Tree options
OPT	+=  -DMULTIPLEDOMAINS=32
OPT	+=  -DTOPNODEFACTOR=5.0


#--------------------------------------- Things that are always recommended
OPT	+=  -DPEANOHILBERT
OPT	+=  -DWALLCLOCK
OPT	+=  -DMYSORT
OPT	+=  -DDONOTUSENODELIST                # do not use node list in hydro why?
#OPT	+=  -DCPUSPEEDADJUSTMENT
#OPT	+=  -DHYDRO_COST_FACTOR=1000
#OPT	+=  -DAUTO_SWAP_ENDIAN_READIC        # Enables automatic ENDIAN swapping for reading ICs
#OPT	+=  -DPERMUTATAION_OPTIMIZATION

#---------------------------------------- On the fly FOF groupfinder 
OPT	+=  -DFOF                                # enable FoF output
OPT	+=  -DFOF_PRIMARY_LINK_TYPES=2           # 2^type for the primary dark matter type
OPT	+=  -DFOF_SECONDARY_LINK_TYPES=1+16+32	 # 2^type for the types linked to nearest primaries
#OPT    +=  -DDENSITY_SPLIT_BY_TYPE=1+2+16+32    # 2^type for whch the densities should be calculated seperately  
OPT 	+=  -DFOF_GROUP_MIN_LEN=32               # default is 32
#OPT	+=  -DSO_VEL_DISPERSIONS                 # computes velocity dispersions for as part of FOF SO-properties

#--------------------------------------- SFR/feedback model
# most of the sfr modes are controled in paramfile (which needs a overhaul too!)
OPT	+=  -DCOOLING
OPT	+=  -DSFR
#OPT	+=  -DSOFTEREQS
OPT	+=  -DMETALS
OPT	+=  -DSTELLARAGE
OPT	+=  -DWINDS
#OPT	+=  -DQUICK_LYALPHA
#OPT	+=  -DISOTROPICWINDS


#-------------------------------------- AGN stuff
OPT	+=  -DBLACK_HOLES             # enables Black-Holes (master switch)
OPT	+=  -DBH_ACCRETION # Bondi-Hoyle style accretion model
OPT	+=  -DBH_ENFORCE_EDDINGTON_LIMIT # put a hard limit on the maximum accretion rate
OPT	+=  -DBH_THERMALFEEDBACK      # couple a fraction of the BH luminosity into surrounding gas
OPT	+=  -DBH_SWALLOWGAS              # Enables stochastic accretion of gas particles consistent with growth rate of hole
OPT	+=  -DBH_SWALLOWBH # Enables blackhole mergers.
OPT	+=  -DBH_COUNTPROGS	      # carries a counter for each BH that gives the total number of seeds that merged into it
OPT	+=  -DBH_USE_GASVEL_IN_BONDI  # only when this is enabled, the surrounding gas velocity is used in addition to the sounds speed in the Bondi rate 


#-------------------------------------- Viscous gas treatment 
#OPT	+=  -DNAVIERSTOKES            # Braginskii-Spitzer parametrization of the shear viscosity: mu = f x T^{5/2}
#OPT	+=  -DNAVIERSTOKES_CONSTANT   # Shear viscosity set constant for all gas particles
#OPT	+=  -DNAVIERSTOKES_BULK       # Bulk viscosity set constant for all gas particles. To run with bulk visocity only one has to set shear viscosity to zero in the parameterfile.
#OPT	+=  -DVISCOSITY_SATURATION    # Both shear and bulk viscosities are saturated, so that unphysical accelerations and entropy increases are avoided. Relevant for the cosmological simulations.
#OPT	+=  -DNS_TIMESTEP             # Enables timestep criterion based on entropy increase due to internal friction forces
#OPT	+=  -DOUTPUTSTRESS            # Outputs diagonal and offdiagonal components of viscous shear stress tensor
#OPT	+=  -DOUTPUTBULKSTRESS        # Outputs viscous bulk stress tensor
#OPT	+=  -DOUTPUTSHEARCOEFF        # Outputs variable shear viscosity coefficient in internal code units


#-------------------------------------------- Things for special behaviour
OPT	+=  -DINCLUDE_RADIATION		# Add radiation density to backround evolution. Only affects the Hubble flow.
#OPT	+=  -DTRADITIONAL_SPH_FORMULATION
OPT	+=  -DNOTEST_FOR_IDUNIQUENESS
#OPT	+=  -DSNIA_HEATING
#OPT    +=  -DRADIAL_TREE                   #make tree forces exact radial (only implemented in tree, not TreePM)
#OPT	+=  -DFIXEDTIMEINFIRSTPHASE=1000.0
OPT	+=  -DNO_ISEND_IRECV_IN_DOMAIN     #sparse MPI_Alltoallv do not use ISEND IRECV
OPT	+=  -DFIX_PATHSCALE_MPI_STATUS_IGNORE_BUG
#OPT	+=  -DMPISENDRECV_SIZELIMIT=100
#OPT	+=  -DMPISENDRECV_CHECKSUM
#OPT	+=  -DNOGRAVITY
#OPT	+=  -DNOACCEL
#OPT	+=  -DNOISMPRESSURE
#OPT	+=  -DNOVISCOSITYLIMITER
#OPT	+=  -DNOTREERND
#OPT	+=  -DNO_TREEDATA_IN_RESTART
#OPT	+=  -DISOTHERM=200                  # adds potential of an isothermal sphere
#OPT	+=  -DCOMPUTE_POTENTIAL_ENERGY
#OPT	+=  -DASSIGN_NEW_IDS
OPT	+=  -DINHOMOG_GASDISTR_HINT         # if the gas is distributed very different from collisionless particles, this can helps to avoid problems in the domain decomposition -- increase All.MaxPartSph
#OPT	+=  -DLONG_X=140
#OPT	+=  -DLONG_Y=1
#OPT	+=  -DLONG_Z=1
#OPT	+=  -DTWODIMS
#OPT	+=  -DONEDIM
#OPT	+=  -DSPH_BND_PARTICLES
#OPT	+=  -DNEW_RATES                     # switches in updated cooling rates from Naoki
#OPT	+=  -DRADIATIVE_RATES               # used in non-equilibrium chemistry model
#OPT	+=  -DREAD_HSML                     # reads hsml from IC file
#OPT   	+=  -DADAPTIVE_GRAVSOFT_FORGAS      # allows variable softening length for gas particles (requires UNEQUALSOFTENINGLENGTH)
#OPT	+=  -DADAPTIVE_GRAVSOFT_FORGAS_HSML # this sets the gravitational softening for SPH particles equal to the SPH smoothing (requires ADAPTIVE_GRAVSOFT_FORGAS)
#OPT	+=  -DGENERATE_GAS_IN_ICS
#OPT	+=  -DSPLIT_PARTICLE_TYPE=4+8
#OPT    +=  -DNEUTRINOS                     # Option for special integration of light neutrino species 
#OPT    +=  -DOMIT_NEUTRINOS_IN_SNAPS
#OPT	+=  -DSTART_WITH_EXTRA_NGBDEV        # Uses special MaxNumNgbDeviation for starting
#OPT	+=  -DVOLUME_CORRECTION=1.75
#OPT	+=  -DISOTHERM_EQS                  # isothermal equation of state
#OPT	+=  -DNO_UTHERM_IN_IC_FILE
#OPT	+=  -DSPECIAL_GAS_TREATMENT_IN_HIGHRESREGION

#--------------------------------------- Time integration options
#OPT	+=  -DALTERNATIVE_VISCOUS_TIMESTEP
#OPT	+=  -DNOWINDTIMESTEPPING            # Disable wind reducing timestep (not recommended)
#OPT	+=  -DNOPMSTEPADJUSTMENT
#OPT	+=  -DFORCE_EQUAL_TIMESTEPS

#--------------------------------------- Options for simplified halo formation process in an Einstei-De Sitter (Newtonian) Universe
#OPT	+= -DSHELL_CODE=200              #activate shell code, the value corresponds to the smoothing length for dM/dr calclulation
                                         #the core softening length equals the halo particle softening length from parameterfile 
                                         #this option replaces the GADGET Poisson solver by a simple 1D integration  
#OPT	+= -DSIM_ADAPTIVE_SOFT=0.667     #set softening for shell code/Tree as fraction of current turnaround radius -> softened SIM
                                         #the halo softening length value is used as the fraction value, e.g. 0.1 -> 10% of turnaround
                                         #the epsilon value of the density perturbation needs to be specified for turnaround radius calc
#OPT	+= -DPHYS_COMOVING_SOFT          #set softening for Tree as fixed fraction in comoving coordinates
#OPT	+= -DREINIT_AT_TURNAROUND=0.667  #reinit phase-space distortion tensor when particles crosses the turnaround radius. 
                                         #the epsilon value of the density perturbation needs to be specified to calculate
					 #correct initial sheet orientation and initial stream density
#OPT    += -DREINIT_AT_TURNAROUND_CMS    #calculate centre of mass within REINIT_AT_TURNAROUND_CMS fraction of turnaround radius
#OPT	+= -DANALYTIC_TURNAROUND         #use analytic turnaround radius instead of the numerical one


#--------------------------------------- Real Cosmic Rays
#OPT    +=  -DJD_VTURB
#OPT    +=  -DBP_REAL_CRs=10             # Number of energy bins for CRs

#--------------------------------------- SPH viscosity options
#OPT	+=  -DCONVENTIONAL_VISCOSITY     # enables the old viscosity
#OPT	+=  -DTIME_DEP_ART_VISC          # Enables time dependend viscosity
#OPT	+=  -DNO_SHEAR_VISCOSITY_LIMITER # Turns of the shear viscosity supression
#OPT	+=  -DHIGH_ART_VISC_START        # Start with high rather than low viscosity
#OPT	+=  -DALTVISCOSITY               # enables alternative viscosity based on div(v)


#....................................... Induction equation stuff
#OPT	+=  -DDIVBINDUCTION              # Turns on divB term in induction eq. (REMOVED)
#OPT	+=  -DCORRECTDB                  # Turns on dW/dh correction in induction eq.

#....................................... Force equation stuff
#OPT	+=  -DMU0_UNITY                  # Sets \mu_0 to unity
#OPT	+=  -DARTBPRES                   # Anti clumping term ala Morris (REMOVED)
#OPT	+=  -DDIVBFORCE                  # Subtract div(B) force from M-tensor
#OPT	+=  -DCORRECTBFRC                # Turns on dW/dh correction for B force 

#....................................... Smoothing Options
#OPT	+=  -DBSMOOTH                    # Turns on B field smoothing

#....................................... Healpix stuff
#OPT    +=  -DHEALPIX=1.05		 # Generates a healpix map, to retain particles in the 
					 # HiRes region. It should be a tolerance value.
#OPT    +=  -DHEALPIX_INNERBOUND=2
#OPT    +=  -DHEALPIX_OUTERBOUND=4

#--------------------------------------- Glass making/ 2nd-order initial conditions
#OPT	+=  -DMAKEGLASS

#--------------------------------------- Raditive Transfer
#OPT	+=  -DRADTRANSFER
#OPT	+=  -DCG
#OPT	+=  -DRADTRANSFER_FLUXLIMITER
#OPT	+=  -DRADTRANSFER_MODIFY_EDDINGTON_TENSOR
#OPT	+=  -DRT_COOLING_PHOTOHEATING
#OPT	+=  -DRT_RAD_PRESSURE
#OPT    +=  -DEDDINGTON_TENSOR_GAS
#OPT	+=  -DEDDINGTON_TENSOR_STARS
#OPT	+=  -DEDDINGTON_TENSOR_SFR
#OPT    +=  -DEDDINGTON_TENSOR_BH
#OPT	+=  -DRT_OUTPUT_ET

#--------------------------------------- degenerate equation of state
#OPT	+=  -DEOS_DEGENERATE
#OPT	+=  -DEOS_COULOMB_CORRECTIONS
#OPT	+=  -DEOS_NSPECIES=3
#OPT	+=  -DWAKEUP=4.1           /* allows 2 timestep bins within kernel */
#OPT	+=  -DRELAXOBJECT

#--------------------------------------- nuclear network
#OPT +=  -DNUCLEAR_NETWORK
#OPT +=  -DFIXED_TEMPERATURE
#OPT +=  -DNEGLECT_DTDY_TERMS
#OPT +=  -DNETWORK_OUTPUT
#OPT +=  -DNETWORK_OUTPUT_BINARY


#--------------------------------------- Select target Computer
include Makefile.$(SYSTYPE)

include $(VPATH)/Makefile.deps


###############################################################################
#
# at compile-time. From the list below, please activate/deactivate the
# options that apply to your run. If you modify any of these options,
# make sure that you recompile the whole code by typing "make clean;
# make".
#
# Main code options:
#
#     These affect the physical model that is simulated.
#
#     - PERIODIC:   Set this if you want to have periodic boundary conditions.
#     - COOLING:    This enables radiative cooling and heating. It also enables
#                   an external UV background which is read from a file.
#     - SFR:        This enables star formation using an effective multiphase
#                   models. This option requires cooling.
#     - METALS:     This model activates the tracking of enrichment in gas and
#                   stars. Note that metal-line cooling is not included yet.
#     - STELLARAGE: This stores the formation redshift of each star particle.
#     - WINDS:      This activates galactic winds. Requires star formation.
#     - ISOTROPICWINDS: This makes the wind isotropic. If not set the wind is
#                       spawned in an axial way. Requires winds to be activated.
#     - NOGRVITY:  This switches off gravity. Makes only sense for pure
#                   SPH simulations in non-expanding space.
#
# Options for SPH:
#
#     - NOFIXEDMASSINKERNEL:  If set, the number of SPH particles in the kernel
#                             is kept constant instead of the mass.
#     - NOGRADHSML:           If actived, an equation of motion without grad(h)
#                             terms is used.
#            Note: To have the default "entropy"-formulation of SPH (Springel &
#                  Hernquist), the switches NOFIXEDMASSINKERNEL and NOGRADHSML
#                  should *not* be set.
#     - NOVISCOSITYLIMITER:   If this is set, there is no explicit upper limit
#                             on the viscosity that tries to prevent particle
#                             'reflection' in case of poor timestepping.
#
# Numerical options:
#
#     - PMGRID:     This enables the TreePM method, i.e. the long-range force
#                   is computed with a PM-algoritthm, and the short range force
#                   with the tree. The parameter has to be set to the size of the
#                   mesh that should be used, (e.g. 64, 96, 128, etc). The mesh
#                   dimensions need not necessarily be a power of two.
#                   Note: If the simulation is not in a periodic box, then a FFT
#                   method for vacuum boundaries is employed, using a mesh with
#                   dimension twice that specified by PMGRID.
#     - PLACEHIGHRESREGION: If this option is set (will only work together
#                   with PMGRID), then the long range force is computed in two
#                   stages: One Fourier-grid is used to cover the whole simulation
#                   volume, allowing the computation of the large-scale force.
#                   A second Fourier mesh is placed on the region occupied by
#                   "high-resolution" particles, allowing the computation of an
#                   intermediate scale force. Finally, the force on very small
#                   scales is supplemented by the tree. This procedure can be useful
#                   for "zoom-simulations", where the majority of particles (the
#                   high-res particles) are occupying only a small fraction of the
#                   volume. To activate this option, the parameter needs to be set
#                   to an integer that encodes the particle types that represent the
#                   high-res particles in the form of a bit mask. For example, if
#                   types 0, 1, and 4 form the high-res particles, set the parameter
#                   to PLACEHIGHRESREGION=1+2+16. The spatial region covered by the
#                   high-res grid is determined automatically from the initial
#                   conditions. Note: If a periodic box is used, the high-res zone
#                   may not intersect the box boundaries.
#     - ENLARGEREGION: The spatial region covered by the high-res zone has a fixed
#                   size during the simulation, which initially is set to the
#                   smallest region that encompasses all high-res particles. Normally, the
#                   simulation will be interrupted, if high-res particles leave this
#                   region in the course of the run. However, by setting this parameter
#                   to a value larger than one, the high-res region can be expanded.
#                   For example, setting it to 1.4 will enlarge its side-length by
#                   40% (it remains centered on the high-res particles). Hence, with
#                   such a setting, the high-res region may expand or move by a
#                   limited amount. If in addition SYNCHRONIZATION is activated, then
#                   the code will be able to continue even if high-res particles
#                   leave the initial high-res grid. In this case, the code will
#                   update the size and position of the grid that is placed onto
#                   the high-resolution region automatically. To prevent that this
#                   potentially happens every single PM step, one should nevertheless
#                   assign a value slightly larger than 1 to ENLARGEREGION.
#     - DOUBLEPRECISION: This makes the code store and compute internal
#                        particle data in double precision. Note that output
#                        files are nevertheless written by converting to single
#                        precision.
#     - NOTREERND:       If this is not set, the tree construction will succeed
#                        even when there are a few particles at identical
#                        locations. This is done by `rerouting' particles once
#                        the node-size has fallen below 1.0e-3 of the softening
#                        length. When this option is activated, this will be
#                        surpressed and the tree construction will always fail
#                        if there are particles at extremely close coordinates.
#     - NOSTOP_WHEN_BELOW_MINTIMESTEP: If this is activated, the code will not
#                        terminate when the timestep falls below the value of
#                        MinSizeTimestep specified in the parameterfile. This
#                        is useful for runs where one wants to enforce a
#                        constant timestep for all particles. This can be done
#                        by activating this option, and by setting Min- and
#                        MaxSizeTimestep to an equal value.
#     - PSEUDOSYMMETRIC: When this option is set, the code will try to "anticipate"
#                        timestep changes by extrapolating the change of the
#                        acceleration into the future. This in general improves the
#                        long-term integration behaviour of periodic orbits.
#     - SYNCHRONIZATION: When this is set, particles may only increase their
#                        timestep if the new timestep will put them into
#                        synchronization with the higher time level. This typically
#                        means that only on half of the timesteps of a particle
#                        an increase of the step may occur.
#     - NOPMSTEPADJUSTMENT: When this is set, the long-range timestep for the
#                        PM force computation is always determined by MaxSizeTimeStep.
#                        Otherwise, it is set to the minimum of MaxSizeTimeStep and
#                        the timestep obtained for the maximum long-range force with
#                        an effective softening scale equal to the PM smoothing-scale.
# - LONG_X/Y/Z:
#     These options can be used together with PERIODIC and NOGRAVITY only.
#     When set, the options define numerical factors that can be used to
#     distorts the periodic simulation cube into a parallelepiped of
#     arbitrary aspect ratio. This can be useful for idealized SPH tests.
#
# - TWODIMS:
#     This effectively switches of one dimension in SPH, i.e. the code
#     follows only 2d hydrodynamics in the xy-, yz-, or xz-plane. This
#     only works with NOGRAVITY, and if all coordinates of the third
#     axis are exactly equal. Can be useful for idealized SPH tests.
#
# - SPH_BND_PARTICLES:
#     If this is set, particles with a particle-ID equal to zero do not
#     receive any SPH acceleration. This can be useful for idealized
#     SPH tests, where these particles represent fixed "walls".
#
#
# Architecture options:
#
#     - T3E:       The code assumes that sizeof(int)=4 holds. A few machines
#                  (like Cray T3E) have sizeof(int)=8. In this case, set the
#                  T3E flag.
#
# Input options:
#
#     - MOREPARAMS:  Activate this to allow a set of additional parameters in
#                    the parameterfile which control the star formation and
#                    feedback sector. This option must be activated when star
#                    formation is switched on.
#
# Output options:
#
#     - OUTPUTPOTENTIAL: This will force the code to compute gravitational
#                        potentials for all particles each time a snapshot file
#                        is generated. This values are then included in the
#                        snapshot file. Note that the computation of the
#                        values of the potential costs additional time.
#     - OUTPUTACCELERATION: This will include the physical acceleration of
#                        each particle in snapshot files.
#     - OUTPUTCHANGEOFENTROPY: This will include the rate of change of entropy
#                        of gas particles in snapshot files.
#     - OUTPUTTIMESTEP:  This will include an output of the timesteps actually
#                        taken by each particle.
#
# Miscellaneous options:
#
#     - PEANOHILBERT:    This is a tuning option. When set, the code will bring
#                        the particles after each domain decomposition into
#                        Peano-Hilbert order. This improves cache utilization
#                        and performance.
#     - WALLCLOCK:       If set, a wallclock timer is used by the code to
#                        measure internal time consumption (see cpu-log file).
#                        Otherwise a timer that measures consumed processor
#                        ticks is used.
#
# Debugging/testing options:
#
#     - FORCETEST:       This can be set to check the force accuracy of the
#                        code. The option needs to be set to a number between
#                        0 and 1 (e.g. 0.01), which is taken to specify a
#                        random fraction of particles for which at each
#                        timestep forces by direct summation are computed. The
#                        normal tree-forces and the "correct" direct summation
#                        forces are collected in a file. Note that the
#                        simulation itself is unaffected by this option, but it
#                        will of course run much(!) slower
#                        if FORCETEST*NumPart*NumPart >> NumPart. Note: Particle
#                        IDs must be set to numbers >=1 for this to work.
#
###############################################################################


#     - QUICK_LYALPHA:   This only works for cosmological simulations in periodic boxes
#                        with COOLING & SFR. (WINDS, METALS should be deselected).
#                        It will simply convert all gas particles above overdensity
#                        CritPhysOverdensity and with Temperature below 10^5 K to stars.
#                        This should still leave the Ly-Alpha forest largely unaffected,
#                        but should be faster. It is recommended to set GENERATIONS equal
#                        to 1 for maximum speed-up.
#
#     - TIDALTENSOR:     Calculates the tidal tensor for each particle. 

##################################################################################
#
#  Options for RT:
#
#  - RADTRANSFER        main switch; RT equation solved using the Jacobi iterative method
#
#  - CG                 RT equation solved with the Conjugate Gradient iterative method
#
#  - RADTRANSFER_FLUXLIMITER	intorduces a flux limiter, so that the Ifront speed does not exceed c
#
#  - RADTRANSFER_MODIFY_EDDINGTON_TENSOR	modifies the Eddingto tensor to the fully anisotropic version
#
#  - RT_PHOTOHEATING	includes photoheating
#
#  - RT_COOLING		includes cooling prcesses (only for tests)
#
#  - EDDINGTON_TENSOR_STARS	includes stars, but not sfr partices
#
#  - RT_COLLISIONAL_IONIZATION	includes collisional ionization
#
####################################################################################                 
#
#  Overview of options added for fine-grained phase-space analysis: (Mark)
#
#  * Static Logarithmic Potential with Core:
#   - STATICLP
#   - LP_V02
#   - LP_RC2
#   - LP_Q2
#   - LP_P2=1.0
#
#  * Static "Sikivie 1" potential for inner caustic study  (see Natarajan&Sikivie,2006)
#   - STATICSM
#   - SM_V02=100.0
#   - SM_a=0.285 
#
#  * Options for simplified halo formation process and related things
#   - SHELL_CODE=200 
#   - SIM_ADAPTIVE_SOFT     
#   - REINIT_AT_TURNAROUND=0.667  
#   - ANALYTIC_TURNAROUND
#   - NO_CENTER_ANNIHILATION    
#
#  * Things for special behaviour
#   - RADIAL_TREE
#
#  * Fine-grained phase space structure analysis 
#   - DISTORTIONTENSORPS        
#   - OUTPUT_DISTORTIONTENSORPS 
#   - OUTPUT_TIDALTENSORPS     
#   - CAUSTIC_FINDER=2+4+8+16+32 
#   - ANNIHILATION_RADIATION  
#   - OUTPUT_LAST_CAUSTIC  
####################################################################################
