#######################################################################
#  Look at end of file for a brief guide to the compile-time options. #
#######################################################################
SYSTYPE=Local
VPATH=./

#--------------------------------------- Basic operation mode of code
OPT += -DDENSITY_INDEPENDENT_SPH
#OPT += -DLIGHTCONE                       # write a lightcone on the fly; in development
OPT += -DPETAPM_ORDER=1  # order of finite differentiation kernel 1 is same as gadget
#OPT += VALGRIND  # allow debugging with valgrind, disable the GADGET memory allocator.

# flags shall that always be there they need to be cleaned up
OPT += -DOPENMP_USE_SPINLOCK
OPT	+= -DUNEQUALSOFTENINGS
OPT += -DSPH_GRAD_RHO  # calculate grad of rho in SPH, required for Krumholtz & Gnedin H2 SFR

#--------------------------------------- Multi-Domain and Top-Level Tree options
OPT	+=  -DMULTIPLEDOMAINS=32
OPT	+=  -DTOPNODEFACTOR=5.0


#--------------------------------------- Things that are always recommended
OPT	+=  -DPEANOHILBERT
OPT	+=  -DWALLCLOCK
OPT	+=  -DMYSORT
OPT	+=  -DDONOTUSENODELIST                # do not use node list in hydro why?
#OPT	+=  -DCPUSPEEDADJUSTMENT
#OPT	+=  -DHYDRO_COST_FACTOR=1000

#---------------------------------------- On the fly FOF groupfinder 
OPT	+=  -DFOF                                # enable FoF output
OPT	+=  -DFOF_PRIMARY_LINK_TYPES=2           # 2^type for the primary dark matter type
OPT	+=  -DFOF_SECONDARY_LINK_TYPES=1+16+32	 # 2^type for the types linked to nearest primaries

#--------------------------------------- SFR/feedback model
# most of the sfr modes are controled in paramfile (which needs a overhaul too!)
OPT	+=  -DCOOLING
OPT	+=  -DSFR
#OPT	+=  -DSOFTEREQS
OPT	+=  -DMETALS
OPT	+=  -DSTELLARAGE
OPT	+=  -DWINDS
#OPT	+=  -DQUICK_LYALPHA
#OPT	+=  -DISOTROPICWINDS


#-------------------------------------- AGN stuff
OPT	+=  -DBLACK_HOLES             # enables Black-Holes (master switch)
OPT	+=  -DBH_ACCRETION # Bondi-Hoyle style accretion model
OPT	+=  -DBH_ENFORCE_EDDINGTON_LIMIT # put a hard limit on the maximum accretion rate
OPT	+=  -DBH_THERMALFEEDBACK      # couple a fraction of the BH luminosity into surrounding gas
OPT	+=  -DBH_SWALLOWGAS              # Enables stochastic accretion of gas particles consistent with growth rate of hole
OPT	+=  -DBH_MERGER # Enables blackhole mergers.
OPT	+=  -DBH_COUNTPROGS	      # carries a counter for each BH that gives the total number of seeds that merged into it
OPT	+=  -DBH_USE_GASVEL_IN_BONDI  # only when this is enabled, the surrounding gas velocity is used in addition to the sounds speed in the Bondi rate 
OPT	+=  -DBH_REPOSITION_ON_POTMIN    # repositions hole on potential minimum (required )

#-------------------------------------------- Things for special behaviour
OPT	+=  -DINCLUDE_RADIATION		# Add radiation density to backround evolution. Only affects the Hubble flow.
#OPT	+=  -DTRADITIONAL_SPH_FORMULATION
OPT	+=  -DNOTEST_FOR_IDUNIQUENESS
OPT	+=  -DNO_ISEND_IRECV_IN_DOMAIN     #sparse MPI_Alltoallv do not use ISEND IRECV
#OPT	+=  -DMPISENDRECV_SIZELIMIT=100
#OPT	+=  -DMPISENDRECV_CHECKSUM
#OPT	+=  -DNOGRAVITY
#OPT	+=  -DNOACCEL
#OPT	+=  -DNOISMPRESSURE
#OPT	+=  -DNOVISCOSITYLIMITER
#OPT	+=  -DNOTREERND
#OPT	+=  -DNO_TREEDATA_IN_RESTART
OPT	+=  -DINHOMOG_GASDISTR_HINT         # if the gas is distributed very different from collisionless particles, this can helps to avoid problems in the domain decomposition -- increase All.MaxPartSph
#OPT	+=  -DTWODIMS
#OPT	+=  -DONEDIM
#OPT	+=  -DSPH_BND_PARTICLES
#OPT	+=  -DNEW_RATES                     # switches in updated cooling rates from Naoki
#OPT	+=  -DREAD_HSML                     # reads hsml from IC file
#OPT   	+=  -DADAPTIVE_GRAVSOFT_FORGAS      # allows variable softening length for gas particles (requires UNEQUALSOFTENINGLENGTH)
#OPT	+=  -DADAPTIVE_GRAVSOFT_FORGAS_HSML # this sets the gravitational softening for SPH particles equal to the SPH smoothing (requires ADAPTIVE_GRAVSOFT_FORGAS)
#OPT	+=  -DSPLIT_PARTICLE_TYPE=4+8
#OPT    +=  -DNEUTRINOS                     # Option for special integration of light neutrino species 
#OPT	+=  -DSTART_WITH_EXTRA_NGBDEV        # Uses special MaxNumNgbDeviation for starting
#OPT	+=  -DVOLUME_CORRECTION=1.75

#--------------------------------------- Time integration options
#OPT	+=  -DNOWINDTIMESTEPPING            # Disable wind reducing timestep (not recommended)
#OPT	+=  -DFORCE_EQUAL_TIMESTEPS

#--------------------------------------- SPH viscosity options
#OPT	+=  -DCONVENTIONAL_VISCOSITY     # enables the old viscosity
#OPT	+=  -DTIME_DEP_ART_VISC          # Enables time dependend viscosity
#OPT	+=  -DHIGH_ART_VISC_START        # Start with high rather than low viscosity
#OPT	+=  -DALTVISCOSITY               # enables alternative viscosity based on div(v)

#--------------------------------------- Glass making/ 2nd-order initial conditions
#OPT	+=  -DMAKEGLASS

#--------------------------------------- degenerate equation of state
#OPT	+=  -DEOS_DEGENERATE
#OPT	+=  -DEOS_COULOMB_CORRECTIONS
#OPT	+=  -DEOS_NSPECIES=3
#OPT	+=  -DWAKEUP=4.1           /* allows 2 timestep bins within kernel */

#--------------------------------------- Select target Computer
include Makefile.$(SYSTYPE)

include $(VPATH)/Makefile.deps


###############################################################################
#
# at compile-time. From the list below, please activate/deactivate the
# options that apply to your run. If you modify any of these options,
# make sure that you recompile the whole code by typing "make clean;
# make".
#
# Main code options:
#
#     These affect the physical model that is simulated.
#
#     - PERIODIC:   Set this if you want to have periodic boundary conditions.
#     - COOLING:    This enables radiative cooling and heating. It also enables
#                   an external UV background which is read from a file.
#     - SFR:        This enables star formation using an effective multiphase
#                   models. This option requires cooling.
#     - METALS:     This model activates the tracking of enrichment in gas and
#                   stars. Note that metal-line cooling is not included yet.
#     - STELLARAGE: This stores the formation redshift of each star particle.
#     - WINDS:      This activates galactic winds. Requires star formation.
#     - ISOTROPICWINDS: This makes the wind isotropic. If not set the wind is
#                       spawned in an axial way. Requires winds to be activated.
#     - NOGRAVITY:  This switches off gravity. Makes only sense for pure
#                   SPH simulations in non-expanding space.
#
# Options for SPH:
#
#     - NOVISCOSITYLIMITER:   If this is set, there is no explicit upper limit
#                             on the viscosity that tries to prevent particle
#                             'reflection' in case of poor timestepping.
#
# Numerical options:
#
#     - NOTREERND:       If this is not set, the tree construction will succeed
#                        even when there are a few particles at identical
#                        locations. This is done by `rerouting' particles once
#                        the node-size has fallen below 1.0e-3 of the softening
#                        length. When this option is activated, this will be
#                        surpressed and the tree construction will always fail
#                        if there are particles at extremely close coordinates.
# - TWODIMS:
#     This effectively switches of one dimension in SPH, i.e. the code
#     follows only 2d hydrodynamics in the xy-, yz-, or xz-plane. This
#     only works with NOGRAVITY, and if all coordinates of the third
#     axis are exactly equal. Can be useful for idealized SPH tests.
#
# - SPH_BND_PARTICLES:
#     If this is set, particles with a particle-ID equal to zero do not
#     receive any SPH acceleration. This can be useful for idealized
#     SPH tests, where these particles represent fixed "walls".
#
#
# Architecture options:
#
#     - T3E:       The code assumes that sizeof(int)=4 holds. A few machines
#                  (like Cray T3E) have sizeof(int)=8. In this case, set the
#                  T3E flag.
#
# Miscellaneous options:
#
#     - PEANOHILBERT:    This is a tuning option. When set, the code will bring
#                        the particles after each domain decomposition into
#                        Peano-Hilbert order. This improves cache utilization
#                        and performance.
#     - WALLCLOCK:       If set, a wallclock timer is used by the code to
#                        measure internal time consumption (see cpu-log file).
#                        Otherwise a timer that measures consumed processor
#                        ticks is used.
#
#     - QUICK_LYALPHA:   This only works for cosmological simulations in periodic boxes
#                        with COOLING & SFR. (WINDS, METALS should be deselected).
#                        It will simply convert all gas particles above overdensity
#                        CritPhysOverdensity and with Temperature below 10^5 K to stars.
#                        This should still leave the Ly-Alpha forest largely unaffected,
#                        but should be faster. It is recommended to set GENERATIONS equal
#                        to 1 for maximum speed-up.
#
##################################################################################
