##
# Run all the tests.
#
#  make test
#
# run a selected suite of tests
#
#  make test SUITE=tests/test_cosmology
#
# To debug a test
#
#  make tests/test_cosmology
#  gdb tests/test_cosmology
#
##
TESTED = \
	slotsmanager \
	interp \
	powerspectrum \
	cosmology \
	forcetree \
	timefac \
	timebinmgr \
	memory \
	openmpsort \
	genic-power

TESTBIN = $(TESTED:%=tests/test_%)
SUITE?= $(TESTBIN)

.PHONY: test run-tests build-tests


depends/lib/libcmocka.a:
	cd depends; make lib/libcmocka.a

build-tests: $(TESTBIN)

test : build-tests
	trap 'err=1' ERR; for tt in $(SUITE) ; do $$tt ; done; exit $$err

clean-tests:
	rm -f $(TESTBIN)

# this empty rule is important for tab-completion
$(TESTBIN):

TESTOBJS=$(DESTDIR)/endrun.o $(DESTDIR)/memory.o $(DESTDIR)/mymalloc.o $(DESTDIR)/system.o $(DESTDIR)/event.o $(DESTDIR)/openmpsort.o 
tests/test_%: tests/test_%.c tests/stub.c $(DESTDIR)/%.o $(TESTOBJS) depends/lib/libcmocka.a
	$(MPICC) $(CFLAGS) $^ $(LIBS) -o $@

tests/test_genic-%: tests/test_genic-%.c tests/stub.c $(DESTDIR)/genic/%.o $(DESTDIR)/endrun.o $(DESTDIR)/memory.o $(DESTDIR)/mymalloc.o $(DESTDIR)/system.o depends/lib/libcmocka.a
	$(MPICC) $(CFLAGS) $^ $(LIBS) -o $@
