MP-Gadget: libgadget/utils/mpsort.h File Reference
mpsort.h File Reference
Macros
#define MPSORT_DISABLE_GATHER_SORT (1 << 3)
#define MPSORT_REQUIRE_GATHER_SORT (1 << 4)
#define mpsort_mpi(base, nmemb, elsize, radix, rsize, arg, comm)
#define mpsort_mpi_newarray(base, nmemb, out, outnmemb, elsize, radix, rsize, arg, comm)
Functions
void mpsort_mpi_set_options (int options)
int mpsort_mpi_has_options (int options)
void mpsort_mpi_unset_options (int options)
void mpsort_mpi_impl (void *base, size_t nmemb, size_t elsize, void(*radix)(const void *ptr, void *radix, void *arg), size_t rsize, void *arg, MPI_Comm comm, const int line, const char *file)
void mpsort_mpi_newarray_impl (void *base, size_t nmemb, void *out, size_t outnmemb, size_t size, void(*radix)(const void *ptr, void *radix, void *arg), size_t rsize, void *arg, MPI_Comm comm, const int line, const char *file)
void mpsort_mpi_report_last_run ()
void mpsort_setup_timers (int ntimers)
void mpsort_free_timers (void)
Macro Definition Documentation
MPSORT_DISABLE_GATHER_SORT
#define MPSORT_DISABLE_GATHER_SORT (1 << 3)
Definition at line 5 of file mpsort.h.
mpsort_mpi
#define mpsort_mpi (base, nmemb, elsize, radix, rsize, arg, comm)
Value:
    mpsort_mpi_impl(base, nmemb, elsize, radix, rsize, arg, comm, \
    __LINE__, __FILE__)
Definition at line 26 of file mpsort.h.
mpsort_mpi_newarray
#define mpsort_mpi_newarray (base, nmemb, out, outnmemb, elsize, radix, rsize, arg, comm)
Value:
    mpsort_mpi_newarray_impl(base, nmemb, out, outnmemb, elsize, \
    radix, rsize, arg, comm, __LINE__, __FILE__)
Definition at line 30 of file mpsort.h.
MPSORT_REQUIRE_GATHER_SORT
#define MPSORT_REQUIRE_GATHER_SORT (1 << 4)
Definition at line 6 of file mpsort.h.
Function Documentation
mpsort_free_timers()
void mpsort_free_timers (void)
Definition at line 745 of file mpsort.c.
 {
     if(!(_TIMERS.tmr)) {
         myfree(_TIMERS.tmr);
         _TIMERS.tmr = NULL;
         _TIMERS.ntimer = 0;
         _TIMERS.curtmr = 0;
     }
 }
References _TIMERS, TIMERS::curtmr, myfree, TIMERS::ntimer, and TIMERS::tmr.
mpsort_mpi_has_options()
int mpsort_mpi_has_options (int options)
Definition at line 1444 of file mpsort.c.
 {
     _mpsort_mpi_parse_env();
     return _mpsort_mpi_options & options;
 }
References _mpsort_mpi_options, and _mpsort_mpi_parse_env().
Referenced by mpsort_mpi_newarray_impl().
mpsort_mpi_impl()
void mpsort_mpi_impl (void * base, size_t nmemb, size_t elsize, void(*)(const void *ptr, void *radix, void *arg) radix, size_t rsize, void * arg, MPI_Comm comm, const int line, const char * file)
Definition at line 775 of file mpsort.c.
 {
     mpsort_mpi_newarray_impl(mybase, mynmemb,
         mybase, mynmemb,
         size, radix, rsize, arg, comm, line, file);
 }
References mpsort_mpi_newarray_impl().
mpsort_mpi_newarray_impl()
void mpsort_mpi_newarray_impl (void * base, size_t nmemb, void * out, size_t outnmemb, size_t size, void(*)(const void *ptr, void *radix, void *arg) radix, size_t rsize, void * arg, MPI_Comm comm, const int line, const char * file)
Definition at line 809 of file mpsort.c.
 {
     if(MPI_TYPE_PTRDIFF == 0) {
         if(MPI_SUCCESS != MPI_Type_match_size(MPI_TYPECLASS_INTEGER, sizeof(ptrdiff_t), &MPI_TYPE_PTRDIFF))
             endrun(3, "Ptrdiff size %ld not recognised\n", sizeof(ptrdiff_t));
     }
     struct SegmentGroupDescr seggrp[1];
     uint64_t sum1 = checksum(mybase, elsize * mynmemb, comm);
     int NTask;
     int ThisTask;
     MPI_Comm_size(comm, &NTask);
     MPI_Comm_rank(comm, &ThisTask);
     if(elsize > 8 && elsize % 8 != 0) {
         if(ThisTask == 0) {
             endrun(12, "MPSort: element size is large (%d) but not aligned to 8 bytes. "
                             "This is known to frequently trigger MPI bugs. "
                             "Caller site: %s:%d\n",
                             elsize, file, line);
         }
     }
     if(rsize > 8 && rsize % 8 != 0) {
         if(ThisTask == 0) {
             endrun(12, "MPSort: radix size is large (%d) but not aligned to 8 bytes. "
                             "This is known to frequently trigger MPI bugs. "
                             "Caller site: %s:%d\n",
                             rsize, file, line);
         }
     }
     size_t * sizes = ta_malloc("sizes", size_t, NTask);
     size_t myoffset;
     size_t totalsize = _collect_sizes(mynmemb, sizes, &myoffset, comm);
     size_t avgsegsize = NTask; /* combine very small ranks to segments */
     if (avgsegsize * elsize > 4 * 1024 * 1024) {
         /* do not use more than 4MB in a segment */
         avgsegsize = 4 * 1024 * 1024 / elsize;
     }
     if(mpsort_mpi_has_options(MPSORT_REQUIRE_GATHER_SORT)) {
         message(0, "MPSort: gathering all data to a single rank for sorting due to MPSORT_REQUIRE_GATHER_SORT. "
                    "Total number of items is %ld. Caller site: %s:%d\n",
                    totalsize, file, line);
         avgsegsize = totalsize;
     }
     if(mpsort_mpi_has_options(MPSORT_DISABLE_GATHER_SORT)) {
         avgsegsize = 0;
         message(0, "MPSort: disable gathering data into larger chunks due to MPSORT_DISABLE_GATHER_SORT. "
                    "Caller site: %s:%d\n",
                    file, line);
     }
     /* use as many groups as possible (some will be empty) but at most 1 segment per group */
     _create_segment_group(seggrp, sizes, avgsegsize, NTask, comm);
     myfree(sizes);
     /* group comm == seg comm */
     void * mysegmentbase = NULL;
     void * myoutsegmentbase = NULL;
     size_t mysegmentnmemb;
     size_t myoutsegmentnmemb;
     int groupsize;
     int grouprank;
     MPI_Comm_size(seggrp->Group, &groupsize);
     MPI_Comm_rank(seggrp->Group, &grouprank);
     MPI_Allreduce(&mynmemb, &mysegmentnmemb, 1, MPI_TYPE_PTRDIFF, MPI_SUM, seggrp->Group);
     MPI_Allreduce(&myoutnmemb, &myoutsegmentnmemb, 1, MPI_TYPE_PTRDIFF, MPI_SUM, seggrp->Group);
     if (groupsize > 1) {
         if(grouprank == seggrp->group_leader_rank) {
             mysegmentbase = mymalloc("segmentbase", mysegmentnmemb * elsize);
             myoutsegmentbase = mymalloc("outsegment", myoutsegmentnmemb * elsize);
         }
         MPIU_Gather(seggrp->Group, seggrp->group_leader_rank, mybase, mysegmentbase, mynmemb, elsize, NULL);
     } else {
         mysegmentbase = mybase;
         myoutsegmentbase = myoutbase;
     }
     /* only do sorting on the group leaders for each segment */
     if(seggrp->is_group_leader) {
         struct crstruct d;
         struct crmpistruct o;
         _setup_radix_sort(&d, mysegmentbase, mysegmentnmemb, elsize, radix, rsize, arg);
         _setup_mpsort_mpi(&o, &d, myoutsegmentbase, myoutsegmentnmemb, seggrp->Leaders);
         mpsort_mpi_histogram_sort(d, o);
         _destroy_mpsort_mpi(&o);
     }
     if(groupsize > 1) {
         MPIU_Scatter(seggrp->Group, seggrp->group_leader_rank, myoutsegmentbase, myoutbase, myoutnmemb, elsize, NULL);
     }
 /*    {
         int ntmr;
         if(seggrp->is_group_leader)
             ntmr = (mpsort_mpi_find_ntimers(tmr) + 1);
         MPI_Bcast(&ntmr, 1, MPI_INT, seggrp->group_leader_rank, seggrp->Group);
         MPI_Bcast(tmr, sizeof(tmr[0]) * ntmr, MPI_BYTE, seggrp->group_leader_rank, seggrp->Group);
     }*/
     if(grouprank == seggrp->group_leader_rank) {
         if(myoutsegmentbase != myoutbase)
             myfree(myoutsegmentbase);
         if(mysegmentbase != mybase)
             myfree(mysegmentbase);
     }
     _destroy_segment_group(seggrp);
     uint64_t sum2 = checksum(myoutbase, elsize * myoutnmemb, comm);
     if (sum1 != sum2) {
         endrun(5, "Data changed after sorting; checksum mismatch.\n");
     }
 }
References _collect_sizes(), _create_segment_group(), _destroy_mpsort_mpi(), _destroy_segment_group(), _setup_mpsort_mpi(), _setup_radix_sort(), checksum(), crmpistruct::comm, endrun(), SegmentGroupDescr::Group, SegmentGroupDescr::group_leader_rank, SegmentGroupDescr::is_group_leader, SegmentGroupDescr::Leaders, message(), MPI_TYPE_PTRDIFF, MPIU_Gather(), MPIU_Scatter(), MPSORT_DISABLE_GATHER_SORT, mpsort_mpi_has_options(), mpsort_mpi_histogram_sort(), MPSORT_REQUIRE_GATHER_SORT, crmpistruct::mybase, myfree, mymalloc, crmpistruct::myoutbase, crmpistruct::myoutnmemb, NTask, ta_malloc, ThisTask, and SegmentGroupDescr::totalsize.
Referenced by mpsort_mpi_impl().
mpsort_mpi_report_last_run()
void mpsort_mpi_report_last_run ()
Definition at line 756 of file mpsort.c.
{
     if(!(_TIMERS.tmr))
         return;
     double last = _TIMERS.tmr[0].time;
     int i;
     for(i = 1; i < _TIMERS.curtmr; i++) {
         struct TIMER * tmr = &_TIMERS.tmr[i];
         if(0 == strncmp(tmr->name, "END", 20))
             break;
         message(0, "%s: %g\n", tmr->name, tmr->time - last);
         last = tmr->time;
     }
 }
References _TIMERS, TIMERS::curtmr, message(), TIMER::name, TIMER::time, and TIMERS::tmr.
mpsort_mpi_set_options()
void mpsort_mpi_set_options (int options)
Definition at line 1437 of file mpsort.c.
 {
     _mpsort_mpi_parse_env();
     _mpsort_mpi_options |= options;
 }
References _mpsort_mpi_options, and _mpsort_mpi_parse_env().
Referenced by _mpsort_mpi_parse_env(), and do_mpsort_test().
mpsort_mpi_unset_options()
void mpsort_mpi_unset_options (int options)
Definition at line 1451 of file mpsort.c.
 {
     _mpsort_mpi_parse_env();
     _mpsort_mpi_options &= ~options;
 }
References _mpsort_mpi_options, and _mpsort_mpi_parse_env().
Referenced by do_mpsort_test().
mpsort_setup_timers()
void mpsort_setup_timers (int ntimers)
Definition at line 736 of file mpsort.c.
 {
     if(!(_TIMERS.tmr)) {
         _TIMERS.tmr = (struct TIMER *) mymalloc2("timers", ntimers * sizeof(struct TIMER));
         _TIMERS.ntimer = ntimers;
         _TIMERS.curtmr = 0;
     }
 }
References _TIMERS, TIMERS::curtmr, mymalloc2, TIMERS::ntimer, and TIMERS::tmr.
Referenced by do_mpsort_test().