MP-Gadget: libgadget/utils/mymalloc.h File Reference
mymalloc.h File Reference
#include "memory.h"
Macros
#define mymalloc(name, size) allocator_alloc_bot(A_MAIN, name, size)
#define mymalloc2(name, size) allocator_alloc_top(A_MAIN, name, size)
#define myrealloc(ptr, size) allocator_realloc(A_MAIN, ptr, size)
#define myfree(x) allocator_free(x)
#define ma_malloc(name, type, nele) (type*) allocator_alloc_bot(A_MAIN, name, sizeof(type) * (nele))
#define ma_malloc2(name, type, nele) (type*) allocator_alloc_top(A_MAIN, name, sizeof(type) * (nele))
#define ma_free(p) allocator_free(p)
#define ta_malloc(name, type, nele) (type*) allocator_alloc_bot(A_TEMP, name, sizeof(type) * (nele))
#define ta_malloc2(name, type, nele) (type*) allocator_alloc_top(A_TEMP, name, sizeof(type) * (nele))
#define ta_reset() allocator_reset(A_TEMP, 0)
#define ta_free(p) allocator_free(p)
#define report_memory_usage(x) report_detailed_memory_usage(x, "%s:%d", __FILE__, __LINE__)
#define mymalloc_freebytes() allocator_get_free_size(A_MAIN)
#define mymalloc_usedbytes() allocator_get_used_size(A_MAIN, ALLOC_DIR_BOTH)
Functions
void mymalloc_init (double MemoryMB)
void tamalloc_init (void)
void report_detailed_memory_usage (const char *label, const char *fmt,...)
Variables
Allocator A_MAIN [1]
Allocator A_TEMP [1]
Macro Definition Documentation
ma_free
#define ma_free (p) allocator_free(p)
Definition at line 23 of file mymalloc.h.
ma_malloc
#define ma_malloc (name, type, nele) (type*) allocator_alloc_bot(A_MAIN, name, sizeof(type) * (nele))
Definition at line 21 of file mymalloc.h.
ma_malloc2
#define ma_malloc2 (name, type, nele) (type*) allocator_alloc_top(A_MAIN, name, sizeof(type) * (nele))
Definition at line 22 of file mymalloc.h.
myfree
#define myfree (x) allocator_free(x)
Definition at line 19 of file mymalloc.h.
mymalloc
#define mymalloc (name, size) allocator_alloc_bot(A_MAIN, name, size)
Definition at line 15 of file mymalloc.h.
mymalloc2
#define mymalloc2 (name, size) allocator_alloc_top(A_MAIN, name, size)
Definition at line 16 of file mymalloc.h.
mymalloc_freebytes
#define mymalloc_freebytes () allocator_get_free_size(A_MAIN)
Definition at line 31 of file mymalloc.h.
mymalloc_usedbytes
#define mymalloc_usedbytes () allocator_get_used_size(A_MAIN, ALLOC_DIR_BOTH)
Definition at line 32 of file mymalloc.h.
myrealloc
#define myrealloc (ptr, size) allocator_realloc(A_MAIN, ptr, size)
Definition at line 18 of file mymalloc.h.
report_memory_usage
#define report_memory_usage (x) report_detailed_memory_usage(x, "%s:%d", __FILE__, __LINE__)
Definition at line 30 of file mymalloc.h.
ta_free
#define ta_free (p) allocator_free(p)
Definition at line 28 of file mymalloc.h.
ta_malloc
#define ta_malloc (name, type, nele) (type*) allocator_alloc_bot(A_TEMP, name, sizeof(type) * (nele))
Definition at line 25 of file mymalloc.h.
ta_malloc2
#define ta_malloc2 (name, type, nele) (type*) allocator_alloc_top(A_TEMP, name, sizeof(type) * (nele))
Definition at line 26 of file mymalloc.h.
ta_reset
#define ta_reset () allocator_reset(A_TEMP, 0)
Definition at line 27 of file mymalloc.h.
Function Documentation
mymalloc_init()
void mymalloc_init (double MemoryMB)
Definition at line 48 of file mymalloc.c.
 {
     /* Warning: this uses ta_malloc*/
     size_t Nhost = cluster_get_num_hosts();
     MPI_Comm comm = MPI_COMM_WORLD;
     int NTask;
     MPI_Comm_size(comm, &NTask);
     double nodespercpu = (1.0 * Nhost) / (1.0 * NTask);
     size_t n = 1.0 * MaxMemSizePerNode * nodespercpu * 1024. * 1024.;
     message(0, "Nhost = %d\n", Nhost);
     message(0, "Reserving %td bytes per rank for MAIN memory allocator. \n", n);
     if(n < 1)
         endrun(2, "Mem too small! MB/node=%g, nodespercpu = %g NTask = %d\n", MaxMemSizePerNode, nodespercpu, NTask);
     if (MPIU_Any(ALLOC_ENOMEMORY == allocator_init(A_MAIN, "MAIN", n, 1, NULL), MPI_COMM_WORLD)) {
         endrun(0, "Insufficient memory for the MAIN allocator on at least one nodes."
                   "Requestion %td bytes. Try reducing MaxMemSizePerNode. Also check the node health status.\n", n);
     }
 }
References A_MAIN, ALLOC_ENOMEMORY, allocator_init(), cluster_get_num_hosts(), endrun(), message(), MPIU_Any(), and NTask.
Referenced by main().
report_detailed_memory_usage()
void report_detailed_memory_usage (const char * label, const char * fmt, ...)
Definition at line 75 of file mymalloc.c.
 {
     if(allocator_get_used_size(A_MAIN, ALLOC_DIR_BOTH) < highest_memory_usage) {
         return;
     }
     MPI_Comm comm = MPI_COMM_WORLD;
     int NTask;
     int ThisTask;
     MPI_Comm_size(comm, &NTask);
     MPI_Comm_rank(comm, &ThisTask);
     if (ThisTask != 0) {
         return;
     }
     highest_memory_usage = allocator_get_used_size(A_MAIN, ALLOC_DIR_BOTH);
     va_list va;
     va_start(va, fmt);
     char * buf = fastpm_strdup_vprintf(fmt, va);
     va_end(va);
     message(1, "Peak Memory usage induced by %s\n", buf);
     myfree(buf);
     allocator_print(A_MAIN);
 }
References A_MAIN, ALLOC_DIR_BOTH, allocator_get_used_size(), allocator_print(), fastpm_strdup_vprintf(), highest_memory_usage, message(), myfree, NTask, and ThisTask.
tamalloc_init()
void tamalloc_init (void)
Definition at line 29 of file mymalloc.c.
 {
     int Nt = omp_get_max_threads();
     int NTask;
     MPI_Comm_size(MPI_COMM_WORLD, &NTask);
     /* Reserve 4MB, 512 bytes per thread, 128 bytes per task and 128 bytes per thread per task (for export) for TEMP storage.*/
     size_t n = 4096 * 1024 + 128 * NTask + 128 * Nt * NTask + 512 * Nt;
     message(0, "Reserving %td bytes per rank for TEMP memory allocator. \n", n);
     if (MPIU_Any(ALLOC_ENOMEMORY == allocator_init(A_TEMP, "TEMP", n, 1, NULL), MPI_COMM_WORLD)) {
         endrun(0, "Insufficient memory for the TEMP allocator on at least one nodes."
                   "Requestion %td bytes. Try reducing MaxMemSizePerNode. Also check the node health status.\n", n);
     }
 }
References A_TEMP, ALLOC_ENOMEMORY, allocator_init(), endrun(), message(), MPIU_Any(), and NTask.
Referenced by main().
Variable Documentation
A_MAIN
Allocator A_MAIN[1] extern
Definition at line 17 of file mymalloc.c.
Referenced by mymalloc_init(), and report_detailed_memory_usage().
A_TEMP
Allocator A_TEMP[1] extern
Definition at line 22 of file mymalloc.c.
Referenced by tamalloc_init().