MP-Gadget: param2.c File Reference
param2.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
Classes
struct ParamError
struct ParamParser
struct ParamParser::ParamItem
struct ParamSchema
Typedefs
typedef struct ParamError ParamError
typedef struct ParamParser ParamParser
typedef struct ParamSchema ParamSchema
Functions
int param_parser_get_int (ParamParser *parser, ParamSchema *schema)
double param_parser_get_double (ParamParser *parser, ParamSchema *schema)
char * param_parser_get_string (ParamParser *parser, ParamSchema *schema)
void param_parser_copy_string (ParamParser *parser, ParamSchema *schema, char *dest, size_t len)
ParamParser * param_parser_new (const char *rawtext)
static void param_parser_raise (ParamParser *parser, const char *fmt,...)
static int param_parser_parse (ParamParser *parser, const char *start, const int size)
static char * param_parser_find_key (ParamParser *parser, ParamSchema *schema)
char * param_parser_get_error (ParamParser *parser)
Typedef Documentation
ParamError
typedef struct ParamError ParamError
ParamParser
typedef struct ParamParser ParamParser
ParamSchema
typedef struct ParamSchema ParamSchema
Function Documentation
param_parser_copy_string()
void param_parser_copy_string (ParamParser * parser, ParamSchema * schema, char * dest, size_t len)
param_parser_find_key()
static char* param_parser_find_key (ParamParser * parser, ParamSchema * schema) static
Definition at line 121 of file param2.c.
References ParamParser::head, ParamSchema::key, ParamParser::ParamItem::next, param_parser_raise(), and ParamSchema::required.
Referenced by param_parser_get_double(), param_parser_get_int(), and param_parser_get_string().
 {
     struct ParamItem * p;
     for(p = parser->head.next; p; p = p->next) {
         if(0 == strcasecmp(p->key, schema->key)) {
             return p->value;
         }
     }
     if(schema->required) {
         param_parser_raise(parser, "%s is required", schema->key);
     }
     return NULL;
 }
param_parser_get_double()
double param_parser_get_double (ParamParser * parser, ParamSchema * schema)
Definition at line 151 of file param2.c.
References ParamSchema::def, ParamSchema::f, param_parser_find_key(), and param_parser_raise().
 {
     const char * value = param_parser_find_key(parser, schema);
     if(value) {
         double f;
         if(1 == sscanf(value, "%g", &f)) {
             return f;
         } else {
             param_parser_raise(parser, "%s cannot be parsed as a float", value);
         }
     }
     return schema->def.f;
 }
param_parser_get_error()
char* param_parser_get_error (ParamParser * parser)
Definition at line 174 of file param2.c.
References ParamParser::error, and ParamError::message.
 {
     return parser->error->message;
 }
param_parser_get_int()
int param_parser_get_int (ParamParser * parser, ParamSchema * schema)
Definition at line 136 of file param2.c.
References ParamSchema::def, ParamSchema::i, param_parser_find_key(), and param_parser_raise().
 {
     const char * value = param_parser_find_key(parser, schema);
     if(value) {
         int i;
         if(1 == sscanf(value, "%d", &i)) {
             return i;
         } else {
             param_parser_raise(parser, "%s cannot be parsed as an integer", value);
         }
     }
     return schema->def.i;
 }
param_parser_get_string()
char * param_parser_get_string (ParamParser * parser, ParamSchema * schema)
Definition at line 166 of file param2.c.
References ParamSchema::def, param_parser_find_key(), and ParamSchema::s.
 {
     const char * value = param_parser_find_key(parser, schema);
     if(value) return value;
     return schema->def.s;
 }
param_parser_new()
ParamParser * param_parser_new (const char * rawtext)
Definition at line 113 of file param2.c.
References param_parser_parse().
 {
     ParamParser * self = calloc(sizeof(ParamParser), 1);
     self->error = NULL;
     param_parser_parse(self, rawtext, strlen(rawtext));
     return self;
 }
param_parser_parse()
static int param_parser_parse (ParamParser * parser, const char * start, const int size) static
Definition at line 63 of file param2.c.
References ParamParser::head, name, ParamParser::ParamItem::next, param_parser_raise(), and make_zeros::size.
Referenced by param_parser_new().
 {
     /* parse a line */
     char * buf = alloca(size + 1);
     static char blanks[] = " \t\r\n";
     static char comments[] =  "%#";
     strncpy(buf, start, size);
     buf[size] = 0;
     if (size == 0) return 0;
     /* blank lines are OK */
     char * name = NULL;
     char * value = NULL;
     char * ptr = buf;
     /* parse name */
     while(*ptr && strchr(blanks, *ptr)) ptr++;
     if (*ptr == 0 || strchr(comments, *ptr)) {
         /* This line is fully comment */
         return 0;
     }
     name = ptr;
     while(*ptr && !strchr(blanks, *ptr)) ptr++;
     *ptr = 0;
     ptr++;
     /* parse value */
     while(*ptr && strchr(blanks, *ptr)) ptr++;
     if (*ptr == 0 || strchr(comments, *ptr)) {
         /* This line is malformed, must have a value! */
         strncpy(buf, start, size);
         param_parser_raise(parser, "Line `%s` is malformed.\n", buf);
         return 1;
     }
     value = ptr;
     while(*ptr && !strchr(comments, *ptr)) ptr++;
     *ptr = 0;
     ptr++;
     /* name */ /* value */
     struct ParamItem * item = calloc(sizeof(struct ParamItem), 1);
     item->key = strdup(name);
     item->value = strdup(value);
     item->next = parser->head.next;
     parser->head.next = item;
     return 0;
 }
param_parser_raise()
static void param_parser_raise (ParamParser * parser, const char * fmt, ...) static
Definition at line 47 of file param2.c.
References ParamParser::error, ParamError::message, and ParamError::next.
Referenced by param_parser_find_key(), param_parser_get_double(), param_parser_get_int(), and param_parser_parse().
 {
     char buf[4096];
     va_list va;
     va_start (va, fmt);
     vsprintf(buf, fmt, va);
     va_end(va);
     ParamError * old = parser->error;
     ParamError * n = calloc(sizeof(ParamError), 1);
     n->message = strdup(buf);
     parser->error = n;
     n->next = old;
 }