MP-Gadget: gadget/params.h File Reference
params.h File Reference
Functions
void read_parameter_file (char *fname, int *ShowBacktrace, double *MaxMemSizePerNode)
Function Documentation
read_parameter_file()
void read_parameter_file (char * fname, int * ShowBacktrace, double * MaxMemSizePerNode)
This function parses the parameterfile in a simple way. Each paramater is defined by a keyword (‘tag’), and can be either of type douple, int, or character string. The routine makes sure that each parameter appears exactly once in the parameterfile, otherwise error messages are produced that complain about the missing parameters.
Definition at line 359 of file params.c.
 {
     ParameterSet * ps = create_gadget_parameter_set();
     int ThisTask;
     MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
     if(0 != param_parse_file(ps, fname)) {
         endrun(1, "Parsing %s failed.\n", fname);
     }
     if(0 != param_validate(ps)) {
         endrun(1, "Validation of %s failed: %s\n", fname);
     }
     message(0, "----------- Running with Parameters ----------\n");
     if(ThisTask == 0)
         param_dump(ps, stdout);
     message(0, "----------------------------------------------\n");
     *ShowBacktrace = param_get_int(ps, "ShowBacktrace");
     *MaxMemSizePerNode = param_get_double(ps, "MaxMemSizePerNode");
     if(*MaxMemSizePerNode <= 1) {
         *MaxMemSizePerNode *= get_physmem_bytes() / (1024. * 1024.);
     }
     /*Initialize per-module parameters.*/
     set_all_global_params(ps);
     set_init_params(ps);
     set_petaio_params(ps);
     set_timestep_params(ps);
     set_cooling_params(ps);
     set_density_params(ps);
     set_hydro_params(ps);
     set_qso_lightup_params(ps);
     set_treewalk_params(ps);
     set_gravshort_tree_params(ps);
     set_domain_params(ps);
     set_sfr_params(ps);
     set_winds_params(ps);
     set_fof_params(ps);
     set_blackhole_params(ps);
     set_metal_return_params(ps);
     set_stats_params(ps);
     parameter_set_free(ps);
 }
References create_gadget_parameter_set(), endrun(), get_physmem_bytes(), message(), param_dump(), param_get_double(), param_get_int(), param_parse_file(), param_validate(), parameter_set_free(), set_all_global_params(), set_blackhole_params(), set_cooling_params(), set_density_params(), set_domain_params(), set_fof_params(), set_gravshort_tree_params(), set_hydro_params(), set_init_params(), set_metal_return_params(), set_petaio_params(), set_qso_lightup_params(), set_sfr_params(), set_stats_params(), set_timestep_params(), set_treewalk_params(), set_winds_params(), ShowBacktrace, and ThisTask.
Referenced by main().