MP-Gadget: param.h File Reference
param.h File Reference
Functions
void read_parameter_file (char *fname)
Function Documentation
read_parameter_file()
void read_parameter_file (char * fname)
This function parses the parameterfile in a simple way. Each paramater is defined by a keyword (`tag'), and can be either of type douple, int, or character string. The routine makes sure that each parameter appears exactly once in the parameterfile, otherwise error messages are produced that complain about the missing parameters.
Definition at line 324 of file param.c.
References global_data_all_processes::AggregatedIOThreshold, All, global_data_all_processes::ArtBulkViscConst, global_data_all_processes::Asmth, global_data_all_processes::AutoSnapshotTime, global_data_all_processes::BlackHoleAccretionFactor, global_data_all_processes::BlackHoleEddingtonFactor, global_data_all_processes::BlackHoleFeedbackFactor, global_data_all_processes::BlackHoleFeedbackMethod, global_data_all_processes::BlackHoleFeedbackRadius, global_data_all_processes::BlackHoleFeedbackRadiusMaxPhys, global_data_all_processes::BlackHoleMaxAccretionRadius, global_data_all_processes::BlackHoleNgbFactor, global_data_all_processes::BlackHoleOn, global_data_all_processes::BlackHoleSoundSpeedFromPressure, global_data_all_processes::BufferSize, global_data_all_processes::BytesPerFile, global_data_all_processes::CAMBInputSpectrum_UnitLength_in_cm, global_data_all_processes::CAMBTransferFunction, Cosmology::CMBTemperature, global_data_all_processes::CoolingOn, global_data_all_processes::CourantFac, global_data_all_processes::CP, global_data_all_processes::CpuFile, create_gadget_parameter_set(), density_kernel_desnumngb(), density_kernel_init(), global_data_all_processes::DensityContrastLimit, global_data_all_processes::DensityKernelType, global_data_all_processes::DensityOn, global_data_all_processes::DensityResolutionEta, global_data_all_processes::DesNumNgb, global_data_all_processes::DomainOverDecompositionFactor, global_data_all_processes::DomainUseGlobalSorting, global_data_all_processes::EnableAggregatedIO, endrun(), global_data_all_processes::EnergyFile, global_data_all_processes::ErrTolForceAcc, global_data_all_processes::ErrTolIntAccuracy, global_data_all_processes::FastParticleType, global_data_all_processes::FOFFileBase, global_data_all_processes::FOFHaloLinkingLength, global_data_all_processes::FOFHaloMinLength, global_data_all_processes::FOFSaveParticles, global_data_all_processes::ForceEqualTimesteps, global_data_all_processes::GravitySoftening, global_data_all_processes::GravitySofteningGas, global_data_all_processes::HeliumHeatAmp, global_data_all_processes::HeliumHeatExp, global_data_all_processes::HeliumHeatOn, global_data_all_processes::HeliumHeatThresh, Cosmology::HubbleParam, global_data_all_processes::HybridNeutrinosOn, global_data_all_processes::HybridNuPartTime, global_data_all_processes::HybridVcrit, global_data_all_processes::HydroCostFactor, global_data_all_processes::HydroOn, global_data_all_processes::InitCondFile, global_data_all_processes::InitGasTemp, global_data_all_processes::IO, kernel(), global_data_all_processes::MakeGlassFile, global_data_all_processes::MassiveNuLinRespOn, global_data_all_processes::MaxGasVel, global_data_all_processes::MaxMemSizePerNode, global_data_all_processes::MaxNumNgbDeviation, global_data_all_processes::MaxRMSDisplacementFac, global_data_all_processes::MaxSizeTimestep, message(), global_data_all_processes::MetalCoolFile, global_data_all_processes::MinFoFMassForNewSeed, global_data_all_processes::MinGasHsmlFractional, global_data_all_processes::MinGasTemp, global_data_all_processes::MinNumWriters, global_data_all_processes::MinSizeTimestep, Cosmology::MNu, DensityKernel::name, global_data_all_processes::Nmesh, global_data_all_processes::NumThreads, global_data_all_processes::NumWriters, Cosmology::Omega0, Cosmology::Omega_fld, Cosmology::OmegaBaryon, Cosmology::OmegaLambda, omp_get_max_threads, global_data_all_processes::OutputDir, global_data_all_processes::OutputEnergyDebug, global_data_all_processes::OutputPotential, param_dump(), param_get_double(), param_get_enum(), param_get_int(), param_get_string2(), param_parse_file(), param_validate(), parameter_set_free(), global_data_all_processes::PartAllocFactor, global_data_all_processes::QuickLymanAlphaProbability, Cosmology::RadiationOn, global_data_all_processes::SeedBlackHoleMass, global_data_all_processes::SnapshotFileBase, global_data_all_processes::SnapshotWithFOF, global_data_all_processes::StarformationCriterion, global_data_all_processes::StarformationOn, ThisTask, global_data_all_processes::TimeBetweenSeedingSearch, global_data_all_processes::TimeLimitCPU, global_data_all_processes::TimeMax, global_data_all_processes::TopNodeAllocFactor, global_data_all_processes::TopNodeIncreaseFactor, global_data_all_processes::TreeCoolFile, global_data_all_processes::TreeGravOn, global_data_all_processes::UsePeculiarVelocity, global_data_all_processes::UVFluctuationFile, global_data_all_processes::UVRedshiftThreshold, Cosmology::w0_fld, Cosmology::wa_fld, global_data_all_processes::WindModel, global_data_all_processes::WindOn, and global_data_all_processes::WritersPerFile.
Referenced by main().
 {
     if(ThisTask == 0) {
         ParameterSet * ps = create_gadget_parameter_set();
         if(0 != param_parse_file(ps, fname)) {
             endrun(1, "Parsing %s failed.", fname);
         }
         if(0 != param_validate(ps)) {
             endrun(1, "Validation of %s failed.", fname);
         }
         message(1, "----------- Running with Parameters ----------\n");
         param_dump(ps, stdout);
         message(1, "----------------------------------------------\n");
         All.NumThreads = omp_get_max_threads();
     /* Start reading the values */
         param_get_string2(ps, "InitCondFile", All.InitCondFile);
         param_get_string2(ps, "OutputDir", All.OutputDir);
         param_get_string2(ps, "TreeCoolFile", All.TreeCoolFile);
         param_get_string2(ps, "MetalCoolFile", All.MetalCoolFile);
         param_get_string2(ps, "UVFluctuationfile", All.UVFluctuationFile);
         param_get_string2(ps, "SnapshotFileBase", All.SnapshotFileBase);
         param_get_string2(ps, "FOFFileBase", All.FOFFileBase);
         param_get_string2(ps, "EnergyFile", All.EnergyFile);
         All.OutputEnergyDebug = param_get_int(ps, "EnergyFile");
         param_get_string2(ps, "CpuFile", All.CpuFile);
         All.DensityKernelType = param_get_enum(ps, "DensityKernelType");
         All.CP.CMBTemperature = param_get_double(ps, "CMBTemperature");
         All.CP.RadiationOn = param_get_int(ps, "RadiationOn");
         All.CP.Omega0 = param_get_double(ps, "Omega0");
         All.CP.OmegaBaryon = param_get_double(ps, "OmegaBaryon");
         All.CP.OmegaLambda = param_get_double(ps, "OmegaLambda");
         All.CP.Omega_fld = param_get_double(ps, "Omega_fld");
         if(All.CP.OmegaLambda > 0 && All.CP.Omega_fld > 0)
             endrun(0, "Cannot have OmegaLambda and Omega_fld (evolving dark energy) at the same time!\n");
         All.CP.w0_fld = param_get_double(ps,"w0_fld");
         All.CP.wa_fld = param_get_double(ps,"wa_fld");
         All.CP.HubbleParam = param_get_double(ps, "HubbleParam");
         All.DomainOverDecompositionFactor = param_get_int(ps, "DomainOverDecompositionFactor");
         All.DomainUseGlobalSorting = param_get_int(ps, "DomainUseGlobalSorting");
         All.TopNodeIncreaseFactor = param_get_int(ps, "TopNodeIncreaseFactor");
         All.OutputPotential = param_get_int(ps, "OutputPotential");
         All.MaxMemSizePerNode = param_get_int(ps, "MaxMemSizePerNode");
         All.TimeMax = param_get_double(ps, "TimeMax");
         All.ErrTolIntAccuracy = param_get_double(ps, "ErrTolIntAccuracy");
         All.ErrTolForceAcc = param_get_double(ps, "ErrTolForceAcc");
         All.Asmth = param_get_double(ps, "Asmth");
         All.Nmesh = param_get_int(ps, "Nmesh");
         All.MinGasHsmlFractional = param_get_double(ps, "MinGasHsmlFractional");
         All.MaxGasVel = param_get_double(ps, "MaxGasVel");
         All.MaxSizeTimestep = param_get_double(ps, "MaxSizeTimestep");
         All.MinSizeTimestep = param_get_double(ps, "MinSizeTimestep");
         All.ForceEqualTimesteps = param_get_int(ps, "ForceEqualTimesteps");
         All.MaxRMSDisplacementFac = param_get_double(ps, "MaxRMSDisplacementFac");
         All.ArtBulkViscConst = param_get_double(ps, "ArtBulkViscConst");
         All.CourantFac = param_get_double(ps, "CourantFac");
         All.DensityResolutionEta = param_get_double(ps, "DensityResolutionEta");
         All.HydroCostFactor = param_get_double(ps, "HydroCostFactor");
         All.DensityContrastLimit = param_get_double(ps, "DensityContrastLimit");
         All.MaxNumNgbDeviation = param_get_double(ps, "MaxNumNgbDeviation");
         All.IO.BytesPerFile = param_get_int(ps, "BytesPerFile");
         All.IO.UsePeculiarVelocity = 0; /* Will be set by the Initial Condition File */
         All.IO.NumWriters = param_get_int(ps, "NumWriters");
         All.IO.MinNumWriters = param_get_int(ps, "MinNumWriters");
         All.IO.WritersPerFile = param_get_int(ps, "WritersPerFile");
         All.IO.AggregatedIOThreshold = param_get_int(ps, "AggregatedIOThreshold");
         All.IO.EnableAggregatedIO = param_get_int(ps, "EnableAggregatedIO");
         All.MakeGlassFile = param_get_int(ps, "MakeGlassFile");
         All.CoolingOn = param_get_int(ps, "CoolingOn");
         All.UVRedshiftThreshold = param_get_double(ps, "UVRedshiftThreshold");
         All.HydroOn = param_get_int(ps, "HydroOn");
         All.DensityOn = param_get_int(ps, "DensityOn");
         All.TreeGravOn = param_get_int(ps, "TreeGravOn");
         All.FastParticleType = param_get_int(ps, "FastParticleType");
         All.TimeLimitCPU = param_get_double(ps, "TimeLimitCPU");
         All.AutoSnapshotTime = param_get_double(ps, "AutoSnapshotTime");
         All.GravitySoftening = param_get_double(ps, "GravitySoftening");
         All.GravitySofteningGas = param_get_double(ps, "GravitySofteningGas");
         All.BufferSize = param_get_double(ps, "BufferSize");
         All.PartAllocFactor = param_get_double(ps, "PartAllocFactor");
         All.TopNodeAllocFactor = param_get_double(ps, "TopNodeAllocFactor");
         All.InitGasTemp = param_get_double(ps, "InitGasTemp");
         All.MinGasTemp = param_get_double(ps, "MinGasTemp");
         All.SnapshotWithFOF = param_get_int(ps, "SnapshotWithFOF");
         All.FOFSaveParticles = param_get_int(ps, "FOFSaveParticles");
         All.FOFHaloLinkingLength = param_get_double(ps, "FOFHaloLinkingLength");
         All.FOFHaloMinLength = param_get_int(ps, "FOFHaloMinLength");
         All.MinFoFMassForNewSeed = param_get_double(ps, "MinFoFMassForNewSeed");
         All.TimeBetweenSeedingSearch = param_get_double(ps, "TimeBetweenSeedingSearch");
         All.BlackHoleOn = param_get_int(ps, "BlackHoleOn");
     #ifdef BLACK_HOLES
         All.BlackHoleSoundSpeedFromPressure = 0;
         All.BlackHoleAccretionFactor = param_get_double(ps, "BlackHoleAccretionFactor");
         All.BlackHoleEddingtonFactor = param_get_double(ps, "BlackHoleEddingtonFactor");
         All.SeedBlackHoleMass = param_get_double(ps, "SeedBlackHoleMass");
         All.BlackHoleNgbFactor = param_get_double(ps, "BlackHoleNgbFactor");
         All.BlackHoleMaxAccretionRadius = param_get_double(ps, "BlackHoleMaxAccretionRadius");
         All.BlackHoleFeedbackFactor = param_get_double(ps, "BlackHoleFeedbackFactor");
         All.BlackHoleFeedbackRadius = param_get_double(ps, "BlackHoleFeedbackRadius");
         All.BlackHoleFeedbackRadiusMaxPhys = param_get_double(ps, "BlackHoleFeedbackRadiusMaxPhys");
         All.BlackHoleFeedbackMethod = param_get_enum(ps, "BlackHoleFeedbackMethod");
     #endif
         All.StarformationOn = param_get_int(ps, "StarformationOn");
         All.WindOn = param_get_int(ps, "WindOn");
     #ifdef SFR
         All.StarformationCriterion = param_get_enum(ps, "StarformationCriterion");
         All.CritOverDensity = param_get_double(ps, "CritOverDensity");
         All.CritPhysDensity = param_get_double(ps, "CritPhysDensity");
         All.FactorSN = param_get_double(ps, "FactorSN");
         All.FactorEVP = param_get_double(ps, "FactorEVP");
         All.TempSupernova = param_get_double(ps, "TempSupernova");
         All.TempClouds = param_get_double(ps, "TempClouds");
         All.MaxSfrTimescale = param_get_double(ps, "MaxSfrTimescale");
         All.WindModel = param_get_enum(ps, "WindModel");
         /* The following two are for VS08 and SH03*/
         All.WindEfficiency = param_get_double(ps, "WindEfficiency");
         All.WindEnergyFraction = param_get_double(ps, "WindEnergyFraction");
         /* The following two are for OFJT10*/
         All.WindSigma0 = param_get_double(ps, "WindSigma0");
         All.WindSpeedFactor = param_get_double(ps, "WindSpeedFactor");
         All.WindFreeTravelLength = param_get_double(ps, "WindFreeTravelLength");
         All.WindFreeTravelDensFac = param_get_double(ps, "WindFreeTravelDensFac");
         All.QuickLymanAlphaProbability = param_get_double(ps, "QuickLymanAlphaProbability");
         All.HeliumHeatOn = param_get_int(ps, "HeliumHeatOn");
         All.HeliumHeatThresh = param_get_double(ps, "HeliumHeatThresh");
         All.HeliumHeatAmp = param_get_double(ps, "HeliumHeatAmp");
         All.HeliumHeatExp = param_get_double(ps, "HeliumHeatExp");
     #endif
         /*Massive neutrino parameters*/
         All.MassiveNuLinRespOn = param_get_int(ps, "MassiveNuLinRespOn");
         All.HybridNeutrinosOn = param_get_int(ps, "HybridNeutrinosOn");
         param_get_string2(ps, "LinearTransferFunction", All.CAMBTransferFunction);
         All.CAMBInputSpectrum_UnitLength_in_cm = param_get_double(ps, "InputSpectrum_UnitLength_in_cm");
         All.CP.MNu[0] = param_get_double(ps, "MNue");
         All.CP.MNu[1] = param_get_double(ps, "MNum");
         All.CP.MNu[2] = param_get_double(ps, "MNut");
         All.HybridVcrit = param_get_double(ps, "Vcrit");
         All.HybridNuPartTime = param_get_double(ps, "NuPartTime");
         if(All.MassiveNuLinRespOn && !All.CP.RadiationOn)
             endrun(2, "You have enabled (kspace) massive neutrinos without radiation, but this will give an inconsistent cosmology!\n");
         /*End massive neutrino parameters*/
         parameter_set_free(ps);
     #ifndef BLACK_HOLES
         if(All.BlackHoleOn)
         {
             endrun(1, "Code was compiled with black holes switched off but BlackHoleOn = 1. This does not work!\n");
         }
     #endif
     #ifdef SFR
         if(All.StarformationOn == 0)
         {
             message(1, "StarformationOn is disabled!\n");
         } else {
             if(All.CoolingOn == 0)
             {
                 endrun(1, "You try to use the code with star formation enabled,\n"
                           "but you did not switch on cooling.\nThis mode is not supported.\n");
             }
         }
         if(All.WindOn == 1) {
             if(All.StarformationOn == 0) {
                 endrun(1, "You try to use the code with wind enabled,\n"
                           "but you did not switch on starformation.\nThis mode is not supported.\n");
             }
         }
     #else
         if(All.StarformationOn == 1)
         {
             endrun(1, "Code was compiled with star formation switched off.\n"
                       "You must set `StarformationOn=0', or recompile the code.\n");
             All.StarformationOn = 0;
         }
     #endif
         DensityKernel kernel;
         density_kernel_init(&kernel, 1.0);
         All.DesNumNgb = density_kernel_desnumngb(&kernel, All.DensityResolutionEta);
         message(1, "The Density Kernel type is %s\n", kernel.name);
         message(1, "The Density resolution is %g * mean separation, or %d neighbours\n",
                     All.DensityResolutionEta, All.DesNumNgb);
     }
     MPI_Bcast(&All, sizeof(All), MPI_BYTE, 0, MPI_COMM_WORLD);
 }