MP-Gadget: libgadget/partmanager.h File Reference
partmanager.h File Reference
#include "types.h"
#include "utils/peano.h"
Classes
struct particle_data
struct part_manager_type
Macros
#define P PartManager->Base
#define NEAREST(x, BoxSize) (((x)>0.5*BoxSize)?((x)-BoxSize):(((x)<-0.5*BoxSize)?((x)+BoxSize):(x)))
Functions
void particle_alloc_memory (struct part_manager_type *PartManager, double BoxSize, int64_t MaxPart)
void update_random_offset (struct part_manager_type *PartManager, double *rel_random_shift, double RandomParticleOffset)
static double DMAX (double a, double b)
static double DMIN (double a, double b)
static int IMAX (int a, int b)
static int IMIN (int a, int b)
Variables
struct part_manager_type PartManager [1]
Macro Definition Documentation
NEAREST
#define NEAREST (x, BoxSize) (((x)>0.5*BoxSize)?((x)-BoxSize):(((x)<-0.5*BoxSize)?((x)+BoxSize):(x)))
Definition at line 99 of file partmanager.h.
P
#define P PartManager->Base
Definition at line 88 of file partmanager.h.
Function Documentation
DMAX()
static double DMAX (double a, double b) inline static
Definition at line 101 of file partmanager.h.
{
     if(a > b) return a;
     return b;
 }
DMIN()
static double DMIN (double a, double b) inline static
Definition at line 105 of file partmanager.h.
{
     if(a < b) return a;
     return b;
 }
IMAX()
static int IMAX (int a, int b) inline static
Definition at line 109 of file partmanager.h.
{
     if(a > b) return a;
     return b;
 }
IMIN()
static int IMIN (int a, int b) inline static
Definition at line 113 of file partmanager.h.
{
     if(a < b) return a;
     return b;
 }
particle_alloc_memory()
void particle_alloc_memory (struct part_manager_type * PartManager, double BoxSize, int64_t MaxPart)
Definition at line 14 of file partmanager.c.
 {
     size_t bytes;
     PartManager->Base = (struct particle_data *) mymalloc("P", bytes = MaxPart * sizeof(struct particle_data));
     PartManager->MaxPart = MaxPart;
     PartManager->NumPart = 0;
     if(MaxPart >= 1L<<31 || MaxPart < 0)
         endrun(5, "Trying to store %ld particles on a single node, more than fit in an int32, not supported\n", MaxPart);
     memset(PartManager->CurrentParticleOffset, 0, 3*sizeof(double));
     PartManager->BoxSize = BoxSize;
     /* clear the memory to avoid valgrind errors;
      *
      * note that I tried to set each component in P to zero but
      * valgrind still complains in PFFT
      * seems to be to do with how the struct is padded and
      * the missing holes being accessed by __kmp_atomic functions.
      * (memory lock etc?)
      * */
     memset(PartManager->Base, 0, sizeof(struct particle_data) * MaxPart);
     message(0, "Allocated %g MByte for storing %ld particles.\n", bytes / (1024.0 * 1024.0), MaxPart);
 }
References part_manager_type::Base, part_manager_type::BoxSize, part_manager_type::CurrentParticleOffset, endrun(), part_manager_type::MaxPart, message(), mymalloc, part_manager_type::NumPart, and PartManager.
Referenced by init_alloc_particle_slot_memory(), setup_density(), and setup_particles().
update_random_offset()
void update_random_offset (struct part_manager_type * PartManager, double * rel_random_shift, double RandomParticleOffset)
Definition at line 43 of file partmanager.c.
 {
     int i;
     for (i = 0; i < 3; i++) {
         /* Note random number table is duplicated across processors*/
         double rr = get_random_number(i);
         /* Upstream Gadget uses a random fraction of the box, but since all we need
          * is to adjust the tree openings, and the tree force is zero anyway on the
          * scale of a few PM grid cells, this seems enough.*/
         rr *= RandomParticleOffset * PartManager->BoxSize;
         /* Subtract the old random shift first.*/
         rel_random_shift[i] = rr - PartManager->CurrentParticleOffset[i];
         PartManager->CurrentParticleOffset[i] = rr;
     }
     message(0, "Internal particle offset is now %g %g %g\n", PartManager->CurrentParticleOffset[0], PartManager->CurrentParticleOffset[1], PartManager->CurrentParticleOffset[2]);
 #ifdef DEBUG
     /* Check explicitly that the vector is the same on all processors*/
     double test_random_shift[3] = {0};
     for (i = 0; i < 3; i++)
         test_random_shift[i] = PartManager->CurrentParticleOffset[i];
     MPI_Bcast(test_random_shift, 3, MPI_DOUBLE, 0, MPI_COMM_WORLD);
     for (i = 0; i < 3; i++)
         if(test_random_shift[i] != PartManager->CurrentParticleOffset[i])
             endrun(44, "Random shift %d is %g != %g on task 0!\n", i, test_random_shift[i], PartManager->CurrentParticleOffset[i]);
 #endif
 }
References part_manager_type::BoxSize, part_manager_type::CurrentParticleOffset, endrun(), get_random_number(), message(), and PartManager.
Referenced by run().
Variable Documentation
PartManager
struct part_manager_type PartManager[1]