MP-Gadget: petaio.c File Reference
petaio.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include "bigfile-mpi.h"
#include "allvars.h"
#include "proto.h"
#include "system.h"
#include "sfr_eff.h"
#include "cooling.h"
#include "timestep.h"
#include "petaio.h"
#include "slotsmanager.h"
#include "partmanager.h"
#include "mymalloc.h"
#include "openmpsort.h"
#include "utils-string.h"
#include "endrun.h"
#include "config.h"
#include "kspace-neutrinos/delta_tot_table.h"
Functions
void fof_register_io_blocks ()
static void petaio_write_header (BigFile *bf, const int64_t *NTotal)
static void petaio_read_header_internal (BigFile *bf)
static void register_io_blocks ()
void petaio_init ()
static void petaio_save_internal (char *fname)
void petaio_save_snapshot (const char *fmt,...)
void petaio_build_selection (int *selection, int *ptype_offset, int *ptype_count, const int NumPart, int(*select_func)(int i))
void petaio_save_neutrinos (BigFile *bf)
void petaio_read_neutrinos (BigFile *bf)
void petaio_read_internal (char *fname, int ic)
void petaio_read_header (int num)
void petaio_read_snapshot (int num)
static double _get_attr_double (BigBlock *bh, char *name, double def)
static int _get_attr_int (BigBlock *bh, char *name, int def)
void petaio_alloc_buffer (BigArray *array, IOTableEntry *ent, int64_t localsize)
void petaio_readout_buffer (BigArray *array, IOTableEntry *ent)
void petaio_build_buffer (BigArray *array, IOTableEntry *ent, const int *selection, const int NumSelection)
void petaio_destroy_buffer (BigArray *array)
int petaio_read_block (BigFile *bf, char *blockname, BigArray *array, int required)
void petaio_save_block (BigFile *bf, char *blockname, BigArray *array)
void io_register_io_block (char *name, char *dtype, int items, int ptype, property_getter getter, property_setter setter, int required)
static void GTVelocity (int i, float *out)
static void STVelocity (int i, float *out)
static void GTNeutralHydrogenFraction (int i, float *out)
static void GTInternalEnergy (int i, float *out)
static void GTJUV (int i, float *out)
static int order_by_type (const void *a, const void *b)
Variables
struct IOTable IOTable = {0}
_delta_tot_table delta_tot_table
Function Documentation
_get_attr_double()
static double _get_attr_double (BigBlock * bh, char * name, double def) static
Definition at line 519 of file petaio.c.
Referenced by petaio_read_header_internal().
 {
     double foo;
     if(0 != big_block_get_attr(bh, name, &foo, "f8", 1)) {
         foo = def;
     }
     return foo;
 }
_get_attr_int()
static int _get_attr_int (BigBlock * bh, char * name, int def) static
Definition at line 528 of file petaio.c.
Referenced by petaio_read_header_internal().
 {
     int foo;
     if(0 != big_block_get_attr(bh, name, &foo, "i4", 1)) {
         foo = def;
     }
     return foo;
 }
fof_register_io_blocks()
void fof_register_io_blocks ()
Definition at line 311 of file fofpetaio.c.
References IO_REG, IO_REG_WRONLY, and PTYPE_FOF_GROUP.
Referenced by register_io_blocks().
{
     IO_REG(GroupID, "u4", 1, PTYPE_FOF_GROUP);
     IO_REG(Mass, "f4", 1, PTYPE_FOF_GROUP);
     IO_REG(MassCenterPosition, "f8", 3, PTYPE_FOF_GROUP);
     IO_REG(FirstPos, "f4", 3, PTYPE_FOF_GROUP);
     IO_REG(MinID, "u8", 1, PTYPE_FOF_GROUP);
     IO_REG(Imom, "f4", 9, PTYPE_FOF_GROUP);
     IO_REG(Jmom, "f4", 3, PTYPE_FOF_GROUP);
     IO_REG_WRONLY(MassCenterVelocity, "f4", 3, PTYPE_FOF_GROUP);
     IO_REG(LengthByType, "u4", 6, PTYPE_FOF_GROUP);
     IO_REG(MassByType, "f4", 6, PTYPE_FOF_GROUP);
 #ifdef SFR
     IO_REG(StarFormationRate, "f4", 1, PTYPE_FOF_GROUP);
 #endif
 #ifdef BLACK_HOLES
     IO_REG(BlackholeMass, "f4", 1, PTYPE_FOF_GROUP);
     IO_REG(BlackholeAccretionRate, "f4", 1, PTYPE_FOF_GROUP);
 #endif
 }
GTInternalEnergy()
static void GTInternalEnergy (int i, float * out) static
Definition at line 869 of file petaio.c.
References global_data_all_processes::a3inv, All, global_data_all_processes::cf, DMAX(), EOMDensity, GAMMA_MINUS1, global_data_all_processes::MinEgySpec, and SPHP.
{
     *out = DMAX(All.MinEgySpec,
         SPHP(i).Entropy / GAMMA_MINUS1 * pow(SPHP(i).EOMDensity * All.cf.a3inv, GAMMA_MINUS1));
 }
GTJUV()
static void GTJUV (int i, float * out) static
Definition at line 874 of file petaio.c.
References GetParticleUVBG(), and UVBG::J_UV.
{
     struct UVBG uvbg;
     GetParticleUVBG(i, &uvbg);
     *out = uvbg.J_UV;
 }
GTNeutralHydrogenFraction()
static void GTNeutralHydrogenFraction (int i, float * out) static
Definition at line 856 of file petaio.c.
References global_data_all_processes::a3inv, AbundanceRatios(), All, global_data_all_processes::cf, DMAX(), EOMDensity, GAMMA_MINUS1, GetParticleUVBG(), global_data_all_processes::MinEgySpec, ne, and SPHP.
{
     double ne, nh0, nHeII;
     ne = SPHP(i).Ne;
     struct UVBG uvbg;
     GetParticleUVBG(i, &uvbg);
     AbundanceRatios(DMAX(All.MinEgySpec,
                 SPHP(i).Entropy / GAMMA_MINUS1 * pow(SPHP(i).EOMDensity *
                     All.cf.a3inv,
                     GAMMA_MINUS1)),
             SPHP(i).Density * All.cf.a3inv, &uvbg, &ne, &nh0, &nHeII);
     *out = nh0;
 }
GTVelocity()
static void GTVelocity (int i, float * out) static
Definition at line 796 of file petaio.c.
References global_data_all_processes::a, All, global_data_all_processes::cf, global_data_all_processes::IO, P, and global_data_all_processes::UsePeculiarVelocity.
{
     /* Convert to Peculiar Velocity if UsePeculiarVelocity is set */
     double fac;
     if (All.IO.UsePeculiarVelocity) {
         fac = 1.0 / All.cf.a;
     } else {
         fac = 1.0;
     }
     int d;
     for(d = 0; d < 3; d ++) {
         out[d] = fac * P[i].Vel[d];
     }
 }
io_register_io_block()
void io_register_io_block (char * name, char * dtype, int items, int ptype, property_getter getter, property_setter setter, int required)
Definition at line 776 of file petaio.c.
References IOTableEntry::dtype, IOTable::ent, IOTableEntry::getter, IOTableEntry::items, IOTableEntry::name, P, IOTableEntry::ptype, IOTableEntry::required, IOTableEntry::setter, SIMPLE_PROPERTY, and IOTable::used.
           {
     IOTableEntry * ent = &IOTable.ent[IOTable.used];
     strcpy(ent->name, name);
     ent->ptype = ptype;
     dtype_normalize(ent->dtype, dtype);
     ent->getter = getter;
     ent->setter = setter;
     ent->items = items;
     ent->required = required;
     IOTable.used ++;
 }
order_by_type()
static int order_by_type (const void * a, const void * b) static
Definition at line 880 of file petaio.c.
References IOTableEntry::ptype.
Referenced by register_io_blocks().
 {
     const struct IOTableEntry * pa  = (const struct IOTableEntry *) a;
     const struct IOTableEntry * pb  = (const struct IOTableEntry *) b;
     if(pa->ptype < pb->ptype)
         return -1;
     if(pa->ptype > pb->ptype)
         return +1;
     return 0;
 }
petaio_alloc_buffer()
void petaio_alloc_buffer (BigArray * array, IOTableEntry * ent, int64_t localsize)
Definition at line 609 of file petaio.c.
References IOTableEntry::dtype, IOTableEntry::items, and mymalloc.
Referenced by build_buffer_fof(), petaio_build_buffer(), and petaio_read_internal().
{
     size_t dims[2];
     ptrdiff_t strides[2];
     int elsize = dtype_itemsize(ent->dtype);
     dims[0] = localsize;
     dims[1] = ent->items;
     strides[1] = elsize;
     strides[0] = elsize * ent->items;
     char * buffer = mymalloc("IOBUFFER", dims[0] * dims[1] * elsize);
     big_array_init(array, buffer, ent->dtype, 2, dims, strides);
 }
petaio_build_buffer()
void petaio_build_buffer (BigArray * array, IOTableEntry * ent, const int * selection, const int NumSelection)
Definition at line 639 of file petaio.c.
References endrun(), IOTableEntry::getter, omp_get_thread_num, P, petaio_alloc_buffer(), and IOTableEntry::ptype.
Referenced by fof_save_particles(), and petaio_save_internal().
 {
     if(selection == NULL) {
         endrun(-1, "NULL selection is not supported\n");
     }
     /* don't forget to free buffer after its done*/
     petaio_alloc_buffer(array, ent, NumSelection);
     /* Fast code path if there are no such particles */
     if(NumSelection == 0) {
         return;
     }
 #pragma omp parallel
     {
         int i;
         const int tid = omp_get_thread_num();
         const int NT = omp_get_num_threads();
         const int start = NumSelection * (size_t) tid / NT;
         const int end = NumSelection * ((size_t) tid + 1) / NT;
         /* fill the buffer */
         char * p = array->data;
         p += array->strides[0] * start;
         for(i = start; i < end; i ++) {
             const int j = selection[i];
             if(P[j].Type != ent->ptype) {
                 endrun(2, "Selection %d has type = %d != %d\n", j, P[j].Type, ent->ptype);
             }
             ent->getter(j, p);
             p += array->strides[0];
         }
     }
 }
petaio_build_selection()
void petaio_build_selection (int * selection, int * ptype_offset, int * ptype_count, const int NumPart, int(*)(int i) select_func)
Create a Selection array for the buffers. This array indirectly sort the particles by the type.
The offset for the starting of each type is stored in ptype_offset.
if select_func is provided, it shall return 1 for those that shall be included in the output.
Definition at line 98 of file petaio.c.
References delta_tot_table, and P.
Referenced by fof_save_particles(), and petaio_save_internal().
 {
     int i;
     ptype_offset[0] = 0;
     ptype_count[0] = 0;
     for(i = 0; i < NumPart; i ++) {
         if((select_func == NULL) || (select_func(i) != 0)) {
             int ptype = P[i].Type;
             ptype_count[ptype] ++;
         }
     }
     for(i = 1; i < 6; i ++) {
         ptype_offset[i] = ptype_offset[i-1] + ptype_count[i-1];
         ptype_count[i-1] = 0;
     }
     ptype_count[5] = 0;
     for(i = 0; i < NumPart; i ++) {
         int ptype = P[i].Type;
         if((select_func == NULL) || (select_func(i) != 0)) {
             selection[ptype_offset[ptype] + ptype_count[ptype]] = i;
             ptype_count[ptype]++;
         }
     }
 }
petaio_destroy_buffer()
void petaio_destroy_buffer (BigArray * array)
Definition at line 675 of file petaio.c.
References myfree.
Referenced by fof_save_particles(), petaio_read_internal(), and petaio_save_internal().
{
     myfree(array->data);
 }
petaio_init()
void petaio_init ()
Definition at line 45 of file petaio.c.
References global_data_all_processes::AggregatedIOThreshold, All, global_data_all_processes::EnableAggregatedIO, global_data_all_processes::IO, message(), petaio_save_internal(), and register_io_blocks().
Referenced by begrun().
                    {
     /* Smaller files will do aggregareted IO.*/
     if(All.IO.EnableAggregatedIO) {
         message(0, "Aggregated IO is enabled\n");
         big_file_mpi_set_aggregated_threshold(All.IO.AggregatedIOThreshold);
     } else {
         message(0, "Aggregated IO is disabled.\n");
         big_file_mpi_set_aggregated_threshold(0);
     }
     register_io_blocks();
 }
petaio_read_block()
int petaio_read_block (BigFile * bf, char * blockname, BigArray * array, int required)
Definition at line 680 of file petaio.c.
References All, endrun(), global_data_all_processes::IO, and global_data_all_processes::NumWriters.
Referenced by petaio_read_internal(), and petaio_read_neutrinos().
{
     BigBlock bb;
     BigBlockPtr ptr;
     /* open the block */
     if(0 != big_file_mpi_open_block(bf, &bb, blockname, MPI_COMM_WORLD)) {
         if(required)
             endrun(0, "Failed to open block at %s:%s\n", blockname, big_file_get_error_message());
         else
             return 1;
     }
     if(0 != big_block_seek(&bb, &ptr, 0)) {
             endrun(1, "Failed to seek block %s: %s\n", blockname, big_file_get_error_message());
     }
     if(0 != big_block_mpi_read(&bb, &ptr, array, All.IO.NumWriters, MPI_COMM_WORLD)) {
         endrun(1, "Failed to read from block %s: %s\n", blockname, big_file_get_error_message());
     }
     if(0 != big_block_mpi_close(&bb, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block at %s:%s\n", blockname,
                     big_file_get_error_message());
     }
     return 0;
 }
petaio_read_header()
void petaio_read_header (int num)
Definition at line 405 of file petaio.c.
References All, endrun(), fastpm_strdup_printf(), global_data_all_processes::InitCondFile, message(), global_data_all_processes::OutputDir, petaio_read_header_internal(), and global_data_all_processes::SnapshotFileBase.
Referenced by begrun().
 {
     BigFile bf = {0};
     char * fname;
     if(num == -1) {
         fname = fastpm_strdup_printf("%s", All.InitCondFile);
     } else {
         fname = fastpm_strdup_printf("%s/%s_%03d", All.OutputDir, All.SnapshotFileBase, num);
     }
     message(0, "Probing Header of snapshot file: %s\n", fname);
     if(0 != big_file_mpi_open(&bf, fname, MPI_COMM_WORLD)) {
         endrun(0, "Failed to open snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     petaio_read_header_internal(&bf);
     if(0 != big_file_mpi_close(&bf, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     free(fname);
 }
petaio_read_header_internal()
static void petaio_read_header_internal (BigFile * bf) static
Definition at line 538 of file petaio.c.
References _get_attr_double(), _get_attr_int(), All, global_data_all_processes::BoxSize, endrun(), global_data_all_processes::IO, global_data_all_processes::MassTable, global_data_all_processes::MeanSeparation, message(), global_data_all_processes::NTotalInit, Time, global_data_all_processes::TimeIC, global_data_all_processes::TimeInit, global_data_all_processes::TotNumPartInit, global_data_all_processes::UnitLength_in_cm, global_data_all_processes::UnitMass_in_g, global_data_all_processes::UnitVelocity_in_cm_per_s, and global_data_all_processes::UsePeculiarVelocity.
Referenced by petaio_read_header().
{
     BigBlock bh = {0};
     if(0 != big_file_mpi_open_block(bf, &bh, "Header", MPI_COMM_WORLD)) {
         endrun(0, "Failed to create block at %s:%s\n", "Header",
                     big_file_get_error_message());
     }
     double Time;
     int ptype;
     int64_t NTotal[6];
     if(
     (0 != big_block_get_attr(&bh, "TotNumPart", NTotal, "u8", 6)) ||
     (0 != big_block_get_attr(&bh, "MassTable", All.MassTable, "f8", 6)) ||
     (0 != big_block_get_attr(&bh, "BoxSize", &All.BoxSize, "f8", 1)) ||
     (0 != big_block_get_attr(&bh, "Time", &Time, "f8", 1))
     ) {
         endrun(0, "Failed to read attr: %s\n",
                     big_file_get_error_message());
     }
     All.TimeInit = Time;
     if(0!= big_block_get_attr(&bh, "TimeIC", &All.TimeIC, "f8", 1))
         All.TimeIC = Time;
     /* fall back to traditional MP-Gadget Units if not given in the snapshot file. */
     All.UnitVelocity_in_cm_per_s = _get_attr_double(&bh, "UnitVelocity_in_cm_per_s", 1e5); /* 1 km/sec */
     All.UnitLength_in_cm = _get_attr_double(&bh, "UnitLength_in_cm",  3.085678e21); /* 1.0 Kpc /h */
     All.UnitMass_in_g = _get_attr_double(&bh, "UnitMass_in_g", 1.989e43); /* 1e10 Msun/h */
     /* Fall back to use a**2 * dx/dt if UsePeculiarVelocity is not set in IC */
     All.IO.UsePeculiarVelocity = _get_attr_int(&bh, "UsePeculiarVelocity", 0);
     if(0 != big_block_get_attr(&bh, "TotNumPartInit", All.NTotalInit, "u8", 6)) {
         int ptype;
         for(ptype = 0; ptype < 6; ptype ++) {
             All.NTotalInit[ptype] = NTotal[ptype];
         }
     }
     int64_t TotNumPart = 0;
     All.TotNumPartInit = 0;
     for(ptype = 0; ptype < 6; ptype ++) {
         TotNumPart += NTotal[ptype];
         All.TotNumPartInit += All.NTotalInit[ptype];
         if(All.NTotalInit[ptype] > 0) {
             All.MeanSeparation[ptype] = All.BoxSize / pow(All.NTotalInit[ptype], 1.0 / 3);
         } else {
             All.MeanSeparation[ptype] = 0;
         }
     }
     message(0, "Total number of particles: %018ld\n", TotNumPart);
     const char * PARTICLE_TYPE_NAMES [] = {"Gas", "DarkMatter", "Neutrino", "Unknown", "Star", "BlackHole"};
     for(ptype = 0; ptype < 6; ptype ++) {
         message(0, "% 11s: Total: %018ld Init: %018ld Mean-Sep %g \n",
                 PARTICLE_TYPE_NAMES[ptype], NTotal[ptype], All.NTotalInit[ptype], All.MeanSeparation[ptype]);
     }
     /*FIXME: check others as well */
     /*
     big_block_get_attr(&bh, "OmegaLambda", &All.OmegaLambda, "f8", 1);
     big_block_get_attr(&bh, "Omega0", &All.Omega0, "f8", 1);
     big_block_get_attr(&bh, "HubbleParam", &All.HubbleParam, "f8", 1);
     */
     if(0 != big_block_mpi_close(&bh, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block: %s\n",
                     big_file_get_error_message());
     }
 }
petaio_read_internal()
void petaio_read_internal (char * fname, int ic)
Definition at line 278 of file petaio.c.
References All, endrun(), IOTable::ent, global_data_all_processes::MassiveNuLinRespOn, part_manager_type::MaxPart, message(), IOTableEntry::name, NTask, part_manager_type::NumPart, P, global_data_all_processes::PartAllocFactor, particle_alloc_memory(), PartManager, petaio_alloc_buffer(), petaio_destroy_buffer(), petaio_read_block(), petaio_read_neutrinos(), petaio_readout_buffer(), IOTableEntry::ptype, IOTableEntry::required, IOTableEntry::setter, slots_reserve(), slots_setup_id(), slots_setup_topology(), ThisTask, timestep_allocate_memory(), global_data_all_processes::TotNumPartInit, and IOTable::used.
Referenced by petaio_read_snapshot().
{
     int ptype;
     int i;
     BigFile bf = {0};
     BigBlock bh = {0};
     message(0, "Reading snapshot %s\n", fname);
     if(0 != big_file_mpi_open(&bf, fname, MPI_COMM_WORLD)) {
         endrun(0, "Failed to open snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     int64_t NTotal[6];
     if(0 != big_file_mpi_open_block(&bf, &bh, "Header", MPI_COMM_WORLD)) {
         endrun(0, "Failed to create block at %s:%s\n", "Header",
                     big_file_get_error_message());
     }
     if ((0 != big_block_get_attr(&bh, "TotNumPart", NTotal, "u8", 6)) ||
         (0 != big_block_mpi_close(&bh, MPI_COMM_WORLD))) {
         endrun(0, "Failed to close block: %s\n",
                     big_file_get_error_message());
     }
     /* sets the maximum number of particles that may reside on a processor */
     int MaxPart = (int) (All.PartAllocFactor * All.TotNumPartInit / NTask);
     /*Allocates ActiveParticle array*/
     timestep_allocate_memory(MaxPart);
     /*Allocate the particle memory*/
     particle_alloc_memory(MaxPart);
     int NLocal[6];
     for(ptype = 0; ptype < 6; ptype ++) {
         int64_t start = ThisTask * NTotal[ptype] / NTask;
         int64_t end = (ThisTask + 1) * NTotal[ptype] / NTask;
         NLocal[ptype] = end - start;
         PartManager->NumPart += NLocal[ptype];
     }
     /* Allocate enough memory for stars and black holes.
      * This will be dynamically increased as needed.*/
     if(PartManager->NumPart >= PartManager->MaxPart) {
         endrun(1, "Overwhelmed by part: %d > %d\n", PartManager->NumPart, PartManager->MaxPart);
     }
     int newSlots[6];
     for(ptype = 0; ptype < 6; ptype++) {
         /* initialize MaxSlots to zero, such that grow don't fail. */
         newSlots[ptype] = 0;
         if(NLocal[ptype] > 0) {
             newSlots[ptype] = All.PartAllocFactor * NLocal[ptype];
         }
     }
     /* Now allocate memory for the secondary particle data arrays.
      * This may be dynamically resized later!*/
     /*Ensure all processors have initially the same number of particle slots*/
     MPI_Allreduce(MPI_IN_PLACE, newSlots, 6, MPI_INT, MPI_MAX, MPI_COMM_WORLD);
     slots_reserve(0, newSlots);
     /* initialize particle types */
     int offset = 0;
     for(ptype = 0; ptype < 6; ptype ++) {
         for(i = 0; i < NLocal[ptype]; i++)
         {
             int j = offset + i;
             P[j].Type = ptype;
         }
         offset += NLocal[ptype];
     }
     /* so we can set up the memory topology of secondary slots */
     slots_setup_topology();
     for(i = 0; i < IOTable.used; i ++) {
         /* only process the particle blocks */
         char blockname[128];
         int ptype = IOTable.ent[i].ptype;
         BigArray array = {0};
         if(!(ptype < 6 && ptype >= 0)) {
             continue;
         }
         if(NTotal[ptype] == 0) continue;
         if(ic) {
             /* for IC read in only three blocks */
             int keep = 0;
             keep |= (0 == strcmp(IOTable.ent[i].name, "Position"));
             keep |= (0 == strcmp(IOTable.ent[i].name, "Velocity"));
             keep |= (0 == strcmp(IOTable.ent[i].name, "ID"));
             if (ptype == 5) {
                 keep |= (0 == strcmp(IOTable.ent[i].name, "Mass"));
                 keep |= (0 == strcmp(IOTable.ent[i].name, "BlackholeMass"));
                 keep |= (0 == strcmp(IOTable.ent[i].name, "MinPotPos"));
                 keep |= (0 == strcmp(IOTable.ent[i].name, "MinPotVel"));
             }
             if(!keep) continue;
         }
         if(IOTable.ent[i].setter == NULL) {
             /* FIXME: do not know how to read this block; assume the fucker is
              * internally intialized; */
             continue;
         }
         sprintf(blockname, "%d/%s", ptype, IOTable.ent[i].name);
         petaio_alloc_buffer(&array, &IOTable.ent[i], NLocal[ptype]);
         if(0 == petaio_read_block(&bf, blockname, &array, IOTable.ent[i].required))
             petaio_readout_buffer(&array, &IOTable.ent[i]);
         petaio_destroy_buffer(&array);
     }
     /*Read neutrinos from the snapshot if necessary*/
     if((!ic) && All.MassiveNuLinRespOn)
         petaio_read_neutrinos(&bf);
     if(0 != big_file_mpi_close(&bf, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     /* now we have IDs, set up the ID consistency between slots. */
     slots_setup_id();
 }
petaio_read_neutrinos()
void petaio_read_neutrinos (BigFile * bf)
Definition at line 178 of file petaio.c.
References delta_tot_table, endrun(), myfree, mymalloc, petaio_read_block(), and ThisTask.
Referenced by petaio_read_internal().
 {
 #pragma omp master
     {
     size_t nk, ia, ik, i;
     BigBlock bn = {0};
     if(0 != big_file_mpi_open_block(bf, &bn, "Neutrino", MPI_COMM_WORLD)) {
         endrun(0, "Failed to open block at %s:%s\n", "Neutrino",
                     big_file_get_error_message());
     }
     if(
     (0 != big_block_get_attr(&bn, "Nscale", &ia, "u8", 1)) ||
     (0 != big_block_get_attr(&bn, "Nkval", &nk, "u8", 1))) {
         endrun(0, "Failed to read attr: %s\n",
                     big_file_get_error_message());
     }
     double *delta_tot = (double *) mymalloc("tmp_nusave",ia*nk*sizeof(double));
     /*Allocate list of scale factors, and space for delta_tot, in one operation.*/
     if(0 != big_block_get_attr(&bn, "scalefact", delta_tot_table.scalefact, "f8", ia))
         endrun(0, "Failed to read attr: %s\n", big_file_get_error_message());
     if(0 != big_block_mpi_close(&bn, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block %s\n",
                     big_file_get_error_message());
     }
     BigArray deltas = {0};
     size_t dims[2] = {0, ia};
     ptrdiff_t strides[2] = {8*ia, 8};
     /*The neutrino state is shared between all processors,
      *so only read on master task and broadcast*/
     if(ThisTask == 0) {
         dims[0] = nk;
     }
     big_array_init(&deltas, delta_tot, "=f8", 2, dims, strides);
     petaio_read_block(bf, "Neutrino/Deltas", &deltas, 1);
     /*Save a flat memory block*/
     for(ik=0;ik<nk;ik++)
         for(i=0;i<ia;i++)
             delta_tot_table.delta_tot[ik][i] = delta_tot[ik*ia+i];
     delta_tot_table.nk = nk;
     delta_tot_table.ia = ia;
     myfree(delta_tot);
     /*Broadcast the arrays.*/
     MPI_Bcast(&(delta_tot_table.ia), 1,MPI_INT,0,MPI_COMM_WORLD);
     if(delta_tot_table.ia > 0) {
         MPI_Bcast(&(delta_tot_table.nk), 1,MPI_INT,0,MPI_COMM_WORLD);
         /*Broadcast data for scalefact and delta_tot, Delta_tot is allocated as the same block of memory as scalefact.
           Not all this memory will actually have been used, but it is easiest to bcast all of it.*/
         MPI_Bcast(delta_tot_table.scalefact,delta_tot_table.namax*(delta_tot_table.nk+1),MPI_DOUBLE,0,MPI_COMM_WORLD);
     }
     }
 }
petaio_read_snapshot()
void petaio_read_snapshot (int num)
Definition at line 432 of file petaio.c.
References global_data_all_processes::a, All, global_data_all_processes::cf, fastpm_strdup_printf(), global_data_all_processes::InitCondFile, global_data_all_processes::IO, global_data_all_processes::MassTable, part_manager_type::NumPart, global_data_all_processes::OutputDir, P, PartManager, petaio_read_internal(), global_data_all_processes::SnapshotFileBase, and global_data_all_processes::UsePeculiarVelocity.
Referenced by init().
 {
     char * fname;
     if(num == -1) {
         fname = fastpm_strdup_printf("%s", All.InitCondFile);
         /*
          *  IC doesn't have entropy or energy; always use the
          *  InitTemp in paramfile, then use init.c to convert to
          *  entropy.
          * */
         petaio_read_internal(fname, 1);
         int i;
         /* touch up the mass -- IC files save mass in header */
         for(i = 0; i < PartManager->NumPart; i++)
         {
             P[i].Mass = All.MassTable[P[i].Type];
         }
         if (!All.IO.UsePeculiarVelocity ) {
             /* fixing the unit of velocity from Legacy GenIC IC */
             #pragma omp parallel for
             for(i = 0; i < PartManager->NumPart; i++) {
                 int k;
                 /* for GenIC's Gadget-1 snapshot Unit to Gadget-2 Internal velocity unit */
                 for(k = 0; k < 3; k++)
                     P[i].Vel[k] *= sqrt(All.cf.a) * All.cf.a;
             }
         }
     } else {
         fname = fastpm_strdup_printf("%s/%s_%03d", All.OutputDir, All.SnapshotFileBase, num);
         /*
          * we always save the Entropy, init.c will not mess with the entropy
          * */
         petaio_read_internal(fname, 0);
     }
     free(fname);
 }
petaio_readout_buffer()
void petaio_readout_buffer (BigArray * array, IOTableEntry * ent)
Definition at line 624 of file petaio.c.
References part_manager_type::NumPart, P, PartManager, IOTableEntry::ptype, and IOTableEntry::setter.
Referenced by petaio_read_internal().
{
     int i;
     /* fill the buffer */
     char * p = array->data;
     for(i = 0; i < PartManager->NumPart; i ++) {
         if(P[i].Type != ent->ptype) continue;
         ent->setter(i, p);
         p += array->strides[0];
     }
 }
petaio_save_block()
void petaio_save_block (BigFile * bf, char * blockname, BigArray * array)
Definition at line 705 of file petaio.c.
References All, global_data_all_processes::BytesPerFile, count_sum(), global_data_all_processes::EnableAggregatedIO, endrun(), global_data_all_processes::IO, message(), global_data_all_processes::MinNumWriters, global_data_all_processes::NumWriters, make_zeros::size, and global_data_all_processes::WritersPerFile.
Referenced by fof_save_particles(), petaio_save_internal(), and petaio_save_neutrinos().
 {
     BigBlock bb;
     BigBlockPtr ptr;
     int elsize = dtype_itemsize(array->dtype);
     int NumWriters = All.IO.NumWriters;
     size_t size = count_sum(array->dims[0]);
     int NumFiles;
     if(All.IO.EnableAggregatedIO) {
         NumFiles = (size * elsize + All.IO.BytesPerFile - 1) / All.IO.BytesPerFile;
         if(NumWriters > NumFiles * All.IO.WritersPerFile) {
             NumWriters = NumFiles * All.IO.WritersPerFile;
             message(0, "Throttling NumWriters to %d.\n", NumWriters);
         }
         if(NumWriters < All.IO.MinNumWriters) {
             NumWriters = All.IO.MinNumWriters;
             NumFiles = (NumWriters + All.IO.WritersPerFile - 1) / All.IO.WritersPerFile ;
             message(0, "Throttling NumWriters to %d.\n", NumWriters);
         }
     } else {
         NumFiles = NumWriters;
     }
     /*Do not write empty files*/
     if(size == 0) {
         NumFiles = 0;
     }
     if(size > 0) {
         message(0, "Will write %td particles to %d Files for %s\n", size, NumFiles, blockname);
     }
     /* create the block */
     /* dims[1] is the number of members per item */
     if(0 != big_file_mpi_create_block(bf, &bb, blockname, array->dtype, array->dims[1], NumFiles, size, MPI_COMM_WORLD)) {
         endrun(0, "Failed to create block at %s:%s\n", blockname,
                     big_file_get_error_message());
     }
     if(0 != big_block_seek(&bb, &ptr, 0)) {
         endrun(0, "Failed to seek:%s\n", big_file_get_error_message());
     }
     if(0 != big_block_mpi_write(&bb, &ptr, array, NumWriters, MPI_COMM_WORLD)) {
         endrun(0, "Failed to write :%s\n", big_file_get_error_message());
     }
     if(size > 0)
         message(0, "Done writing %td particles to %d Files\n", size, NumFiles);
     if(0 != big_block_mpi_close(&bb, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block at %s:%s\n", blockname,
                 big_file_get_error_message());
     }
 }
petaio_save_internal()
static void petaio_save_internal (char * fname) static
Definition at line 232 of file petaio.c.
References All, endrun(), IOTable::ent, global_data_all_processes::MassiveNuLinRespOn, myfree, mymalloc, IOTableEntry::name, part_manager_type::NumPart, PartManager, petaio_build_buffer(), petaio_build_selection(), petaio_destroy_buffer(), petaio_save_block(), petaio_save_neutrinos(), petaio_write_header(), IOTableEntry::ptype, sumup_large_ints(), and IOTable::used.
Referenced by petaio_init(), and petaio_save_snapshot().
{
     BigFile bf = {0};
     if(0 != big_file_mpi_create(&bf, fname, MPI_COMM_WORLD)) {
         endrun(0, "Failed to create snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     int ptype_offset[6]={0};
     int ptype_count[6]={0};
     int64_t NTotal[6]={0};
     int * selection = mymalloc("Selection", sizeof(int) * PartManager->NumPart);
     petaio_build_selection(selection, ptype_offset, ptype_count, PartManager->NumPart, NULL);
     sumup_large_ints(6, ptype_count, NTotal);
     petaio_write_header(&bf, NTotal);
     int i;
     for(i = 0; i < IOTable.used; i ++) {
         /* only process the particle blocks */
         char blockname[128];
         int ptype = IOTable.ent[i].ptype;
         BigArray array = {0};
         /*This exclude FOF blocks*/
         if(!(ptype < 6 && ptype >= 0)) {
             continue;
         }
         sprintf(blockname, "%d/%s", ptype, IOTable.ent[i].name);
         petaio_build_buffer(&array, &IOTable.ent[i], selection + ptype_offset[ptype], ptype_count[ptype]);
         petaio_save_block(&bf, blockname, &array);
         petaio_destroy_buffer(&array);
     }
     if(All.MassiveNuLinRespOn) {
         petaio_save_neutrinos(&bf);
     }
     if(0 != big_file_mpi_close(&bf, MPI_COMM_WORLD)){
         endrun(0, "Failed to close snapshot at %s:%s\n", fname,
                     big_file_get_error_message());
     }
     myfree(selection);
 }
petaio_save_neutrinos()
void petaio_save_neutrinos (BigFile * bf)
Definition at line 135 of file petaio.c.
References endrun(), myfree, mymalloc, petaio_save_block(), and ThisTask.
Referenced by petaio_save_internal().
 {
 #pragma omp master
     {
     double * scalefact = delta_tot_table.scalefact;
     size_t nk = delta_tot_table.nk, ia = delta_tot_table.ia;
     size_t ik, i;
     double * delta_tot = mymalloc("tmp_delta",nk * ia * sizeof(double));
     /*Save a flat memory block*/
     for(ik=0;ik< nk;ik++)
         for(i=0;i< ia;i++)
             delta_tot[ik*ia+i] = delta_tot_table.delta_tot[ik][i];
     BigBlock bn = {0};
     if(0 != big_file_mpi_create_block(bf, &bn, "Neutrino", NULL, 0, 0, 0, MPI_COMM_WORLD)) {
         endrun(0, "Failed to create block at %s:%s\n", "Neutrino",
                 big_file_get_error_message());
     }
     if ( (0 != big_block_set_attr(&bn, "Nscale", &ia, "u8", 1)) ||
        (0 != big_block_set_attr(&bn, "scalefact", scalefact, "f8", ia)) ||
         (0 != big_block_set_attr(&bn, "Nkval", &nk, "u8", 1)) ) {
         endrun(0, "Failed to write neutrino attributes %s\n",
                     big_file_get_error_message());
     }
     if(0 != big_block_mpi_close(&bn, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block %s\n",
                     big_file_get_error_message());
     }
     BigArray deltas = {0};
     size_t dims[2] = {0 , ia};
     /*The neutrino state is shared between all processors,
      *so only write on master task*/
     if(ThisTask == 0) {
         dims[0] = nk;
     }
     ptrdiff_t strides[2] = {8 * ia, 8};
     big_array_init(&deltas, delta_tot, "=f8", 2, dims, strides);
     petaio_save_block(bf, "Neutrino/Deltas", &deltas);
     myfree(delta_tot);
     }
 }
petaio_save_snapshot()
void petaio_save_snapshot (const char * fmt, ...)
Definition at line 61 of file petaio.c.
References message(), and petaio_save_internal().
Referenced by dump_snapshot(), runtests(), and write_snapshot().
 {
     va_list va;
     va_start(va, fmt);
     char fname[4096];
     vsprintf(fname, fmt, va);
     va_end(va);
     message(0, "saving snapshot into %s\n", fname);
     petaio_save_internal(fname);
 }
petaio_write_header()
static void petaio_write_header (BigFile * bf, const int64_t * NTotal) static
Definition at line 475 of file petaio.c.
References global_data_all_processes::a, All, global_data_all_processes::BoxSize, global_data_all_processes::cf, Cosmology::CMBTemperature, global_data_all_processes::CP, global_data_all_processes::DensityKernelType, endrun(), global_data_all_processes::hubble, Cosmology::HubbleParam, global_data_all_processes::IO, global_data_all_processes::MassTable, global_data_all_processes::NTotalInit, Cosmology::Omega0, Cosmology::OmegaBaryon, Cosmology::OmegaLambda, global_data_all_processes::Time, global_data_all_processes::TimeIC, global_data_all_processes::UnitLength_in_cm, global_data_all_processes::UnitMass_in_g, global_data_all_processes::UnitVelocity_in_cm_per_s, and global_data_all_processes::UsePeculiarVelocity.
Referenced by petaio_save_internal().
{
     BigBlock bh = {0};
     if(0 != big_file_mpi_create_block(bf, &bh, "Header", NULL, 0, 0, 0, MPI_COMM_WORLD)) {
         endrun(0, "Failed to create block at %s:%s\n", "Header",
                 big_file_get_error_message());
     }
     /* conversion from peculiar velocity to RSD */
     double RSD = 1.0 / (All.cf.a * All.cf.hubble);
     if(!All.IO.UsePeculiarVelocity) {
         RSD /= All.cf.a; /* Conversion from internal velocity to RSD */
     }
     if(
     (0 != big_block_set_attr(&bh, "TotNumPart", NTotal, "u8", 6)) ||
     (0 != big_block_set_attr(&bh, "TotNumPartInit", All.NTotalInit, "u8", 6)) ||
     (0 != big_block_set_attr(&bh, "MassTable", All.MassTable, "f8", 6)) ||
     (0 != big_block_set_attr(&bh, "Time", &All.Time, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "TimeIC", &All.TimeIC, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "BoxSize", &All.BoxSize, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "OmegaLambda", &All.CP.OmegaLambda, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "RSDFactor", &RSD, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "UsePeculiarVelocity", &All.IO.UsePeculiarVelocity, "i4", 1)) ||
     (0 != big_block_set_attr(&bh, "Omega0", &All.CP.Omega0, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "CMBTemperature", &All.CP.CMBTemperature, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "OmegaBaryon", &All.CP.OmegaBaryon, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "UnitLength_in_cm", &All.UnitLength_in_cm, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "UnitMass_in_g", &All.UnitMass_in_g, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "UnitVelocity_in_cm_per_s", &All.UnitVelocity_in_cm_per_s, "f8", 1)) ||
     (0 != big_block_set_attr(&bh, "CodeVersion", GADGET_VERSION, "S1", strlen(GADGET_VERSION))) ||
     (0 != big_block_set_attr(&bh, "CompilerSettings", GADGET_COMPILER_SETTINGS, "S1", strlen(GADGET_COMPILER_SETTINGS))) ||
     (0 != big_block_set_attr(&bh, "DensityKernel", &All.DensityKernelType, "u8", 1)) ||
     (0 != big_block_set_attr(&bh, "HubbleParam", &All.CP.HubbleParam, "f8", 1)) ) {
         endrun(0, "Failed to write attributes %s\n",
                     big_file_get_error_message());
     }
     if(0 != big_block_mpi_close(&bh, MPI_COMM_WORLD)) {
         endrun(0, "Failed to close block %s\n",
                     big_file_get_error_message());
     }
 }
register_io_blocks()
static void register_io_blocks () static
Definition at line 892 of file petaio.c.
References All, IOTable::ent, fof_register_io_blocks(), IO_REG, IO_REG_NONFATAL, IO_REG_TYPE, IO_REG_WRONLY, order_by_type(), global_data_all_processes::OutputPotential, qsort_openmp(), global_data_all_processes::SnapshotWithFOF, and IOTable::used.
Referenced by petaio_init().
{
     int i;
     /* Bare Bone Gravity*/
     for(i = 0; i < 6; i ++) {
         IO_REG(Position, "f8", 3, i);
         IO_REG(Velocity, "f4", 3, i);
         IO_REG(Mass,     "f4", 1, i);
         IO_REG(ID,       "u8", 1, i);
         if(All.OutputPotential)
             IO_REG_WRONLY(Potential, "f4", 1, i);
         if(All.SnapshotWithFOF)
             IO_REG_WRONLY(GroupID, "u4", 1, i);
     }
     IO_REG(Generation,       "u1", 1, 0);
     IO_REG(Generation,       "u1", 1, 4);
     IO_REG(Generation,       "u1", 1, 5);
     /* Bare Bone SPH*/
     IO_REG(SmoothingLength,  "f4", 1, 0);
     IO_REG(Density,          "f4", 1, 0);
 #ifdef DENSITY_INDEPENDENT_SPH
     IO_REG(EgyWtDensity,          "f4", 1, 0);
     IO_REG(Entropy,          "f4", 1, 0);
 #endif
     /* Cooling */
     IO_REG(ElectronAbundance,       "f4", 1, 0);
     IO_REG_WRONLY(NeutralHydrogenFraction, "f4", 1, 0);
     IO_REG_WRONLY(InternalEnergy,   "f4", 1, 0);
     IO_REG_WRONLY(JUV,   "f4", 1, 0);
     /* SF */
 #ifdef SFR
     IO_REG_WRONLY(StarFormationRate, "f4", 1, 0);
     IO_REG_NONFATAL(BirthDensity, "f4", 1, 4);
     IO_REG_TYPE(StarFormationTime, "f4", 1, 4);
     IO_REG_TYPE(Metallicity,       "f4", 1, 0);
     IO_REG_TYPE(Metallicity,       "f4", 1, 4);
 #endif /* SFR */
 #ifdef BLACK_HOLES
     /* Blackhole */
     IO_REG_TYPE(StarFormationTime, "f4", 1, 5);
     IO_REG(BlackholeMass,          "f4", 1, 5);
     IO_REG(BlackholeAccretionRate, "f4", 1, 5);
     IO_REG(BlackholeProgenitors,   "i4", 1, 5);
     IO_REG(BlackholeMinPotPos, "f8", 3, 5);
     IO_REG(BlackholeMinPotVel,   "f4", 3, 5);
     IO_REG(BlackholeJumpToMinPot,   "i4", 1, 5);
 #endif
     if(All.SnapshotWithFOF)
         fof_register_io_blocks();
     /*Sort IO blocks so similar types are together*/
     qsort_openmp(IOTable.ent, IOTable.used, sizeof(struct IOTableEntry), order_by_type);
 }
STVelocity()
static void STVelocity (int i, float * out) static
Definition at line 810 of file petaio.c.
References global_data_all_processes::a, All, BHP, global_data_all_processes::cf, get_starformation_rate(), global_data_all_processes::IO, P, SEC_PER_YEAR, SIMPLE_GETTER, SIMPLE_PROPERTY, SIMPLE_PROPERTY_TYPE, SOLAR_MASS, SPHP, STARP, global_data_all_processes::UnitMass_in_g, global_data_all_processes::UnitTime_in_s, and global_data_all_processes::UsePeculiarVelocity.
{
     double fac;
     if (All.IO.UsePeculiarVelocity) {
         fac = All.cf.a;
     } else {
         fac = 1.0;
     }
     int d;
     for(d = 0; d < 3; d ++) {
         P[i].Vel[d] = out[d] * fac;
     }
 }
Variable Documentation
delta_tot_table
_delta_tot_table delta_tot_table
Definition at line 24 of file gravpm.c.
Referenced by compute_neutrino_power(), gravpm_init_periodic(), petaio_build_selection(), petaio_read_neutrinos(), and powerspectrum_nu_save().
IOTable
struct IOTable IOTable = {0}
Definition at line 37 of file petaio.c.