MP-Gadget: libgenic/power.h File Reference
power.h File Reference
#include <libgadget/cosmology.h>
#include <bigfile-mpi.h>
Classes
struct power_params
Enumerations
enum TransferType {
DELTA_BAR = 0 , DELTA_CDM = 1 , DELTA_NU = 2 , DELTA_CB = 3 ,
VEL_BAR = 4 , VEL_CDM = 5 , VEL_NU = 6 , VEL_CB = 7 ,
VEL_TOT = 8 , DELTA_TOT = 9
}
Functions
double DeltaSpec (double kmag, enum TransferType Type)
double dlogGrowth (double kmag, enum TransferType Type)
int init_powerspectrum (int ThisTask, double InitTime, double UnitLength_in_cm_in, Cosmology *CPin, struct power_params *ppar)
void save_all_transfer_tables (BigFile *bf, int ThisTask)
Enumeration Type Documentation
TransferType
enum TransferType
Enumerator
DELTA_BAR
DELTA_CDM
DELTA_NU
DELTA_CB
VEL_BAR
VEL_CDM
VEL_NU
VEL_CB
VEL_TOT
DELTA_TOT
Definition at line 40 of file power.h.
 {
     DELTA_BAR = 0,
     DELTA_CDM = 1,
     DELTA_NU = 2,
     DELTA_CB = 3,
     VEL_BAR = 4,
     VEL_CDM = 5,
     VEL_NU = 6,
     VEL_CB = 7,
     VEL_TOT = 8,
     /*Always unity, so there is no memory for it*/
     DELTA_TOT = 9,
 };
Function Documentation
DeltaSpec()
double DeltaSpec (double kmag, enum TransferType Type)
Definition at line 52 of file power.c.
 {
   double power;
   if(WhichSpectrum == 2)
       power = Delta_Tabulated(k, Type);
   else
       power = Delta_EH(k);
   /*Normalise the power spectrum*/
   power *= Norm;
   return power;
 }
References Delta_EH(), Delta_Tabulated(), Norm, and WhichSpectrum.
Referenced by density_transfer(), disp_transfer(), print_spec(), sigma2_int(), test_growth_numerical(), test_read_no_rescale(), and test_read_rescale_sigma8().
dlogGrowth()
double dlogGrowth (double kmag, enum TransferType Type)
Definition at line 101 of file power.c.
 {
     /*Default to total growth: type 3 is cdm + baryons.*/
     if(Type < DELTA_BAR || Type > DELTA_CB)
         Type = VEL_TOT;
     else
         /*Type should be an offset from the first velocity*/
         Type = (enum TransferType) ((int) VEL_BAR + ((int) Type - (int) DELTA_BAR));
     return get_Tabulated(kmag, Type, 1);
 }
References DELTA_BAR, DELTA_CB, get_Tabulated(), VEL_BAR, and VEL_TOT.
Referenced by disp_transfer(), and test_growth_numerical().
init_powerspectrum()
int init_powerspectrum (int ThisTask, double InitTime, double UnitLength_in_cm_in, Cosmology * CPin, struct power_params * ppar)
Definition at line 394 of file power.c.
 {
     WhichSpectrum = ppar->WhichSpectrum;
     /*Used only for tk_eh*/
     PrimordialIndex = ppar->PrimordialIndex;
     UnitLength_in_cm = UnitLength_in_cm_in;
     CP = CPin;
     if(ppar->WhichSpectrum == 2) {
         read_power_table(ThisTask, ppar->FileWithInputSpectrum, 1, &power_table, InitTime, parse_power);
         /*Initialise the interpolation*/
         gsl_interp_init(power_table.mat_intp[0],power_table.logk, power_table.logD[0],power_table.Nentry);
         transfer_table.Nentry = 0;
         if(ppar->DifferentTransferFunctions || ppar->ScaleDepVelocity) {
             init_transfer_table(ThisTask, InitTime, ppar);
         }
     }
     Norm = 1.0;
     if(ppar->InputPowerRedshift >= 0 || ppar->Sigma8 > 0) {
         const double R8 = 8 * (CM_PER_MPC / UnitLength_in_cm);  /* 8 Mpc/h */
         if(ppar->Sigma8 > 0) {
             double res = TopHatSigma2(R8);
             if(isfinite(res) && res > 0)
                 Norm = ppar->Sigma8 / sqrt(res);
             else
                 endrun(1, "Could not normalize P(k) to Sigma8=%g! Measured Sigma8^2 is %g\n", ppar->Sigma8, res);
         }
         double Dplus = GrowthFactor(CP, InitTime, 1/(1+ppar->InputPowerRedshift));
         if(ppar->InputPowerRedshift >= 0) {
             Norm *= Dplus;
             message(0,"Growth factor from z=%g (InputPowerRedshift) to z=%g (Init): %g \n", ppar->InputPowerRedshift, 1. / InitTime - 1, Dplus);
         }
         message(0, "Normalization adjusted to  Sigma8=%g (at z=0)  (Normfac=%g). \n", sqrt(TopHatSigma2(R8))/Dplus, Norm);
     }
     return power_table.Nentry;
 }
References CM_PER_MPC, CP, power_params::DifferentTransferFunctions, endrun(), power_params::FileWithInputSpectrum, GrowthFactor(), init_transfer_table(), power_params::InputPowerRedshift, table::logD, table::logk, table::mat_intp, message(), table::Nentry, Norm, parse_power(), power_table, PrimordialIndex, power_params::PrimordialIndex, read_power_table(), power_params::ScaleDepVelocity, power_params::Sigma8, ThisTask, TopHatSigma2(), transfer_table, UnitLength_in_cm, WhichSpectrum, and power_params::WhichSpectrum.
Referenced by main(), test_growth_numerical(), test_read_no_rescale(), and test_read_rescale_sigma8().
save_all_transfer_tables()
void save_all_transfer_tables (BigFile * bf, int ThisTask)
Definition at line 150 of file power.c.
 {
     const char * pname = "DELTA_MAT";
     save_transfer(bf, 1, &power_table, "ICPower", ThisTask, &pname);
     save_transfer(bf, MAXCOLS, &transfer_table, "ICTransfers", ThisTask, tnames);
 }
References MAXCOLS, power_table, save_transfer(), ThisTask, tnames, and transfer_table.
Referenced by main().