MP-Gadget: libgadget/powerspectrum.h File Reference
powerspectrum.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <gsl/gsl_interp.h>
Classes
struct _powerspectrum
Typedefs
typedef struct _powerspectrum Power
Functions
void powerspectrum_alloc (Power *ps, const int nbins, const int nthreads, const int MassiveNuLinResp, const double BoxSize_in_cm)
void powerspectrum_zero (Power *ps)
void powerspectrum_free (Power *ps)
void powerspectrum_sum (Power *ps)
void powerspectrum_save (Power *ps, const char *OutputDir, const char *filename, const double Time, const double D1)
Typedef Documentation
Power
typedef struct _powerspectrum Power
Function Documentation
powerspectrum_alloc()
void powerspectrum_alloc (Power * ps, const int nbins, const int nthreads, const int MassiveNuLinResp, const double BoxSize_in_cm)
Definition at line 16 of file powerspectrum.c.
 {
     ps->size = nbins;
     const int nalloc = nbins*nthreads;
     ps->nalloc = nalloc;
     ps->kk = (double *) mymalloc("Powerspectrum", sizeof(double) * 2*nalloc);
     ps->Power = ps->kk + nalloc;
     ps->BoxSize_in_MPC = BoxSize_in_cm / CM_PER_MPC;
     ps->logknu = NULL;
     if(MassiveNuLinResp) {
         /*These arrays are stored separately to make interpolation more accurate*/
         ps->logknu = (double *) mymalloc("PowerNu", sizeof(double) * 2*nbins);
         ps->delta_nu_ratio = ps-> logknu + nbins;
     }
     ps->Nmodes = (int64_t *) mymalloc("Powermodes", sizeof(int64_t) * nalloc);
     powerspectrum_zero(ps);
 }
References _powerspectrum::BoxSize_in_MPC, CM_PER_MPC, _powerspectrum::delta_nu_ratio, _powerspectrum::kk, _powerspectrum::logknu, mymalloc, _powerspectrum::nalloc, _powerspectrum::Nmodes, _powerspectrum::Power, powerspectrum_zero(), and _powerspectrum::size.
Referenced by _prepare(), glass_evolve(), and test_total_powerspectrum().
powerspectrum_free()
void powerspectrum_free (Power * ps)
Definition at line 44 of file powerspectrum.c.
 {
     myfree(ps->Nmodes);
     if(ps->logknu)
         myfree(ps->logknu);
     myfree(ps->kk);
 }
References _powerspectrum::kk, _powerspectrum::logknu, myfree, and _powerspectrum::Nmodes.
Referenced by glass_evolve(), and gravpm_force().
powerspectrum_save()
void powerspectrum_save (Power * ps, const char * OutputDir, const char * filename, const double Time, const double D1)
Definition at line 92 of file powerspectrum.c.
 {
         int i;
         int ThisTask;
         MPI_Comm_rank(MPI_COMM_WORLD, &ThisTask);
         if(ThisTask != 0)
             return;
         char * fname = fastpm_strdup_printf("%s/%s-%0.4f.txt", OutputDir, filename, Time);
         /* Avoid -0.0000.txt at high z*/
         if(Time <= 1e-4) {
             myfree(fname);
             fname = fastpm_strdup_printf("%s/%s-%0.4e.txt", OutputDir, filename, Time);
         }
         message(1, "Writing Power Spectrum to %s\n", fname);
         FILE * fp = fopen(fname, "w");
         if(!fp)
             message(1, "Could not open %s for writing\n", fname);
         else {
             fprintf(fp, "# in Mpc/h Units \n");
             fprintf(fp, "# D1 = %g \n", D1);
             fprintf(fp, "# k P N P(z=0)\n");
             for(i = 0; i < ps->nonzero; i ++) {
                 fprintf(fp, "%g %g %ld %g\n", ps->kk[i], ps->Power[i], ps->Nmodes[i],
                             ps->Power[i] / (D1 * D1));
             }
             fclose(fp);
         }
         myfree(fname);
 }
References fastpm_strdup_printf(), _powerspectrum::kk, message(), myfree, _powerspectrum::Nmodes, _powerspectrum::nonzero, _powerspectrum::Power, and ThisTask.
Referenced by glass_evolve(), and gravpm_force().
powerspectrum_sum()
void powerspectrum_sum (Power * ps)
Definition at line 54 of file powerspectrum.c.
 {
     /*Sum power spectrum thread-local storage*/
     int i,j;
     for(i = 0; i < ps->size; i ++) {
         for(j = 1; j < ps->nalloc/ps->size; j++) {
             ps->Power[i] += ps->Power[i+ ps->size*j];
             ps->kk[i] += ps->kk[i+ ps->size*j];
             ps->Nmodes[i] += ps->Nmodes[i +ps->size*j];
         }
     }
     /*Now sum power spectrum MPI storage*/
     MPI_Allreduce(MPI_IN_PLACE, &(ps->Norm), 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
     MPI_Allreduce(MPI_IN_PLACE, ps->kk, ps->size, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
     MPI_Allreduce(MPI_IN_PLACE, ps->Power, ps->size, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
     MPI_Allreduce(MPI_IN_PLACE, ps->Nmodes, ps->size, MPI_INT64, MPI_SUM, MPI_COMM_WORLD);
     int nk_nz = 0;
     /*Now fix power spectrum units and remove zero entries.*/
     for(i = 0; i < ps->size; i ++) {
         if(ps->Nmodes[i] == 0) continue;
         ps->Power[i] /= ps->Nmodes[i];
         ps->Power[i] /= ps->Norm;
         ps->kk[i] /= ps->Nmodes[i];
         /* Mpc/h units */
         ps->kk[i] *= 2 * M_PI / (ps->BoxSize_in_MPC);
         ps->Power[i] *= pow(ps->BoxSize_in_MPC , 3.0);
         /*Move the power spectrum earlier, removing zero modes*/
         ps->Power[nk_nz] = ps->Power[i];
         ps->kk[nk_nz] = ps->kk[i];
         ps->Nmodes[nk_nz] = ps->Nmodes[i];
         nk_nz++;
     }
     ps->nonzero = nk_nz;
 }
References _powerspectrum::BoxSize_in_MPC, _powerspectrum::kk, MPI_INT64, _powerspectrum::nalloc, _powerspectrum::Nmodes, _powerspectrum::nonzero, _powerspectrum::Norm, _powerspectrum::Power, and _powerspectrum::size.
Referenced by compute_neutrino_power(), glass_force(), gravpm_force(), and test_total_powerspectrum().
powerspectrum_zero()
void powerspectrum_zero (Power * ps)
Definition at line 35 of file powerspectrum.c.
 {
     memset(ps->kk, 0, sizeof(double) * ps->nalloc);
     memset(ps->Power, 0, sizeof(double) * ps->nalloc);
     memset(ps->Nmodes, 0, sizeof(int64_t) * ps->nalloc);
     ps->Norm = 0;
 }
References _powerspectrum::kk, _powerspectrum::nalloc, _powerspectrum::Nmodes, _powerspectrum::Norm, and _powerspectrum::Power.
Referenced by compute_neutrino_power(), glass_force(), powerspectrum_alloc(), and test_total_powerspectrum().