MP-Gadget: runtests.c File Reference
runtests.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <ctype.h>
#include "allvars.h"
#include "partmanager.h"
#include "forcetree.h"
#include "proto.h"
#include "cooling.h"
#include "mymalloc.h"
#include "endrun.h"
#include "petaio.h"
#include "domain.h"
#include "timestep.h"
Functions
void grav_short_pair (void)
char * GDB_format_particle (int i)
void runtests ()
Function Documentation
GDB_format_particle()
char* GDB_format_particle (int i)
Definition at line 56 of file gdbtools.c.
References add, and P.
Referenced by runtests().
{
     static char buf[4096];
     char * p = buf;
     int n = 4096;
 #define add(fmt, ...) \
         snprintf(p, n - 1, fmt, __VA_ARGS__ ); \
         p = buf + strlen(buf); \
         n = 4096 - strlen(buf)
     add("P[%d]: ", i);
     add("ID : %ld ", P[i].ID);
     add("Generation: %d ", (int) P[i].Generation);
     add("Mass : %g ", P[i].Mass);
     add("Pos: %g %g %g ", P[i].Pos[0], P[i].Pos[1], P[i].Pos[2]);
     add("Vel: %g %g %g ", P[i].Vel[0], P[i].Vel[1], P[i].Vel[2]);
     add("GravAccel: %g %g %g ", P[i].GravAccel[0], P[i].GravAccel[1], P[i].GravAccel[2]);
     add("GravPM: %g %g %g ", P[i].GravPM[0], P[i].GravPM[1], P[i].GravPM[2]);
     return buf;
 }
grav_short_pair()
void grav_short_pair (void)
Definition at line 24 of file gravshort-pair.c.
References ActiveParticle, TreeWalk::ev_label, TreeWalk::fill, grav_short_copy(), grav_short_haswork(), grav_short_pair_ngbiter(), grav_short_postprocess(), grav_short_reduce(), TreeWalk::haswork, message(), TreeWalk::ngbiter, TreeWalk::ngbiter_type_elsize, NumActiveParticle, TreeWalk::postprocess, TreeWalk::query_type_elsize, TreeWalk::reduce, TreeWalk::result_type_elsize, treewalk_run(), treewalk_visit_ngbiter(), TreeWalk::UseNodeList, TreeWalk::visit, and walltime_measure.
Referenced by runtests().
 {
     TreeWalk tw[1] = {0};
     message(0, "Starting pair-wise short range gravity...\n");
     tw->ev_label = "GRAV_SHORT";
     tw->visit = (TreeWalkVisitFunction) treewalk_visit_ngbiter;
     tw->ngbiter_type_elsize = sizeof(TreeWalkNgbIterGravShort);
     tw->ngbiter = (TreeWalkNgbIterFunction) grav_short_pair_ngbiter;
     tw->haswork = grav_short_haswork;
     tw->fill = (TreeWalkFillQueryFunction) grav_short_copy;
     tw->reduce = (TreeWalkReduceResultFunction) grav_short_reduce;
     tw->postprocess = (TreeWalkProcessFunction) grav_short_postprocess;
     tw->UseNodeList = 1;
     tw->query_type_elsize = sizeof(TreeWalkQueryGravShort);
     tw->result_type_elsize = sizeof(TreeWalkResultGravShort);
     walltime_measure("/Misc");
     treewalk_run(tw, ActiveParticle, NumActiveParticle);
     walltime_measure("/Grav/Short");
 }
runtests()
void runtests (void)
Definition at line 27 of file runtests.c.
References All, domain_decompose_full(), GDB_format_particle(), grav_short_pair(), grav_short_tree(), gravpm_force(), IO_REG, message(), NTask, part_manager_type::NumPart, global_data_all_processes::OutputDir, P, PartManager, petaio_save_snapshot(), rebuild_activelist(), ThisTask, and global_data_all_processes::Ti_Current.
Referenced by main().
 {
     int ptype;
     for(ptype = 0; ptype < 6; ptype++) {
         IO_REG(GravAccel,       "f4", 3, ptype);
         IO_REG(GravPM,       "f4", 3, ptype);
     }
     gravpm_force();
     /* this produces a very imbalanced load to trigger Issue 86 */
     if(ThisTask == 0) {
         P[0].GravCost = 1e10;
         P[PartManager->NumPart - 1].GravCost = 1e10;
     }
     domain_decompose_full();    /* do domain decomposition */
     rebuild_activelist(All.Ti_Current);
     grav_short_pair();
     message(0, "GravShort Pairs %s\n", GDB_format_particle(0));
     petaio_save_snapshot("%s/PART-pairs-%03d-mpi", All.OutputDir, NTask);
     grav_short_tree();  /* computes gravity accel. */
     grav_short_tree();  /* computes gravity accel. */
     grav_short_tree();  /* computes gravity accel. */
     grav_short_tree();  /* computes gravity accel. */
     message(0, "GravShort Tree %s\n", GDB_format_particle(0));
     petaio_save_snapshot("%s/PART-tree-%03d-mpi", All.OutputDir, NTask);
 }