MP-Gadget: sfr_eff.h File Reference
sfr_eff.h File Reference
Functions
void init_clouds (void)
void cooling_and_starformation (void)
void cooling_only (void)
double get_starformation_rate (int i)
Function Documentation
cooling_and_starformation()
void cooling_and_starformation (void)
Referenced by compute_accelerations().
cooling_only()
void cooling_only (void)
Definition at line 347 of file sfr_eff.c.
References ActiveParticle, All, cool_postprocess(), global_data_all_processes::CoolingOn, TreeWalk::ev_label, TreeWalk::haswork, NumActiveParticle, TreeWalk::postprocess, treewalk_run(), TreeWalk::visit, and walltime_measure.
Referenced by compute_accelerations().
 {
     if(!All.CoolingOn) return;
     walltime_measure("/Misc");
     TreeWalk tw[1] = {0};
     /* Only used to list all active particles for the parallel loop */
     /* no tree walking and no need to export / copy particles. */
     tw->visit = NULL; /* no tree walk */
     tw->ev_label = "SFR_COOL";
     tw->haswork = sfr_cooling_haswork;
     tw->postprocess = (TreeWalkProcessFunction) cool_postprocess;
     treewalk_run(tw, ActiveParticle, NumActiveParticle);
     walltime_measure("/Cooling/StarFormation");
 }
get_starformation_rate()
double get_starformation_rate (int i)
Referenced by add_particle_to_group(), cooling_direct(), and STVelocity().
init_clouds()
void init_clouds (void)
Referenced by begrun(), and cooling_direct().