MP-Gadget: libgadget/utils/spinlocks.c File Reference
spinlocks.c File Reference
#include "spinlocks.h"
#include "mymalloc.h"
#include <pthread.h>
Classes
struct SpinLocks
Functions
void lock_spinlock (int i, struct SpinLocks *spin)
void unlock_spinlock (int i, struct SpinLocks *spin)
int try_lock_spinlock (int i, struct SpinLocks *spin)
struct SpinLocks * init_spinlocks (int NumLock)
void free_spinlocks (struct SpinLocks *spin)
Variables
static struct SpinLocks spin
Function Documentation
free_spinlocks()
void free_spinlocks (struct SpinLocks * spin)
Definition at line 70 of file spinlocks.c.
 {
     int i;
     for(i = 0; i < spin->NumSpinLock; i ++) {
 #ifndef NO_OPENMP_SPINLOCK
         pthread_spin_destroy(&(spin->SpinLocks[i]));
 #else
         omp_destroy_lock(&(spin->SpinLocks[i]));
 #endif
     }
     myfree((void *) spin->SpinLocks);
 }
References myfree, SpinLocks::NumSpinLock, spin, and SpinLocks::SpinLocks.
Referenced by fof_label_primary(), and metal_return().
init_spinlocks()
struct SpinLocks* init_spinlocks (int NumLock)
Definition at line 49 of file spinlocks.c.
 {
     int i;
     /* Initialize the spinlocks*/
 #ifndef NO_OPENMP_SPINLOCK
     spin.SpinLocks = (pthread_spinlock_t *) mymalloc("SpinLocks", NumLock * sizeof(pthread_spinlock_t));
     #pragma omp parallel for
 #else
     spin.SpinLocks = mymalloc("SpinLocks", NumLock * sizeof(omp_lock_t));
 #endif
     for(i = 0; i < NumLock; i ++) {
 #ifndef NO_OPENMP_SPINLOCK
         pthread_spin_init(&spin.SpinLocks[i], PTHREAD_PROCESS_PRIVATE);
 #else
         omp_init_lock(&spin.SpinLocks[i]);
 #endif
     }
     spin.NumSpinLock = NumLock;
     return &spin;
 }
References mymalloc, SpinLocks::NumSpinLock, spin, and SpinLocks::SpinLocks.
Referenced by fof_label_primary(), and metal_return().
lock_spinlock()
void lock_spinlock (int i, struct SpinLocks * spin)
Definition at line 23 of file spinlocks.c.
{
 #ifndef NO_OPENMP_SPINLOCK
     pthread_spin_lock(&spin->SpinLocks[i]);
 #else
     omp_set_lock(&spin->SpinLocks[i]);
 #endif
 }
References spin, and SpinLocks::SpinLocks.
Referenced by fof_label_primary(), fof_primary_ngbiter(), fofp_merge(), and metal_return_ngbiter().
try_lock_spinlock()
int try_lock_spinlock (int i, struct SpinLocks * spin)
Definition at line 38 of file spinlocks.c.
 {
 #ifndef NO_OPENMP_SPINLOCK
     return pthread_spin_trylock(&spin->SpinLocks[i]);
 #else
     /* omp returns true if successful, ie, lock taken.
      * pthread_spin_lock returns 0 on success*/
     return !omp_test_lock(&spin->SpinLocks[i]);
 #endif
 }
References spin, and SpinLocks::SpinLocks.
unlock_spinlock()
void unlock_spinlock (int i, struct SpinLocks * spin)
Definition at line 30 of file spinlocks.c.
{
 #ifndef NO_OPENMP_SPINLOCK
     pthread_spin_unlock(&spin->SpinLocks[i]);
 #else
     omp_unset_lock(&spin->SpinLocks[i]);
 #endif
 }
References spin, and SpinLocks::SpinLocks.
Referenced by fof_label_primary(), fof_primary_ngbiter(), fofp_merge(), and metal_return_ngbiter().
Variable Documentation
spin
struct SpinLocks spin static
Definition at line 1 of file spinlocks.c.
Referenced by fof_label_primary(), fof_primary_ngbiter(), fofp_merge(), free_spinlocks(), init_spinlocks(), lock_spinlock(), try_lock_spinlock(), and unlock_spinlock().