MP-Gadget: libgadget/utils/string.h File Reference
string.h File Reference
#include <stdarg.h>
Functions
char * fastpm_file_get_content (const char *filename)
char * fastpm_strdup (const char *str)
char * fastpm_strdup_printf (const char *fmt,...)
char * fastpm_strdup_vprintf (const char *fmt, va_list va)
void fastpm_path_ensure_dirname (const char *path)
Function Documentation
fastpm_file_get_content()
char* fastpm_file_get_content (const char * filename)
Definition at line 14 of file string.c.
 {
     FILE * fp = fopen(filename, "r");
     if(!fp) return NULL;
     fseek(fp, 0, SEEK_END);
     size_t file_length = ftell(fp);
     char * buf = ta_malloc2(filename, char, file_length + 1);
     fseek(fp, 0, SEEK_SET);
     file_length = fread(buf, 1, file_length, fp);
     fclose(fp);
     buf[file_length] = 0;
     return buf;
 }
References ta_malloc2.
Referenced by hci_query_filesystem(), and param_parse_file().
fastpm_path_ensure_dirname()
void fastpm_path_ensure_dirname (const char * path)
Definition at line 70 of file string.c.
 {
     int i = strlen(path);
     char * dup = ta_malloc("dirname", char, strlen(path) + 1);
     strcpy(dup, path);
     dup[strlen(path)]='\0';
     char * p;
     for(p = i + dup; p >= dup && *p != '/'; p --) {
         continue;
     }
     /* plain file name in current directory */
     if(p < dup) return;
     /* p == '/', so set it to NULL, dup is the dirname */
     *p = 0;
     _mkdir(dup);
     myfree(dup);
 }
References _mkdir(), myfree, and ta_malloc.
Referenced by open_outputfiles().
fastpm_strdup()
char* fastpm_strdup (const char * str)
Definition at line 31 of file string.c.
 {
     size_t N = strlen(str);
     char * d = ta_malloc("strdup", char, N + 1);
     strcpy(d, str);
     d[N] = '\0';
     return d;
 }
References ta_malloc.
Referenced by OutputListAction(), param_declare_string(), param_format_value(), param_set_from_string(), and parse_enum().
fastpm_strdup_printf()
char* fastpm_strdup_printf (const char * fmt, ...)
Definition at line 41 of file string.c.
 {
     va_list va;
     va_start(va, fmt);
     char * buf = fastpm_strdup_vprintf(fmt, va);
     va_end(va);
     return buf;
 }
References fastpm_strdup_vprintf().
Referenced by begrun(), dump_snapshot(), exists(), find_last_snapnum(), fof_save_particles(), hci_query_filesystem(), open_outputfiles(), petaio_get_snapshot_fname(), powerspectrum_nu_save(), powerspectrum_save(), run_gravity_test(), setup_glass(), touch(), and write_checkpoint().
fastpm_strdup_vprintf()
char* fastpm_strdup_vprintf (const char * fmt, va_list va)
Definition at line 51 of file string.c.
 {
     va_list va2;
     va_copy(va2, va);
     /* This relies on a good LIBC vsprintf that returns the number of char */
     char buf0[128];
     size_t N = vsnprintf(buf0, 1, fmt, va);
     char * buf = ta_malloc("strdup_vprintf", char, N + 100);
     vsnprintf(buf, N + 1, fmt, va2);
     buf[N + 1] = 0;
     va_end(va2);
     return buf;
 }
References ta_malloc.
Referenced by fastpm_strdup_printf(), and report_detailed_memory_usage().