MP-Gadget: PetaPMGlobalFunctions Struct Reference
PetaPMGlobalFunctions Struct Reference
#include <petapm.h>
Public Attributes
void(* global_readout)(int64_t k2, int kpos[3], pfft_complex *value)
void(* global_analysis)(void)
void(* global_transfer)(int64_t k2, int kpos[3], pfft_complex *value)
Detailed Description
Definition at line 25 of file petapm.h.
Member Data Documentation
global_analysis
void(* PetaPMGlobalFunctions::global_analysis) (void)
Definition at line 27 of file petapm.h.
Referenced by gravpm_init_periodic(), and petapm_force_r2c().
global_readout
void(* PetaPMGlobalFunctions::global_readout) (int64_t k2, int kpos[3], pfft_complex *value)
Definition at line 26 of file petapm.h.
Referenced by gravpm_init_periodic(), and petapm_force_r2c().
global_transfer
void(* PetaPMGlobalFunctions::global_transfer) (int64_t k2, int kpos[3], pfft_complex *value)
Definition at line 28 of file petapm.h.
Referenced by petapm_force_r2c().
The documentation for this struct was generated from the following file:
petapm.h