MP-Gadget: libgadget/tests/test_hci.c File Reference
test_hci.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <stdlib.h>
#include <setjmp.h>
#include <cmocka.h>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include "stub.h"
#include <libgadget/hci.h>
Functions
static void touch (char *prefix, char *b)
static int exists (char *prefix, char *b)
static void test_hci_no_action (void **state)
static void test_hci_auto_checkpoint (void **state)
static void test_hci_auto_checkpoint2 (void **state)
static void test_hci_timeout (void **state)
static void test_hci_stop (void **state)
static void test_hci_checkpoint (void **state)
static void test_hci_terminate (void **state)
static int setup (void **state)
static int teardown (void **state)
int main (void)
Variables
char prefix [1024] = "XXXXXXXX"
HCIManager manager [1]
Function Documentation
exists()
static int exists (char * prefix, char * b) static
Definition at line 25 of file test_hci.c.
 {
     char * fn = fastpm_strdup_printf("%s/%s", prefix, b);
     FILE * fp = fopen(fn, "r");
     myfree(fn);
     if(fp) {
         fclose(fp);
         return 1;
     }
     return 0;
 }
References fastpm_strdup_printf(), myfree, and prefix.
Referenced by test_hci_checkpoint(), test_hci_stop(), and test_hci_terminate().
main()
int main (void)
Definition at line 174 of file test_hci.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_hci_no_action),
         cmocka_unit_test(test_hci_auto_checkpoint),
         cmocka_unit_test(test_hci_auto_checkpoint2),
         cmocka_unit_test(test_hci_timeout),
         cmocka_unit_test(test_hci_stop),
         cmocka_unit_test(test_hci_checkpoint),
         cmocka_unit_test(test_hci_terminate),
     };
     return cmocka_run_group_tests_mpi(tests, setup, teardown);
 }
References setup(), teardown(), test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), and test_hci_timeout().
setup()
static int setup (void ** state) static
Definition at line 161 of file test_hci.c.
 {
     char * ret = mkdtemp(prefix);
     message(0, "UsingPrefix : '%s'\n", prefix);
     return !ret;
 }
References message(), and prefix.
Referenced by main().
teardown()
static int teardown (void ** state) static
Definition at line 168 of file test_hci.c.
 {
     remove(prefix);
     return 0;
 }
References prefix.
Referenced by main().
test_hci_auto_checkpoint()
static void test_hci_auto_checkpoint (void ** state) static
Definition at line 56 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 0.0);
     hci_init(manager, prefix, 10.0, 1.0, 1);
     hci_override_now(manager, 0.0);
     hci_query(manager, action);
     hci_override_now(manager, 1.0);
     hci_query(manager, action);
     assert_int_equal(action->type, HCI_AUTO_CHECKPOINT);
     assert_int_equal(action->write_snapshot, 1);
     assert_int_equal(action->write_fof, 1);
     assert_true(manager->LongestTimeBetweenQueries == 1.0);
 }
References HCI_AUTO_CHECKPOINT, hci_init(), hci_override_now(), hci_query(), HCIManager::LongestTimeBetweenQueries, manager, prefix, HCIAction::type, HCIAction::write_fof, and HCIAction::write_snapshot.
Referenced by main().
test_hci_auto_checkpoint2()
static void test_hci_auto_checkpoint2 (void ** state) static
Definition at line 76 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 1.0);
     hci_init(manager, prefix, 10.0, 1.0, 0);
     hci_override_now(manager, 2.0);
     hci_query(manager, action);
     hci_override_now(manager, 4.0);
     hci_query(manager, action);
     assert_true(manager->LongestTimeBetweenQueries == 2.0);
     assert_int_equal(action->type, HCI_AUTO_CHECKPOINT);
     assert_int_equal(action->write_snapshot, 1);
     assert_int_equal(action->write_fof, 0);
 }
References HCI_AUTO_CHECKPOINT, hci_init(), hci_override_now(), hci_query(), HCIManager::LongestTimeBetweenQueries, manager, prefix, HCIAction::type, HCIAction::write_fof, and HCIAction::write_snapshot.
Referenced by main().
test_hci_checkpoint()
static void test_hci_checkpoint (void ** state) static
Definition at line 130 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 0.0);
     hci_init(manager, prefix, 10.0, 1.0, 1);
     touch(prefix, "checkpoint");
     hci_override_now(manager, 4.0);
     hci_query(manager, action);
     assert_false(exists(prefix, "checkpoint"));
     assert_int_equal(action->type, HCI_CHECKPOINT);
     assert_int_equal(action->write_snapshot, 1);
 }
References exists(), HCI_CHECKPOINT, hci_init(), hci_override_now(), hci_query(), manager, prefix, touch(), HCIAction::type, and HCIAction::write_snapshot.
Referenced by main().
test_hci_no_action()
static void test_hci_no_action (void ** state) static
Definition at line 42 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 0.0);
     hci_init(manager, prefix, 10.0, 1.0, 0);
     hci_query(manager, action);
     assert_int_equal(action->type, HCI_NO_ACTION);
     assert_int_equal(action->write_snapshot, 0);
 }
References hci_init(), HCI_NO_ACTION, hci_override_now(), hci_query(), manager, prefix, HCIAction::type, and HCIAction::write_snapshot.
Referenced by main().
test_hci_stop()
static void test_hci_stop (void ** state) static
Definition at line 114 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 0.0);
     hci_init(manager, prefix, 10.0, 1.0, 1);
     touch(prefix, "stop");
     hci_override_now(manager, 4.0);
     hci_query(manager, action);
     assert_false(exists(prefix, "stop"));
     assert_int_equal(action->type, HCI_STOP);
     assert_int_equal(action->write_snapshot, 1);
 }
References exists(), hci_init(), hci_override_now(), hci_query(), HCI_STOP, manager, prefix, touch(), HCIAction::type, and HCIAction::write_snapshot.
Referenced by main().
test_hci_terminate()
static void test_hci_terminate (void ** state) static
Definition at line 146 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 0.0);
     hci_init(manager, prefix, 10.0, 1.0, 1);
     touch(prefix, "terminate");
     hci_override_now(manager, 4.0);
     hci_query(manager, action);
     assert_false(exists(prefix, "terminate"));
     assert_int_equal(action->type, HCI_TERMINATE);
     assert_int_equal(action->write_snapshot, 0);
 }
References exists(), hci_init(), hci_override_now(), hci_query(), HCI_TERMINATE, manager, prefix, touch(), HCIAction::type, and HCIAction::write_snapshot.
Referenced by main().
test_hci_timeout()
static void test_hci_timeout (void ** state) static
Definition at line 96 of file test_hci.c.
 {
     HCIAction action[1];
     hci_override_now(manager, 1.0);
     hci_init(manager, prefix, 10.0, 1.0, 1);
     hci_override_now(manager, 5.0);
     hci_query(manager, action);
     assert_true(manager->LongestTimeBetweenQueries == 4.0);
     hci_override_now(manager, 8.5);
     hci_query(manager, action);
     assert_int_equal(action->type, HCI_TIMEOUT);
     assert_int_equal(action->write_snapshot, 1);
 }
References hci_init(), hci_override_now(), hci_query(), HCI_TIMEOUT, HCIManager::LongestTimeBetweenQueries, manager, prefix, HCIAction::type, and HCIAction::write_snapshot.
Referenced by main().
touch()
static void touch (char * prefix, char * b) static
Definition at line 16 of file test_hci.c.
 {
     char * fn = fastpm_strdup_printf("%s/%s", prefix, b);
     FILE * fp = fopen(fn, "w");
     myfree(fn);
     fclose(fp);
 }
References fastpm_strdup_printf(), myfree, and prefix.
Referenced by test_hci_checkpoint(), test_hci_stop(), and test_hci_terminate().
Variable Documentation
manager
HCIManager manager[1]
Initial value:
= {
    {.OVERRIDE_NOW = 1, ._now = 0.0}}
Definition at line 37 of file test_hci.c.
Referenced by hci_get_elapsed_time(), hci_init(), hci_now(), hci_override_now(), hci_query(), hci_query_auto_checkpoint(), hci_query_filesystem(), hci_query_timeout(), hci_update_query_timer(), test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), and test_hci_timeout().
prefix
char prefix[1024] = "XXXXXXXX"
Definition at line 13 of file test_hci.c.
Referenced by exists(), hci_init(), MPIU_Tracev(), putline(), setup(), teardown(), test_hci_auto_checkpoint(), test_hci_auto_checkpoint2(), test_hci_checkpoint(), test_hci_no_action(), test_hci_stop(), test_hci_terminate(), test_hci_timeout(), touch(), and walltime_update_parents().