MP-Gadget: libgadget/tests/test_openmpsort.c File Reference
test_openmpsort.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <stdio.h>
#include <omp.h>
#include <stdlib.h>
#include "stub.h"
Classes
struct __data
Functions
static int compare (const void *a, const void *b)
static void test_openmpsort_struct (void **state)
static void test_openmpsort (void **state)
int main (void)
Function Documentation
compare()
static int compare (const void * a, const void * b) static
Definition at line 22 of file test_openmpsort.c.
{
         return ( *(int*)a - *(int*)b );
 }
Referenced by test_openmpsort(), and test_openmpsort_struct().
main()
int main (void)
Definition at line 102 of file test_openmpsort.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_openmpsort),
         cmocka_unit_test(test_openmpsort_struct),
     };
     return cmocka_run_group_tests_mpi(tests, NULL, NULL);
 }
References test_openmpsort(), and test_openmpsort_struct().
test_openmpsort()
static void test_openmpsort (void ** state) static
Definition at line 66 of file test_openmpsort.c.
{
     int i;
     // set up array to be sorted
     //a bad case is 87763 threads = 12
     int size = 87763;
     int *a = (int *) malloc(size * sizeof(int));
     srand48(8675309);
     for(i = 0; i < size; i++)
         a[i] = (int) (size * drand48());
     double start, end;
     start = omp_get_wtime();
     qsort_openmp(a, size, sizeof(int), compare);
     end = omp_get_wtime();
     message(1,"parallel sort time = %g s %d threads\n",end-start, omp_get_max_threads());
     for(i=1; i<size; i++) {
         if( a[i-1]>a[i] )
             message(1,"BAD: %d %d %d\n",i,a[i-1],a[i]);
         assert_true(a[i-1] <= a[i]);
     }
     srand48(8675309);
     for(i = 0; i < size; i++)
         a[i] = (int) (size * drand48());
     start = omp_get_wtime();
     qsort(a, size, sizeof(int), compare);
     end = omp_get_wtime();
     message(1, "serial sort time = %g s\n",end-start);
 }
References compare(), message(), and qsort_openmp.
Referenced by main().
test_openmpsort_struct()
static void test_openmpsort_struct (void ** state) static
Definition at line 31 of file test_openmpsort.c.
{
     int i;
     // set up array to be sorted
     //a bad case is 87763 threads = 12
     int size = 187763;
     struct __data *a = (struct __data *) malloc(size * sizeof(struct __data));
     srand48(8675309);
     for(i = 0; i < size; i++)
         a[i].dd[0] = (int) (size * drand48());
     double start, end;
     start = omp_get_wtime();
     qsort_openmp(a, size, sizeof(struct __data), compare);
     end = omp_get_wtime();
     message(1,"parallel sort time = %g s %d threads\n",end-start, omp_get_max_threads());
     for(i=1; i<size; i++) {
         if( a[i-1].dd[0] >a[i].dd[0] )
             message(1,"BAD: %d %d %d\n",i,a[i-1].dd[0],a[i].dd[0]);
         assert_true(a[i-1].dd[0] <= a[i].dd[0]);
     }
     srand48(8675309);
     for(i = 0; i < size; i++)
         a[i].dd[0] = (int) (size * drand48());
     start = omp_get_wtime();
     qsort(a, size, sizeof(struct __data), compare);
     end = omp_get_wtime();
     message(1, "serial (glibc) sort time = %g s\n",end-start);
 }
References compare(), __data::dd, message(), and qsort_openmp.
Referenced by main().