MP-Gadget: libgadget/tests/test_cooling.c File Reference
test_cooling.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <libgadget/config.h>
#include <libgadget/physconst.h>
#include <libgadget/cosmology.h>
#include <libgadget/cooling.h>
#include <libgadget/cooling_rates.h>
#include <libgadget/utils/peano.h>
#include <libgadget/partmanager.h>
#include <libgadget/utils/endrun.h>
#include "stub.h"
Macros
#define NSTEP 20
Functions
double get_long_mean_free_path_heating (double redshift)
void init_qso_lightup (char *reion_hist_file)
int during_helium_reionization (double redshift)
static void test_DoCooling (void **state)
int main (void)
Variables
static double unew_table [NSTEP *NSTEP]
static double tcool_table [NSTEP *NSTEP]
struct part_manager_type PartManager [1]
Macro Definition Documentation
NSTEP
#define NSTEP 20
Definition at line 41 of file test_cooling.c.
Function Documentation
during_helium_reionization()
int during_helium_reionization (double redshift)
Definition at line 36 of file test_cooling.c.
 {
     return 0;
 }
get_long_mean_free_path_heating()
double get_long_mean_free_path_heating (double redshift)
Definition at line 23 of file test_cooling.c.
 {
     redshift *= 2;
     return 0;
 }
init_qso_lightup()
void init_qso_lightup (char * reion_hist_file)
Definition at line 30 of file test_cooling.c.
 {
     return;
 }
main()
int main (void)
Definition at line 243 of file test_cooling.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_DoCooling),
     };
     return cmocka_run_group_tests_mpi(tests, NULL, NULL);
 }
References test_DoCooling().
test_DoCooling()
static void test_DoCooling (void ** state) static
Definition at line 156 of file test_cooling.c.
 {
     int i, j;
     struct cooling_params coolpar;
     coolpar.CMBTemperature = 2.7255;
     coolpar.PhotoIonizeFactor = 1;
     coolpar.SelfShieldingOn = 0;
     coolpar.fBar = 0.17;
     coolpar.PhotoIonizationOn = 1;
     coolpar.recomb = Cen92;
     coolpar.cooling = KWH92;
     coolpar.HeliumHeatOn = 0;
     coolpar.HeliumHeatAmp = 1.;
     coolpar.HeliumHeatExp = 0.;
     coolpar.HeliumHeatThresh = 10;
     coolpar.MinGasTemp = 0;
     coolpar.UVRedshiftThreshold = -1;
     coolpar.HydrogenHeatAmp = 0;
     coolpar.rho_crit_baryon = 0.045 * 3.0 * pow(0.7*HUBBLE,2.0) /(8.0*M_PI*GRAVITY);
     char * TreeCool = GADGET_TESTDATA_ROOT "/examples/TREECOOL_ep_2018p";
     char * MetalCool = "";
     /*unit system*/
     double HubbleParam = 0.7;
     double UnitDensity_in_cgs = 6.76991e-22;
     double UnitTime_in_s = 3.08568e+16;
     double UnitMass_in_g = 1.989e+43;
     double UnitLength_in_cm = 3.08568e+21;
     double UnitEnergy_in_cgs = UnitMass_in_g  * pow(UnitLength_in_cm, 2) / pow(UnitTime_in_s, 2);
     Cosmology CP = {0};
     CP.OmegaCDM = 0.3;
     CP.OmegaBaryon = coolpar.fBar * CP.OmegaCDM;
     CP.HubbleParam = HubbleParam;
     struct cooling_units coolunits;
     coolunits.CoolingOn = 1;
     coolunits.density_in_phys_cgs = UnitDensity_in_cgs * HubbleParam * HubbleParam;
     coolunits.uu_in_cgs = UnitEnergy_in_cgs / UnitMass_in_g;
     coolunits.tt_in_s = UnitTime_in_s / HubbleParam;
     coolunits.rho_crit_baryon = 3 * pow(CP.HubbleParam * HUBBLE,2) * CP.OmegaBaryon / (8 * M_PI * GRAVITY);
     double meanweight = 4.0 / (1 + 3 * HYDROGEN_MASSFRAC);
     double MinEgySpec = 1 / meanweight * (1.0 / GAMMA_MINUS1) * (BOLTZMANN / PROTONMASS) * 1;
     MinEgySpec /= coolunits.uu_in_cgs;
     set_coolpar(coolpar);
     init_cooling(TreeCool, MetalCool, NULL, coolunits, &CP);
     struct UVBG uvbg = get_global_UVBG(0);
     assert_true(fabs(uvbg.epsH0/3.65296e-25 -1) < 1e-5);
     assert_true(fabs(uvbg.epsHe0/3.98942e-25 -1) < 1e-5);
     assert_true(fabs(uvbg.epsHep/3.33253e-26 -1) < 1e-5);
     double umax = 36000, umin = 200;
     double dmax = 1e-2, dmin = 1e-9;
     double ne= 1.0;
     /*Check two particular values*/
     double tcool = GetCoolingTime(0, 949.755, 7.07946e-06, &uvbg, &ne, 0);
     assert_true(fabs(tcool/ 0.0172379) -1 < 1e-3);
     double unew = DoCooling(0,  9828.44, 7.07946e-06, 0.2, &uvbg, &ne, 0, MinEgySpec, 1);
     assert_true(fabs(unew/ 531.724) -1 < 1e-3);
     double dt = 0.2;
     for(i=0; i < NSTEP; i++)
     {
         double dens = exp(log(dmin) +  i * (log(dmax) - log(dmin)) / 1. /NSTEP);
         for (j = 0; j<NSTEP; j++)
         {
             double ne=1.0, ne2=1.0;
             double uu = exp(log(umin) +  j * (log(umax) - log(umin)) / 1. /NSTEP);
             double tcool = GetCoolingTime(0, uu, dens, &uvbg, &ne2, 0);
             double unew = DoCooling(0, uu, dens, dt, &uvbg, &ne, 0, MinEgySpec, 1);
             assert_false(isnan(unew));
 //             message(0, "d = %g u = %g tcool = %g tcool_table = %g unew = %g ne_after = %g unew_table = %g\n", dens, uu, tcool, tcool_table[i*NSTEP + j], unew, ne, unew_table[i*NSTEP+j]);
             assert_true(fabs(unew/unew_table[i*NSTEP + j] - 1) < 5e-3);
             assert_true(fabs(1/(1e-20 + tcool) - 1./(1e-20 + tcool_table[i*NSTEP + j])) < 1 || fabs((1e-20 + tcool)/(1e-20 + tcool_table[i*NSTEP + j]) - 1) < 2e-2);
             /*Make the tables*/
             //printf("%g , ", unew);
            //printf("%g , ", tcool);
         }
     }
 //    printf("\n");
 }
References BOLTZMANN, Cen92, cooling_params::CMBTemperature, cooling_params::cooling, cooling_units::CoolingOn, coolunits, CP, cooling_units::density_in_phys_cgs, DoCooling(), UVBG::epsH0, UVBG::epsHe0, UVBG::epsHep, cooling_params::fBar, GAMMA_MINUS1, get_global_UVBG(), GetCoolingTime(), GRAVITY, cooling_params::HeliumHeatAmp, cooling_params::HeliumHeatExp, cooling_params::HeliumHeatOn, cooling_params::HeliumHeatThresh, HUBBLE, Cosmology::HubbleParam, HYDROGEN_MASSFRAC, cooling_params::HydrogenHeatAmp, init_cooling(), KWH92, MetalCool, cooling_params::MinGasTemp, NSTEP, Cosmology::OmegaBaryon, Cosmology::OmegaCDM, cooling_params::PhotoIonizationOn, cooling_params::PhotoIonizeFactor, PROTONMASS, cooling_params::recomb, cooling_units::rho_crit_baryon, cooling_params::rho_crit_baryon, cooling_params::SelfShieldingOn, set_coolpar(), tcool_table, cooling_units::tt_in_s, unew_table, UnitLength_in_cm, cooling_units::uu_in_cgs, and cooling_params::UVRedshiftThreshold.
Referenced by main().
Variable Documentation
PartManager
struct part_manager_type PartManager[1]
Definition at line 97 of file test_cooling.c.
tcool_table
double tcool_table[NSTEP *NSTEP] static
Definition at line 97 of file test_cooling.c.
Referenced by test_DoCooling().
unew_table
double unew_table[NSTEP *NSTEP] static
Definition at line 43 of file test_cooling.c.
Referenced by test_DoCooling().