MP-Gadget: libgadget/tests/test_timefac.c File Reference
test_timefac.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <gsl/gsl_integration.h>
#include <stdint.h>
#include "stub.h"
#include <libgadget/timefac.h>
Classes
struct fac_params
Macros
#define AMIN 0.005
#define AMAX 1.0
#define LTIMEBINS 29
Functions
double hubble_function (const Cosmology *CP, double a)
double fac_integ (double a, void *param)
double loga_from_ti (int ti)
static int get_ti (double aa)
double exact_drift_factor (Cosmology *CP, double a1, double a2, int exp)
void test_drift_factor (void **state)
int main (void)
Macro Definition Documentation
AMAX
#define AMAX 1.0
Definition at line 17 of file test_timefac.c.
AMIN
#define AMIN 0.005
Definition at line 16 of file test_timefac.c.
LTIMEBINS
#define LTIMEBINS 29
Definition at line 18 of file test_timefac.c.
Function Documentation
exact_drift_factor()
double exact_drift_factor (Cosmology * CP, double a1, double a2, int exp)
Definition at line 64 of file test_timefac.c.
 {
     double result, abserr;
     gsl_function F;
     gsl_integration_workspace *workspace;
     workspace = gsl_integration_workspace_alloc(10000);
     F.function = &fac_integ;
     struct fac_params ff = {CP, exp};
     F.params = &ff;
     gsl_integration_qag(&F, a1,a2, 0, 1.0e-8, 10000, GSL_INTEG_GAUSS61, workspace, &result, &abserr);
     gsl_integration_workspace_free(workspace);
     return result;
 }
References CP, fac_params::exp, and fac_integ().
Referenced by test_drift_factor().
fac_integ()
double fac_integ (double a, void * param)
Definition at line 40 of file test_timefac.c.
 {
   double h;
   struct fac_params * ff = (struct fac_params *) param;
   h = hubble_function(ff->CP, a);
   return 1 / (h * pow(a,ff->exp));
 }
References fac_params::CP, fac_params::exp, and hubble_function().
Referenced by exact_drift_factor().
get_ti()
static int get_ti (double aa) inline static
Definition at line 58 of file test_timefac.c.
 {
     double logDTime = (log(AMAX) - log(AMIN)) / (1 << LTIMEBINS);
     return (log(aa) - log(AMIN))/logDTime;
 }
References AMAX, AMIN, and LTIMEBINS.
Referenced by test_drift_factor().
hubble_function()
double hubble_function (const Cosmology * CP, double a)
Definition at line 21 of file test_timefac.c.
 {
     double hubble_a;
     /* lambda and matter */
     hubble_a = 1 - CP->Omega0;
     hubble_a += CP->Omega0 / (a * a * a);
     /*Radiation*/
     hubble_a += 5.045e-5*(1+7./8.*pow(pow(4/11.,1/3.)*1.00328,4)*3) / (a * a * a * a);
     /* Hard-code default Gadget unit system. */
     hubble_a = 0.1 * sqrt(hubble_a);
     return (hubble_a);
 }
References CP, and Cosmology::Omega0.
Referenced by fac_integ().
loga_from_ti()
double loga_from_ti (int ti)
Definition at line 51 of file test_timefac.c.
 {
     double logDTime = (log(AMAX) - log(AMIN)) / (1 << LTIMEBINS);
     return log(AMIN) + ti * logDTime;
 }
References AMAX, AMIN, and LTIMEBINS.
Referenced by cooling_direct(), density(), get_atime(), get_exact_factor(), and test_conversions().
main()
int main (void)
Definition at line 109 of file test_timefac.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_drift_factor),
     };
     return cmocka_run_group_tests_mpi(tests, NULL, NULL);
 }
References test_drift_factor().
test_drift_factor()
void test_drift_factor (void ** state)
Definition at line 78 of file test_timefac.c.
 {
     /*Initialise the table: default values from z=200 to z=0*/
     Cosmology CP;
     CP.Omega0 = 1.;
     /* Check default scaling: for total matter domination
      * we should have a drift factor like 1/sqrt(a)*/
     assert_true(fabs(get_exact_drift_factor(&CP, get_ti(0.8), get_ti(0.85)) + 2/0.1*(1/sqrt(0.85) - 1/sqrt(0.8))) < 5e-5);
     /*Test the kick table*/
     assert_true(fabs(get_exact_gravkick_factor(&CP, get_ti(0.8), get_ti(0.85)) - 2/0.1*(sqrt(0.85) - sqrt(0.8))) < 5e-5);
     //Chosen so we get the same bin
     assert_true(fabs(get_exact_drift_factor(&CP, get_ti(0.8), get_ti(0.8003)) + 2/0.1*(1/sqrt(0.8003) - 1/sqrt(0.8))) < 5e-6);
     //Now choose a more realistic cosmology
     CP.Omega0 = 0.25;
     /*Check late and early times*/
     assert_true(fabs(get_exact_drift_factor(&CP, get_ti(0.95), get_ti(0.98)) - exact_drift_factor(&CP, 0.95, 0.98,3)) < 5e-5);
     assert_true(fabs(get_exact_drift_factor(&CP, get_ti(0.05), get_ti(0.06)) - exact_drift_factor(&CP, 0.05, 0.06,3)) < 5e-5);
     /*Check boundary conditions*/
     double logDtime = (log(AMAX)-log(AMIN))/(1<<LTIMEBINS);
     assert_true(fabs(get_exact_drift_factor(&CP, ((1<<LTIMEBINS)-1), 1<<LTIMEBINS) - exact_drift_factor(&CP, AMAX-logDtime, AMAX,3)) < 5e-5);
     assert_true(fabs(get_exact_drift_factor(&CP, 0, 1) - exact_drift_factor(&CP, 1.0 - exp(log(AMAX)-log(AMIN))/(1<<LTIMEBINS), 1.0,3)) < 5e-5);
     /*Gravkick*/
     assert_true(fabs(get_exact_gravkick_factor(&CP, get_ti(0.8), get_ti(0.85)) - exact_drift_factor(&CP, 0.8, 0.85, 2)) < 5e-5);
     assert_true(fabs(get_exact_gravkick_factor(&CP, get_ti(0.05), get_ti(0.06)) - exact_drift_factor(&CP, 0.05, 0.06, 2)) < 5e-5);
     /*Test the hydrokick table: always the same as drift*/
     assert_true(fabs(get_exact_hydrokick_factor(&CP, get_ti(0.8), get_ti(0.85)) - get_exact_drift_factor(&CP, get_ti(0.8), get_ti(0.85))) < 5e-5);
 }
References AMAX, AMIN, CP, exact_drift_factor(), fac_params::exp, get_exact_drift_factor(), get_exact_gravkick_factor(), get_exact_hydrokick_factor(), get_ti(), LTIMEBINS, and Cosmology::Omega0.
Referenced by main().