MP-Gadget: libgadget/tests/test_neutrinos_lra.c File Reference
test_neutrinos_lra.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "../neutrinos_lra.h"
#include "../omega_nu_single.h"
#include "../physconst.h"
#include "../utils/endrun.h"
#include "stub.h"
Macros
#define T_CMB0 2.7255
Functions
double specialJ (const double x, const double vcmnubylight, const double nufrac_low)
double fslength (Cosmology *CP, const double logai, const double logaf, const double light)
void petaio_save_block (BigFile *bf, char *blockname, BigArray *array, int verbose)
int petaio_read_block (BigFile *bf, char *blockname, BigArray *array, int required)
void setup_cosmology (Cosmology *CP, double MNu[])
static void test_allocate_delta_tot_table (void **state)
static void test_specialJ (void **state)
static void test_fslength (void **state)
int main (void)
Variables
_delta_tot_table delta_tot_table
Macro Definition Documentation
T_CMB0
#define T_CMB0 2.7255
Definition at line 14 of file test_neutrinos_lra.c.
Function Documentation
fslength()
double fslength (Cosmology * CP, const double logai, const double logaf, const double light)
Free-streaming length (times Mnu/k_BT_nu, which is dimensionless) for a non-relativistic particle of momentum q = T0, from scale factor ai to af. Arguments:
Parameters
logai log of initial scale factor
logaf log of final scale factor
mnu Neutrino mass in eV
light speed of light in internal length units.
Returns
free-streaming length in Unit_Length/Unit_Time (same units as light parameter).
Definition at line 553 of file neutrinos_lra.c.
 {
   double abserr;
   double fslength_val;
   gsl_function F;
   gsl_integration_workspace * w = gsl_integration_workspace_alloc (GSL_VAL);
   F.function = &fslength_int;
   F.params = CP;
   if(logai >= logaf)
       return 0;
   gsl_integration_qag (&F, logai, logaf, 0, 1e-6,GSL_VAL,6,w,&(fslength_val), &abserr);
   gsl_integration_workspace_free (w);
   return light*fslength_val;
 }
References CP, fslength_int(), and GSL_VAL.
Referenced by get_delta_nu(), and test_fslength().
main()
int main (void)
Definition at line 110 of file test_neutrinos_lra.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_allocate_delta_tot_table),
         cmocka_unit_test(test_specialJ),
         cmocka_unit_test(test_fslength),
     };
     return cmocka_run_group_tests_mpi(tests, NULL, NULL);
 }
References test_allocate_delta_tot_table(), test_fslength(), and test_specialJ().
petaio_read_block()
int petaio_read_block (BigFile * bf, char * blockname, BigArray * array, int required)
Definition at line 20 of file test_neutrinos_lra.c.
 {
     return 0;
 }
petaio_save_block()
void petaio_save_block (BigFile * bf, char * blockname, BigArray * array, int verbose)
Definition at line 19 of file test_neutrinos_lra.c.
 {};
setup_cosmology()
void setup_cosmology (Cosmology * CP, double MNu[])
Definition at line 29 of file test_neutrinos_lra.c.
 {
     CP->CMBTemperature = 2.7255;
     CP->Omega0 = 0.2793;
     CP->OmegaLambda = 1- CP->Omega0;
     CP->OmegaBaryon = 0.0464;
     CP->HubbleParam = 0.7;
     CP->RadiationOn = 1;
     CP->Omega_fld = 0;
     CP->Omega_ur = 0;
     int i;
     for(i = 0; i<3; i++)
         CP->MNu[i] = MNu[i];
     struct UnitSystem units = get_unitsystem(3.085678e21, 1.989e43, 1e5);
     /*Do the main cosmology initialisation*/
     init_cosmology(CP,0.01, units);
 }
References Cosmology::CMBTemperature, CP, get_unitsystem(), Cosmology::HubbleParam, init_cosmology(), Cosmology::MNu, Cosmology::Omega0, Cosmology::Omega_fld, Cosmology::Omega_ur, Cosmology::OmegaBaryon, Cosmology::OmegaLambda, and Cosmology::RadiationOn.
Referenced by test_fslength().
specialJ()
double specialJ (const double x, const double vcmnubylight, const double nufrac_low)
Fit to the special function J(x) that is accurate to better than 3% relative and 0.07% absolute
Definition at line 616 of file neutrinos_lra.c.
 {
   if( qc > 0 ) {
    return Jfrac_high(x, qc, nufrac_low);
   }
   return specialJ_fit(x);
 }
Referenced by get_delta_nu(), get_delta_nu_int(), and test_specialJ().
test_allocate_delta_tot_table()
static void test_allocate_delta_tot_table (void ** state) static
Definition at line 49 of file test_neutrinos_lra.c.
 {
     _omega_nu omnu;
     double MNu[3] = {0, 0, 0};
     int i;
     init_omega_nu(&omnu, MNu, 0.01, 0.7,T_CMB0);
     init_neutrinos_lra(300, 0.01, 1, 0.2793, &omnu, 1, 1);
     assert_true(delta_tot_table.ia == 0);
     assert_true(delta_tot_table.namax > 10);
     assert_true(delta_tot_table.scalefact);
     assert_true(delta_tot_table.delta_nu_init);
     assert_true(delta_tot_table.delta_tot);
     for(i=0; i<delta_tot_table.nk_allocated; i++){
         assert_true(delta_tot_table.delta_tot[i]);
     }
 }
References _delta_tot_table::delta_nu_init, _delta_tot_table::delta_tot, delta_tot_table, _delta_tot_table::ia, init_neutrinos_lra(), init_omega_nu(), _delta_tot_table::namax, _delta_tot_table::nk_allocated, _delta_tot_table::scalefact, and T_CMB0.
Referenced by main().
test_fslength()
static void test_fslength (void ** state) static
Definition at line 95 of file test_neutrinos_lra.c.
 {
     Cosmology CP;
     double MNu[3] = {0.15, 0.15, 0.15};
     setup_cosmology(&CP, MNu);
     /*Note that MNu is the mass of a single neutrino species:
      *we use large masses so that we don't have to compute omega_nu in mathematica.*/
     double kT = BOLEVK*TNUCMB*T_CMB0;
     /*fslength function returns fslength * (MNu / kT)*/
     assert_true(fabs(fslength(&CP, log(0.5), log(1), 299792.)/ 1272.92/(0.45/kT) -1 ) < 1e-5);
     double MNu2[3] = {0.2, 0.2, 0.2};
     setup_cosmology(&CP, MNu2);
     assert_true(fabs(fslength(&CP, log(0.1), log(0.5),299792.)/ 5427.8/(0.6/kT) -1 ) < 1e-5);
 }
References BOLEVK, CP, fslength(), setup_cosmology(), T_CMB0, and TNUCMB.
Referenced by main().
test_specialJ()
static void test_specialJ (void ** state) static
Definition at line 67 of file test_neutrinos_lra.c.
 {
     /*Check against mathematica computed values:
     Integrate[(Sinc[q*x])*(q^2/(Exp[q] + 1)), {q, 0, Infinity}]*/
     assert_true(specialJ(0,-1,0) == 1);
     assert_true(fabs(specialJ(1,-1, 0) - 0.2117) < 1e-3);
     assert_true(fabs(specialJ(2,-1, 0) - 0.0223807) < 1e-3);
     assert_true(fabs(specialJ(0.5,-1, 0) - 0.614729) < 1e-3);
     assert_true(fabs(specialJ(0.3,-1, 0) - 0.829763) < 1e-3);
     /*Test that it is ok when truncated*/
     /*Mathematica: Jfrac[x_, qc_] := NIntegrate[(Sinc[q*x])*(q^2/(Exp[q] + 1)), {q, qc, Infinity}]/(3*Zeta[3]/2) */
     assert_true(fabs(specialJ(0,1, 0) - 0.940437) < 1e-4);
     assert_true(fabs(specialJ(0.5,1e-2, 0.5) - 0.614729/0.5) < 1e-3);
     assert_true(fabs(specialJ(0.5,1, 0.5) - 0.556557/0.5) < 1e-4);
     assert_true(fabs(specialJ(1,0.1, 0.5) - 0.211662/0.5) < 1e-4);
 }
References specialJ().
Referenced by main().
Variable Documentation
delta_tot_table
_delta_tot_table delta_tot_table extern
Definition at line 75 of file neutrinos_lra.c.
Referenced by delta_nu_from_power(), init_neutrinos_lra(), petaio_read_neutrinos(), petaio_save_neutrinos(), powerspectrum_nu_save(), and test_allocate_delta_tot_table().