MP-Gadget: libgadget/tests/test_slotsmanager.c File Reference
test_slotsmanager.c File Reference
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>
#include <math.h>
#include <mpi.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <gsl/gsl_rng.h>
#include "stub.h"
#include <libgadget/partmanager.h>
#include <libgadget/domain.h>
#include <libgadget/slotsmanager.h>
Functions
static int setup_particles (void **state)
static int teardown_particles (void **state)
static void test_slots_gc (void **state)
static void test_slots_gc_sorted (void **state)
static void test_slots_reserve (void **state)
static void test_slots_zero (void **state)
static void test_slots_fork (void **state)
static void test_slots_convert (void **state)
int main (void)
Variables
struct part_manager_type PartManager [1] = {{0}}
Function Documentation
main()
int main (void)
Definition at line 223 of file test_slotsmanager.c.
                {
     const struct CMUnitTest tests[] = {
         cmocka_unit_test(test_slots_gc),
         cmocka_unit_test(test_slots_gc_sorted),
         cmocka_unit_test(test_slots_reserve),
         cmocka_unit_test(test_slots_fork),
         cmocka_unit_test(test_slots_convert),
         cmocka_unit_test(test_slots_zero),
     };
     return cmocka_run_group_tests_mpi(tests, NULL, NULL);
 }
References test_slots_convert(), test_slots_fork(), test_slots_gc(), test_slots_gc_sorted(), test_slots_reserve(), and test_slots_zero().
setup_particles()
static int setup_particles (void ** state) static
Definition at line 21 of file test_slotsmanager.c.
 {
     PartManager->MaxPart = 1024;
     PartManager->NumPart = 128 * 6;
     int64_t newSlots[6] = {128, 128, 128, 128, 128, 128};
     PartManager->Base = (struct particle_data *) mymalloc("P", PartManager->MaxPart* sizeof(struct particle_data));
     memset(PartManager->Base, 0, sizeof(struct particle_data) * PartManager->MaxPart);
     slots_init(0.01 * PartManager->MaxPart, SlotsManager);
     int ptype;
     slots_set_enabled(0, sizeof(struct sph_particle_data), SlotsManager);
     slots_set_enabled(4, sizeof(struct star_particle_data), SlotsManager);
     slots_set_enabled(5, sizeof(struct bh_particle_data), SlotsManager);
     for(ptype = 1; ptype < 4; ptype++) {
         slots_set_enabled(ptype, sizeof(struct particle_data_ext), SlotsManager);
     }
     slots_reserve(1, newSlots, SlotsManager);
     slots_setup_topology(PartManager, newSlots, SlotsManager);
     int64_t i;
     #pragma omp parallel for
     for(i = 0; i < PartManager->NumPart; i ++) {
         P[i].ID = i;
     }
     slots_setup_id(PartManager, SlotsManager);
     return 0;
 }
References part_manager_type::Base, part_manager_type::MaxPart, mymalloc, part_manager_type::NumPart, P, PartManager, ptype, slots_init(), slots_reserve(), slots_set_enabled(), slots_setup_id(), slots_setup_topology(), and SlotsManager.
Referenced by test_slots_convert(), test_slots_fork(), test_slots_gc(), test_slots_gc_sorted(), test_slots_reserve(), and test_slots_zero().
teardown_particles()
static int teardown_particles (void ** state) static
Definition at line 56 of file test_slotsmanager.c.
 {
     slots_free(SlotsManager);
     myfree(PartManager->Base);
     return 0;
 }
References part_manager_type::Base, myfree, PartManager, slots_free(), and SlotsManager.
Referenced by test_slots_convert(), test_slots_fork(), test_slots_gc(), test_slots_gc_sorted(), and test_slots_zero().
test_slots_convert()
static void test_slots_convert (void ** state) static
Definition at line 205 of file test_slotsmanager.c.
 {
     setup_particles(state);
     int i;
     for(i = 0; i < 6; i ++) {
         slots_convert(128 * i, P[i * 128].Type, -1, PartManager, SlotsManager);
     }
     assert_int_equal(PartManager->NumPart, 128 * i);
     assert_int_equal(SlotsManager->info[0].size, 129);
     assert_int_equal(SlotsManager->info[4].size, 129);
     assert_int_equal(SlotsManager->info[5].size, 129);
     teardown_particles(state);
     return;
 }
References slots_manager_type::info, part_manager_type::NumPart, P, PartManager, setup_particles(), slot_info::size, slots_convert(), SlotsManager, teardown_particles(), and particle_data::Type.
Referenced by main().
test_slots_fork()
static void test_slots_fork (void ** state) static
Definition at line 184 of file test_slotsmanager.c.
 {
     setup_particles(state);
     int i;
     for(i = 0; i < 6; i ++) {
         slots_split_particle(128 * i, 0, PartManager);
         slots_convert(128 * i, P[i * 128].Type, -1, PartManager, SlotsManager);
     }
     assert_int_equal(PartManager->NumPart, 129 * i);
     assert_int_equal(SlotsManager->info[0].size, 129);
     assert_int_equal(SlotsManager->info[4].size, 129);
     assert_int_equal(SlotsManager->info[5].size, 129);
     teardown_particles(state);
     return;
 }
References slots_manager_type::info, part_manager_type::NumPart, P, PartManager, setup_particles(), slot_info::size, slots_convert(), slots_split_particle(), SlotsManager, teardown_particles(), and particle_data::Type.
Referenced by main().
test_slots_gc()
static void test_slots_gc (void ** state) static
Definition at line 64 of file test_slotsmanager.c.
 {
     setup_particles(state);
     int i;
     int compact[6];
     for(i = 0; i < 6; i ++) {
         slots_mark_garbage(128 * i, PartManager, SlotsManager);
         compact[i] = 1;
     }
     slots_gc(compact, PartManager, SlotsManager);
     assert_int_equal(PartManager->NumPart, 127 * i);
     assert_int_equal(SlotsManager->info[0].size, 127);
     assert_int_equal(SlotsManager->info[4].size, 127);
     assert_int_equal(SlotsManager->info[5].size, 127);
     slots_check_id_consistency(PartManager, SlotsManager);
     teardown_particles(state);
     return;
 }
References slots_manager_type::info, part_manager_type::NumPart, PartManager, setup_particles(), slot_info::size, slots_check_id_consistency(), slots_gc(), slots_mark_garbage(), SlotsManager, and teardown_particles().
Referenced by main().
test_slots_gc_sorted()
static void test_slots_gc_sorted (void ** state) static
Definition at line 86 of file test_slotsmanager.c.
 {
     setup_particles(state);
     int i;
     for(i = 0; i < 6; i ++) {
         slots_mark_garbage(128 * i, PartManager, SlotsManager);
     }
     slots_gc_sorted(PartManager, SlotsManager);
     assert_int_equal(PartManager->NumPart, 127 * i);
     assert_int_equal(SlotsManager->info[0].size, 127);
     assert_int_equal(SlotsManager->info[4].size, 127);
     assert_int_equal(SlotsManager->info[5].size, 127);
     slots_check_id_consistency(PartManager, SlotsManager);
     teardown_particles(state);
     return;
 }
References slots_manager_type::info, part_manager_type::NumPart, PartManager, setup_particles(), slot_info::size, slots_check_id_consistency(), slots_gc_sorted(), slots_mark_garbage(), SlotsManager, and teardown_particles().
Referenced by main().
test_slots_reserve()
static void test_slots_reserve (void ** state) static
Definition at line 106 of file test_slotsmanager.c.
 {
     /* FIXME: these depends on the magic numbers in slots_reserve. After
      * moving those numbers to All.* we shall rework the code here. */
     setup_particles(state);
     int64_t newSlots[6] = {128, 128, 128, 128, 128, 128};
     int64_t oldSize[6];
     int ptype;
     for(ptype = 0; ptype < 6; ptype++) {
         oldSize[ptype] = SlotsManager->info[ptype].maxsize;
     }
     slots_reserve(1, newSlots, SlotsManager);
     /* shall not increase max size*/
     for(ptype = 0; ptype < 6; ptype++) {
         assert_int_equal(oldSize[ptype], SlotsManager->info[ptype].maxsize);
     }
     for(ptype = 0; ptype < 6; ptype++) {
         newSlots[ptype] += 1;
     }
     /* shall not increase max size; because it is small difference */
     slots_reserve(1, newSlots, SlotsManager);
     for(ptype = 0; ptype < 6; ptype++) {
         assert_int_equal(oldSize[ptype], SlotsManager->info[ptype].maxsize);
     }
     for(ptype = 0; ptype < 6; ptype++) {
         newSlots[ptype] += 8192;
     }
     /* shall increase max size; because it large difference */
     slots_reserve(1, newSlots, SlotsManager);
     for(ptype = 0; ptype < 6; ptype++) {
         assert_true(oldSize[ptype] < SlotsManager->info[ptype].maxsize);
     }
 }
References slots_manager_type::info, slot_info::maxsize, ptype, setup_particles(), slots_reserve(), and SlotsManager.
Referenced by main().
test_slots_zero()
static void test_slots_zero (void ** state) static
Definition at line 150 of file test_slotsmanager.c.
 {
     setup_particles(state);
     int i;
     int compact[6] = {1,0,0,0,1,1};
     for(i = 0; i < PartManager->NumPart; i ++) {
         slots_mark_garbage(i, PartManager, SlotsManager);
     }
     slots_gc(compact, PartManager, SlotsManager);
     assert_int_equal(PartManager->NumPart, 0);
     assert_int_equal(SlotsManager->info[0].size, 0);
     assert_int_equal(SlotsManager->info[1].size, 128);
     assert_int_equal(SlotsManager->info[4].size, 0);
     assert_int_equal(SlotsManager->info[5].size, 0);
     teardown_particles(state);
     setup_particles(state);
     for(i = 0; i < PartManager->NumPart; i ++) {
         slots_mark_garbage(i, PartManager, SlotsManager);
     }
     slots_gc_sorted(PartManager, SlotsManager);
     assert_int_equal(PartManager->NumPart, 0);
     assert_int_equal(SlotsManager->info[0].size, 0);
     assert_int_equal(SlotsManager->info[4].size, 0);
     assert_int_equal(SlotsManager->info[5].size, 0);
     teardown_particles(state);
     return;
 }
References slots_manager_type::info, part_manager_type::NumPart, PartManager, setup_particles(), slot_info::size, slots_gc(), slots_gc_sorted(), slots_mark_garbage(), SlotsManager, and teardown_particles().
Referenced by main().
Variable Documentation
PartManager
struct part_manager_type PartManager[1] = {{0}}
Definition at line 1 of file test_slotsmanager.c.
Referenced by setup_particles(), teardown_particles(), test_slots_convert(), test_slots_fork(), test_slots_gc(), test_slots_gc_sorted(), and test_slots_zero().