MP-Gadget: timefac.c File Reference
timefac.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_integration.h>
#include "allvars.h"
#include "timefac.h"
#include "timebinmgr.h"
#include "cosmology.h"
#include "endrun.h"
Macros
#define DRIFT_TABLE_LENGTH 2000
#define WORKSIZE 100000
Functions
static double drift_integ (double a, void *param)
static double gravkick_integ (double a, void *param)
static double hydrokick_integ (double a, void *param)
void init_drift_table (double timeBegin, double timeMax)
int find_bin_number (inttime_t ti0, double *rem)
double get_drift_factor (inttime_t ti0, inttime_t ti1)
double get_gravkick_factor (inttime_t ti0, inttime_t ti1)
double get_hydrokick_factor (inttime_t ti0, inttime_t ti1)
Variables
static double logTimeInit
static double logTimeMax
static double DriftTable [DRIFT_TABLE_LENGTH]
static double GravKickTable [DRIFT_TABLE_LENGTH]
static double HydroKickTable [DRIFT_TABLE_LENGTH]
static inttime_t df_last_ti0 = -1
static inttime_t df_last_ti1 = -1
static double df_last_value
static inttime_t hk_last_ti0 = -1
static inttime_t hk_last_ti1 = -1
static double hk_last_value
static inttime_t gk_last_ti0 = -1
static inttime_t gk_last_ti1 = -1
static double gk_last_value
Macro Definition Documentation
DRIFT_TABLE_LENGTH
#define DRIFT_TABLE_LENGTH 2000
length of the lookup table used to hold the drift and kick factors
Definition at line 16 of file timefac.c.
Referenced by find_bin_number(), and init_drift_table().
WORKSIZE
#define WORKSIZE 100000
Referenced by init_drift_table(), and intgf_init().
Function Documentation
drift_integ()
static double drift_integ (double a, void * param) static
Definition at line 42 of file timefac.c.
References h, and hubble_function().
Referenced by init_drift_table().
 {
   double h;
   h = hubble_function(a);
   return 1 / (h * a * a * a);
 }
find_bin_number()
int find_bin_number (inttime_t ti0, double * rem)
Definition at line 115 of file timefac.c.
References DRIFT_TABLE_LENGTH, loga_from_ti(), logTimeInit, and logTimeMax.
Referenced by get_drift_factor(), get_gravkick_factor(), and get_hydrokick_factor().
 {
   double a1 = loga_from_ti(ti0);
   double u1;
   int i1;
   u1 = (a1 - logTimeInit) / (logTimeMax - logTimeInit) * DRIFT_TABLE_LENGTH;
   i1 = (int) u1;
   /*Bound u1*/
   if(i1 >= DRIFT_TABLE_LENGTH)
     i1 = DRIFT_TABLE_LENGTH - 1;
   if(i1 <=1)
       i1=1;
   *rem = u1;
   return i1;
 }
get_drift_factor()
double get_drift_factor (inttime_t ti0, inttime_t ti1)
This function integrates the cosmological prefactor for a drift step between ti0 and ti1. The value returned is
A lookup-table is used for reasons of speed.
Definition at line 139 of file timefac.c.
References df_last_ti0, df_last_ti1, df_last_value, DriftTable, and find_bin_number().
Referenced by real_drift_particle().
 {
   double df1, df2, u1, u2;
   int i1, i2;
   if(ti0 == df_last_ti0 && ti1 == df_last_ti1)
     return df_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * DriftTable[0];
   else
     df1 = DriftTable[i1 - 1] + (DriftTable[i1] - DriftTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * DriftTable[0];
   else
     df2 = DriftTable[i2 - 1] + (DriftTable[i2] - DriftTable[i2 - 1]) * (u2 - i2);
   df_last_ti0 = ti0;
   df_last_ti1 = ti1;
   return df_last_value = (df2 - df1);
 }
get_gravkick_factor()
double get_gravkick_factor (inttime_t ti0, inttime_t ti1)
Definition at line 166 of file timefac.c.
References find_bin_number(), gk_last_ti0, gk_last_ti1, gk_last_value, and GravKickTable.
Referenced by do_the_long_range_kick(), do_the_short_range_kick(), and sph_VelPred().
 {
   double df1, df2, u1, u2;
   int i1, i2;
   if(ti0 == gk_last_ti0 && ti1 == gk_last_ti1)
     return gk_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * GravKickTable[0];
   else
     df1 = GravKickTable[i1 - 1] + (GravKickTable[i1] - GravKickTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * GravKickTable[0];
   else
     df2 = GravKickTable[i2 - 1] + (GravKickTable[i2] - GravKickTable[i2 - 1]) * (u2 - i2);
   gk_last_ti0 = ti0;
   gk_last_ti1 = ti1;
   return gk_last_value = (df2 - df1);
 }
get_hydrokick_factor()
double get_hydrokick_factor (inttime_t ti0, inttime_t ti1)
Definition at line 193 of file timefac.c.
References find_bin_number(), hk_last_ti0, hk_last_ti1, hk_last_value, and HydroKickTable.
Referenced by do_the_short_range_kick(), and sph_VelPred().
 {
   double df1, df2,u1,u2;
   int i1, i2;
   if(ti0 == hk_last_ti0 && ti1 == hk_last_ti1)
     return hk_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * HydroKickTable[0];
   else
     df1 = HydroKickTable[i1 - 1] + (HydroKickTable[i1] - HydroKickTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * HydroKickTable[0];
   else
     df2 = HydroKickTable[i2 - 1] + (HydroKickTable[i2] - HydroKickTable[i2 - 1]) * (u2 - i2);
   hk_last_ti0 = ti0;
   hk_last_ti1 = ti1;
   return hk_last_value = (df2 - df1);
 }
gravkick_integ()
static double gravkick_integ (double a, void * param) static
Definition at line 51 of file timefac.c.
References h, and hubble_function().
Referenced by init_drift_table().
 {
   double h;
   h = hubble_function(a);
   return 1 / (h * a * a);
 }
hydrokick_integ()
static double hydrokick_integ (double a, void * param) static
Definition at line 61 of file timefac.c.
References GAMMA_MINUS1, h, and hubble_function().
Referenced by init_drift_table().
 {
   double h;
   h = hubble_function(a);
   return 1 / (h * pow(a, 3 * GAMMA_MINUS1) * a);
 }
init_drift_table()
void init_drift_table (double timeBegin, double timeMax)
Definition at line 70 of file timefac.c.
References df_last_ti0, df_last_ti1, drift_integ(), DRIFT_TABLE_LENGTH, DriftTable, endrun(), gk_last_ti0, gk_last_ti1, gravkick_integ(), GravKickTable, hk_last_ti0, hk_last_ti1, hydrokick_integ(), HydroKickTable, logTimeInit, logTimeMax, and WORKSIZE.
Referenced by init().
 {
 #define WORKSIZE 100000
   int i;
   double result, abserr;
   gsl_function F;
   gsl_integration_workspace *workspace;
   logTimeInit = log(timeBegin);
   logTimeMax = log(timeMax);
   if(logTimeMax <=logTimeInit)
       endrun(1,"Error: Invalid drift table range: (%d->%d)\n", timeBegin, timeMax);
   workspace = gsl_integration_workspace_alloc(WORKSIZE);
   for(i = 0; i < DRIFT_TABLE_LENGTH; i++)
     {
       F.function = &drift_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       DriftTable[i] = result;
       F.function = &gravkick_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       GravKickTable[i] = result;
       F.function = &hydrokick_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       HydroKickTable[i] = result;
     }
   gsl_integration_workspace_free(workspace);
   df_last_ti0 = df_last_ti1 = gk_last_ti0 = gk_last_ti1 = hk_last_ti0 = hk_last_ti1 = -1;
 }
Variable Documentation
df_last_ti0
inttime_t df_last_ti0 = -1 static
Definition at line 30 of file timefac.c.
Referenced by get_drift_factor(), and init_drift_table().
df_last_ti1
inttime_t df_last_ti1 = -1 static
Definition at line 30 of file timefac.c.
Referenced by get_drift_factor(), and init_drift_table().
df_last_value
double df_last_value static
Definition at line 31 of file timefac.c.
Referenced by get_drift_factor().
DriftTable
double DriftTable[DRIFT_TABLE_LENGTH] static
table for the cosmological drift factors
Definition at line 22 of file timefac.c.
Referenced by get_drift_factor(), and init_drift_table().
gk_last_ti0
inttime_t gk_last_ti0 = -1 static
Definition at line 38 of file timefac.c.
Referenced by get_gravkick_factor(), and init_drift_table().
gk_last_ti1
inttime_t gk_last_ti1 = -1 static
Definition at line 38 of file timefac.c.
Referenced by get_gravkick_factor(), and init_drift_table().
gk_last_value
double gk_last_value static
Definition at line 39 of file timefac.c.
Referenced by get_gravkick_factor().
GravKickTable
double GravKickTable[DRIFT_TABLE_LENGTH] static
table for the cosmological kick factor for gravitational forces
Definition at line 25 of file timefac.c.
Referenced by get_gravkick_factor(), and init_drift_table().
hk_last_ti0
inttime_t hk_last_ti0 = -1 static
Definition at line 34 of file timefac.c.
Referenced by get_hydrokick_factor(), and init_drift_table().
hk_last_ti1
inttime_t hk_last_ti1 = -1 static
Definition at line 34 of file timefac.c.
Referenced by get_hydrokick_factor(), and init_drift_table().
hk_last_value
double hk_last_value static
Definition at line 35 of file timefac.c.
Referenced by get_hydrokick_factor().
HydroKickTable
double HydroKickTable[DRIFT_TABLE_LENGTH] static
table for the cosmological kick factor for hydrodynmical forces
Definition at line 28 of file timefac.c.
Referenced by get_hydrokick_factor(), and init_drift_table().
logTimeInit
double logTimeInit static
Definition at line 18 of file timefac.c.
Referenced by find_bin_number(), init_drift_table(), and intgf_init().
logTimeMax
double logTimeMax static
Definition at line 19 of file timefac.c.
Referenced by find_bin_number(), init_drift_table(), and intgf_init().