MP-Gadget: timefac.h File Reference
timefac.h File Reference
Functions
void init_drift_table (double timeBegin, double timeMax)
double get_hydrokick_factor (inttime_t ti0, inttime_t ti1)
double get_gravkick_factor (inttime_t ti0, inttime_t ti1)
double get_drift_factor (inttime_t ti0, inttime_t ti1)
Function Documentation
get_drift_factor()
double get_drift_factor (inttime_t ti0, inttime_t ti1)
This function integrates the cosmological prefactor for a drift step between ti0 and ti1. The value returned is
\[ \int_{a_0}^{a_1} \frac{{\rm d}a}{H(a) a^3} \]
A lookup-table is used for reasons of speed.
Definition at line 139 of file timefac.c.
References df_last_ti0, df_last_ti1, df_last_value, DriftTable, and find_bin_number().
Referenced by real_drift_particle().
 {
   double df1, df2, u1, u2;
   int i1, i2;
   if(ti0 == df_last_ti0 && ti1 == df_last_ti1)
     return df_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * DriftTable[0];
   else
     df1 = DriftTable[i1 - 1] + (DriftTable[i1] - DriftTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * DriftTable[0];
   else
     df2 = DriftTable[i2 - 1] + (DriftTable[i2] - DriftTable[i2 - 1]) * (u2 - i2);
   df_last_ti0 = ti0;
   df_last_ti1 = ti1;
   return df_last_value = (df2 - df1);
 }
get_gravkick_factor()
double get_gravkick_factor (inttime_t ti0, inttime_t ti1)
Definition at line 166 of file timefac.c.
References find_bin_number(), gk_last_ti0, gk_last_ti1, gk_last_value, and GravKickTable.
Referenced by do_the_long_range_kick(), do_the_short_range_kick(), and sph_VelPred().
 {
   double df1, df2, u1, u2;
   int i1, i2;
   if(ti0 == gk_last_ti0 && ti1 == gk_last_ti1)
     return gk_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * GravKickTable[0];
   else
     df1 = GravKickTable[i1 - 1] + (GravKickTable[i1] - GravKickTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * GravKickTable[0];
   else
     df2 = GravKickTable[i2 - 1] + (GravKickTable[i2] - GravKickTable[i2 - 1]) * (u2 - i2);
   gk_last_ti0 = ti0;
   gk_last_ti1 = ti1;
   return gk_last_value = (df2 - df1);
 }
get_hydrokick_factor()
double get_hydrokick_factor (inttime_t ti0, inttime_t ti1)
Definition at line 193 of file timefac.c.
References find_bin_number(), hk_last_ti0, hk_last_ti1, hk_last_value, and HydroKickTable.
Referenced by do_the_short_range_kick(), and sph_VelPred().
 {
   double df1, df2,u1,u2;
   int i1, i2;
   if(ti0 == hk_last_ti0 && ti1 == hk_last_ti1)
     return hk_last_value;
   /* note: will only be called for cosmological integration */
   i1 = find_bin_number(ti0, &u1);
   if(i1 <= 1)
     df1 = u1 * HydroKickTable[0];
   else
     df1 = HydroKickTable[i1 - 1] + (HydroKickTable[i1] - HydroKickTable[i1 - 1]) * (u1 - i1);
   i2 = find_bin_number(ti1, &u2);
   if(i2 <= 1)
     df2 = u2 * HydroKickTable[0];
   else
     df2 = HydroKickTable[i2 - 1] + (HydroKickTable[i2] - HydroKickTable[i2 - 1]) * (u2 - i2);
   hk_last_ti0 = ti0;
   hk_last_ti1 = ti1;
   return hk_last_value = (df2 - df1);
 }
init_drift_table()
void init_drift_table (double timeBegin, double timeMax)
Definition at line 70 of file timefac.c.
References df_last_ti0, df_last_ti1, drift_integ(), DRIFT_TABLE_LENGTH, DriftTable, endrun(), gk_last_ti0, gk_last_ti1, gravkick_integ(), GravKickTable, hk_last_ti0, hk_last_ti1, hydrokick_integ(), HydroKickTable, logTimeInit, logTimeMax, and WORKSIZE.
Referenced by init().
 {
 #define WORKSIZE 100000
   int i;
   double result, abserr;
   gsl_function F;
   gsl_integration_workspace *workspace;
   logTimeInit = log(timeBegin);
   logTimeMax = log(timeMax);
   if(logTimeMax <=logTimeInit)
       endrun(1,"Error: Invalid drift table range: (%d->%d)\n", timeBegin, timeMax);
   workspace = gsl_integration_workspace_alloc(WORKSIZE);
   for(i = 0; i < DRIFT_TABLE_LENGTH; i++)
     {
       F.function = &drift_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       DriftTable[i] = result;
       F.function = &gravkick_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       GravKickTable[i] = result;
       F.function = &hydrokick_integ;
       gsl_integration_qag(&F, exp(logTimeInit),
               exp(logTimeInit + ((logTimeMax - logTimeInit) / DRIFT_TABLE_LENGTH) * (i + 1)), 0,
               1.0e-8, WORKSIZE, GSL_INTEG_GAUSS41, workspace, &result, &abserr);
       HydroKickTable[i] = result;
     }
   gsl_integration_workspace_free(workspace);
   df_last_ti0 = df_last_ti1 = gk_last_ti0 = gk_last_ti1 = hk_last_ti0 = hk_last_ti1 = -1;
 }