MP-Gadget: libgadget/utils/unitsystem.c File Reference
unitsystem.c File Reference
#include "unitsystem.h"
#include <math.h>
Functions
struct UnitSystem get_unitsystem (double UnitLength_in_cm, double UnitMass_in_g, double UnitVelocity_in_cm_per_s)
Function Documentation
get_unitsystem()
struct UnitSystem get_unitsystem (double UnitLength_in_cm, double UnitMass_in_g, double UnitVelocity_in_cm_per_s)
Definition at line 1 of file unitsystem.c.
 {
     struct UnitSystem units;
     units.UnitMass_in_g = UnitMass_in_g;
     units.UnitVelocity_in_cm_per_s = UnitVelocity_in_cm_per_s;
     units.UnitLength_in_cm = UnitLength_in_cm;
     units.UnitTime_in_s = units.UnitLength_in_cm / units.UnitVelocity_in_cm_per_s;
     units.UnitDensity_in_cgs = units.UnitMass_in_g / pow(units.UnitLength_in_cm, 3);
     units.UnitEnergy_in_cgs = units.UnitMass_in_g * pow(units.UnitLength_in_cm, 2) / pow(units.UnitTime_in_s, 2);
     units.UnitInternalEnergy_in_cgs = units.UnitEnergy_in_cgs / units.UnitMass_in_g;
     return units;
 }
References UnitSystem::UnitDensity_in_cgs, UnitSystem::UnitEnergy_in_cgs, UnitSystem::UnitInternalEnergy_in_cgs, UnitSystem::UnitLength_in_cm, UnitSystem::UnitMass_in_g, UnitSystem::UnitTime_in_s, and UnitSystem::UnitVelocity_in_cm_per_s.
Referenced by begrun(), do_density_test(), do_force_test(), main(), run(), setup(), and setup_cosmology().