MP-Gadget: walltime.h File Reference
walltime.h File Reference
Classes
struct Clock
struct ClockTable
Macros
#define WALLTIME_IGNORE "."
#define LINENO(a, b) a ":" # b
#define walltime_measure(name) walltime_measure_full(name, __FILE__ , __LINE__)
#define walltime_add(name, dt) walltime_add_full(name, dt, __FILE__, __LINE__)
#define walltime_step_min(id) walltime_get(id, CLOCK_STEP_MIN)
#define walltime_step_max(id) walltime_get(id, CLOCK_STEP_MAX)
#define walltime_step_mean(id) walltime_get(id, CLOCK_STEP_MEAN)
#define walltime_accu_min(id) walltime_get(id, CLOCK_ACCU_MIN)
#define walltime_accu_max(id) walltime_get(id, CLOCK_ACCU_MAX)
#define walltime_accu_mean(id) walltime_get(id, CLOCK_ACCU_MEAN)
Enumerations
enum clocktype {
CLOCK_STEP_MEAN, CLOCK_STEP_MAX, CLOCK_STEP_MIN, CLOCK_ACCU_MEAN,
CLOCK_ACCU_MAX, CLOCK_ACCU_MIN
}
Functions
int walltime_clock (char *name)
void walltime_reset ()
double walltime_measure_internal (char *name)
double walltime_add_internal (char *name, double dt)
double walltime_measure_full (char *name, char *file, int line)
double walltime_add_full (char *name, double dt, char *file, int line)
char walltime_get_symbol (char *name)
double walltime_get_time (char *name)
double walltime_get (char *name, enum clocktype type)
void walltime_summary (int root, MPI_Comm comm)
void walltime_report (FILE *fd, int root, MPI_Comm comm)
void walltime_init (struct ClockTable *table)
Macro Definition Documentation
LINENO
#define LINENO (a, b) a ":" # b
Definition at line 4 of file walltime.h.
walltime_accu_max
#define walltime_accu_max (id) walltime_get(id, CLOCK_ACCU_MAX)
Definition at line 30 of file walltime.h.
walltime_accu_mean
#define walltime_accu_mean (id) walltime_get(id, CLOCK_ACCU_MEAN)
Definition at line 31 of file walltime.h.
walltime_accu_min
#define walltime_accu_min (id) walltime_get(id, CLOCK_ACCU_MIN)
Definition at line 29 of file walltime.h.
walltime_add
#define walltime_add (name, dt) walltime_add_full(name, dt, __FILE__, __LINE__)
Definition at line 6 of file walltime.h.
Referenced by density_internal(), grav_short_tree(), grav_short_tree_old(), and hydro_force().
WALLTIME_IGNORE
#define WALLTIME_IGNORE "."
Definition at line 3 of file walltime.h.
Referenced by density_internal(), grav_short_tree(), grav_short_tree_old(), and hydro_force().
walltime_measure
#define walltime_measure (name) walltime_measure_full(name, __FILE__ , __LINE__)
Definition at line 5 of file walltime.h.
Referenced by _prepare(), apply_half_kick(), apply_PM_half_kick(), compute_accelerations(), cooling_only(), density_internal(), domain_attempt_decompose(), domain_balance(), domain_check_for_local_refine_subsample(), domain_decompose_full(), domain_determine_global_toptree(), domain_exchange(), domain_exchange_once(), domain_maintain(), drift_active_particles(), drift_all_particles(), find_timesteps(), fof_finish(), fof_fof(), fof_save_particles(), fof_seed(), force_tree_rebuild(), force_update_hmax(), grav_short_pair(), grav_short_tree(), grav_short_tree_old(), gravpm_force(), hydro_force(), petapm_force_c2r(), petapm_force_init(), petapm_force_r2c(), run(), and write_snapshot().
walltime_step_max
#define walltime_step_max (id) walltime_get(id, CLOCK_STEP_MAX)
Definition at line 27 of file walltime.h.
walltime_step_mean
#define walltime_step_mean (id) walltime_get(id, CLOCK_STEP_MEAN)
Definition at line 28 of file walltime.h.
walltime_step_min
#define walltime_step_min (id) walltime_get(id, CLOCK_STEP_MIN)
Definition at line 26 of file walltime.h.
Enumeration Type Documentation
clocktype
enum clocktype
Enumerator
CLOCK_STEP_MEAN
CLOCK_STEP_MAX
CLOCK_STEP_MIN
CLOCK_ACCU_MEAN
CLOCK_ACCU_MAX
CLOCK_ACCU_MIN
Definition at line 12 of file walltime.h.
                {
     CLOCK_STEP_MEAN ,
     CLOCK_STEP_MAX ,
     CLOCK_STEP_MIN ,
     CLOCK_ACCU_MEAN ,
     CLOCK_ACCU_MAX ,
     CLOCK_ACCU_MIN ,
 };
Function Documentation
walltime_add_full()
double walltime_add_full (char * name, double dt, char * file, int line)
Definition at line 196 of file walltime.c.
References walltime_add_internal().
{
     char fullname[128] = {0};
     char * basename = file + strlen(file);
     while(basename >= file && *basename != '/') basename --;
     basename ++;
     sprintf(fullname, "%s@%s:%04d", name, basename, line);
     return walltime_add_internal(fullname, dt);
 }
walltime_add_internal()
double walltime_add_internal (char * name, double dt)
Definition at line 173 of file walltime.c.
References ClockTable::C, Clock::time, and walltime_clock().
Referenced by walltime_add_full().
{
     int id = walltime_clock(name);
     CT->C[id].time += dt;
     return dt;
 }
walltime_clock()
int walltime_clock (char * name)
Definition at line 107 of file walltime.c.
References ClockTable::C, clockcmp(), ClockTable::N, Clock::name, and walltime_clock_insert().
Referenced by walltime_add_internal(), walltime_clock_insert(), walltime_get(), walltime_get_symbol(), walltime_get_time(), and walltime_measure_internal().
{
     struct Clock dummy;
     strcpy(dummy.name, name);
     struct Clock * rt = bsearch(&dummy, CT->C, CT->N, sizeof(struct Clock), clockcmp);
     if(rt == NULL) {
         walltime_clock_insert(name);
         rt = bsearch(&dummy, CT->C, CT->N, sizeof(struct Clock), clockcmp);
     }
     return rt - CT->C;
 };
walltime_get()
double walltime_get (char * name, enum clocktype type)
Definition at line 123 of file walltime.c.
References ClockTable::AC, ClockTable::C, CLOCK_ACCU_MAX, CLOCK_ACCU_MEAN, CLOCK_ACCU_MIN, CLOCK_STEP_MAX, CLOCK_STEP_MEAN, CLOCK_STEP_MIN, Clock::max, Clock::mean, Clock::min, and walltime_clock().
{
     int id = walltime_clock(name);
     /* only make sense on root */
     switch(type) {
         case CLOCK_STEP_MEAN:
             return CT->C[id].mean;
         case CLOCK_STEP_MIN:
             return CT->C[id].min;
         case CLOCK_STEP_MAX:
             return CT->C[id].max;
         case CLOCK_ACCU_MEAN:
             return CT->AC[id].mean;
         case CLOCK_ACCU_MIN:
             return CT->AC[id].min;
         case CLOCK_ACCU_MAX:
             return CT->AC[id].max;
     }
     return 0;
 }
walltime_get_symbol()
char walltime_get_symbol (char * name)
Definition at line 118 of file walltime.c.
References ClockTable::C, Clock::symbol, and walltime_clock().
{
     int id = walltime_clock(name);
     return CT->C[id].symbol;
 }
walltime_get_time()
double walltime_get_time (char * name)
Definition at line 142 of file walltime.c.
References ClockTable::C, Clock::time, and walltime_clock().
{
     int id = walltime_clock(name);
     return CT->C[id].time;
 }
walltime_init()
void walltime_init (struct ClockTable * table)
Definition at line 18 of file walltime.c.
References ClockTable::ElapsedTime, LastReportTime, ClockTable::N, ClockTable::Nmax, seconds(), walltime_clock_insert(), and walltime_reset().
Referenced by begrun(), and walltime_report().
{
     CT = ct;
     CT->Nmax = 512;
     CT->N = 0;
     CT->ElapsedTime = 0;
     walltime_reset();
     walltime_clock_insert("/");
     LastReportTime = seconds();
 }
walltime_measure_full()
double walltime_measure_full (char * name, char * file, int line)
Definition at line 188 of file walltime.c.
References walltime_measure_internal().
{
     char fullname[128] = {0};
     char * basename = file + strlen(file);
     while(basename >= file && *basename != '/') basename --;
     basename ++;
     sprintf(fullname, "%s@%s:%04d", name, basename, line);
     return walltime_measure_internal(fullname);
 }
walltime_measure_internal()
double walltime_measure_internal (char * name)
Definition at line 178 of file walltime.c.
References ClockTable::C, seconds(), Clock::time, walltime_clock(), and WallTimeClock.
Referenced by walltime_measure_full().
{
     double t = seconds();
     double dt = t - WallTimeClock;
     WallTimeClock = seconds();
     if(name[0] != '.') {
         int id = walltime_clock(name);
         CT->C[id].time += dt;
     }
     return dt;
 }
walltime_report()
void walltime_report (FILE * fd, int root, MPI_Comm comm)
Definition at line 213 of file walltime.c.
References ClockTable::AC, ClockTable::C, ClockTable::ElapsedTime, main(), Clock::max, Clock::mean, Clock::min, ClockTable::N, Clock::name, name, ClockTable::Nchildren, ClockTable::StepTime, and walltime_init().
Referenced by write_cpu_log().
{
     int rank;
     MPI_Comm_rank(comm, &rank);
     if(rank != root) return;
     int i;
     for(i = 0; i < CT->N; i ++) {
         char * name = CT->C[i].name;
         int level = 0;
         char * p = name;
         while(*p) {
             if(*p == '/') {
                 level ++;
                 name = p + 1;
             }
             p++;
         }
         /* if there is just one child, don't print it*/
         if(CT->Nchildren[i] == 1) continue;
         fprintf(fp, "%*s%-26s  %10.2f %4.1f%%  %10.2f %4.1f%%  %10.2f %10.2f\n",
                 level, "",  /* indents */
                 name,   /* just the last seg of name*/
                 CT->AC[i].mean,
                 CT->AC[i].mean / CT->ElapsedTime * 100.,
                 CT->C[i].mean,
                 CT->C[i].mean / CT->StepTime * 100.,
                 CT->C[i].min,
                 CT->C[i].max
                 );
     }
 }
walltime_reset()
void walltime_reset ()
Definition at line 169 of file walltime.c.
References seconds(), and WallTimeClock.
Referenced by walltime_init().
                       {
     WallTimeClock = seconds();
 }
walltime_summary()
void walltime_summary (int root, MPI_Comm comm)
Definition at line 53 of file walltime.c.
References ClockTable::AC, ClockTable::C, ClockTable::ElapsedTime, LastReportTime, ClockTable::N, seconds(), ClockTable::StepTime, Clock::time, walltime_summary_clocks(), and walltime_update_parents().
Referenced by write_cpu_log().
{
     walltime_update_parents();
     int i;
     /* add to the cumulative time */
     for(i = 0; i < CT->N; i ++) {
         CT->AC[i].time += CT->C[i].time;
     }
     walltime_summary_clocks(CT->C, CT->N, root, comm);
     walltime_summary_clocks(CT->AC, CT->N, root, comm);
     /* clear .time for next step */
     for(i = 0; i < CT->N; i ++) {
         CT->C[i].time = 0;
     }
     MPI_Barrier(comm);
     /* wo do this here because all processes are sync after summary_clocks*/
     double step_all = seconds() - LastReportTime;
     LastReportTime = seconds();
     CT->ElapsedTime += step_all;
     CT->StepTime = step_all;
 }